import json
import os
import io

CURRICULUM_DIR = "curriculum"
TRACKS_DIR = os.path.join(CURRICULUM_DIR, "tracks")

def build_courses():
    # 1. Load index.json
    index_path = os.path.join(CURRICULUM_DIR, "index.json")
    if not os.path.exists(index_path):
        print("Error: index.json not found.")
        return

    with open(index_path, "r", encoding="utf-8") as f:
        curriculum = json.load(f)

    # 2. Load all track files
    course_manifest = {}
    missing_courses = []

    for filename in os.listdir(TRACKS_DIR):
        if filename.endswith(".json"):
            filepath = os.path.join(TRACKS_DIR, filename)
            with open(filepath, "r", encoding="utf-8") as f:
                track_data = json.load(f)
                # merge into course_manifest
                for course_name, course_data in track_data.items():
                    if course_name in course_manifest:
                        print(f"Warning: Duplicate course '{course_name}' found in {filename}.")
                    course_manifest[course_name] = course_data

    # 3. Validate curriculum
    print("--- Validation Report ---")
    warnings = 0
    for track_name, tiers in curriculum.items():
        for tier_name, courses in tiers.items():
            for course in courses:
                if course not in course_manifest:
                    print(f"Warning: Missing Course Data: '{course}' in track '{track_name}' ({tier_name}) is listed in index.json but missing from track JSONs.")
                    warnings += 1

    if warnings == 0:
        print("Success: All courses validated successfully.")
    else:
        print(f"Warning: Found {warnings} missing courses. They will not have lessons in the generated courses.js.")

    print("-------------------------\n")

    # 4. Generate courses.js and curriculum.json
    output_js = "// ═══════════════════════════════════════════════════\n"
    output_js += "//  MABEL ACADEMY — courses.js  (Mega Expanded Edition)\n"
    output_js += "//  [AUTO-GENERATED FILE] Do not edit this file directly!\n"
    output_js += "//  Edit the JSON files in the curriculum/ directory instead.\n"
    output_js += "// ═══════════════════════════════════════════════════\n\n"

    output_js += "export const curriculum = " + json.dumps(curriculum, indent=2, ensure_ascii=False) + ";\n\n"
    output_js += "export const courseManifest = " + json.dumps(course_manifest, indent=2, ensure_ascii=False) + "; // end courseManifest\n"

    # We still write courses.js for backward compatibility while we refactor the frontend
    with io.open("courses.js", "w", encoding="utf-8") as f:
        f.write(output_js)
    frontend_path = os.path.join("frontend", "src", "data", "courses.js")
    with io.open(frontend_path, "w", encoding="utf-8") as f:
        f.write(output_js)

    # Output static JSON to public folder to avoid massive JS bundles
    public_json = {
        "curriculum": curriculum,
        "courseManifest": course_manifest
    }
    public_path = os.path.join("frontend", "public", "curriculum.json")
    with io.open(public_path, "w", encoding="utf-8") as f:
        json.dump(public_json, f, ensure_ascii=False)

    print("Success: Successfully built courses.js and curriculum.json from JSON modules.")

if __name__ == "__main__":
    build_courses()
