"""
Batch 2: Expand more courses with 3 new lessons each.
Covers: Backend, AI Engineering, Version Control, more Python Core, more SQL, more Frontend
"""
import json

NEW_LESSONS = {

# ─── BACKEND: BEGINNER ───
"HTTP & REST Concepts": [
  {
    "title": "HTTP Status Codes Deep Dive",
    "theory": "## Status Codes\n```python\n# 1xx: Informational\n# 2xx: Success\n#   200 OK, 201 Created, 204 No Content\n# 3xx: Redirection\n#   301 Moved Permanently, 304 Not Modified\n# 4xx: Client Error\n#   400 Bad Request, 401 Unauthorized, 403 Forbidden, 404 Not Found\n# 5xx: Server Error\n#   500 Internal Server Error, 502 Bad Gateway, 503 Service Unavailable\n```",
    "instructions": "## Task: Status Code Validator\n1. Create a dict mapping status codes to their meanings\n2. Write a function that categorizes any status code\n3. Test with various codes and print results",
    "starterCode": "STATUS_CODES = {\n    200: 'OK', 201: 'Created', 204: 'No Content',\n    301: 'Moved Permanently', 304: 'Not Modified',\n    400: '___', 401: 'Unauthorized', 403: 'Forbidden', 404: '___',\n    500: 'Internal Server Error', 502: 'Bad Gateway', 503: '___'\n}\n\ndef categorize(code):\n    if 200 <= code < 300: return 'SUCCESS'\n    if 300 <= code < 400: return '___'\n    if 400 <= code < 500: return 'CLIENT_ERROR'\n    if 500 <= code < 600: return '___'\n    return 'UNKNOWN'\n\nfor code in [200, 201, 301, 400, 404, 500, 503]:\n    cat = categorize(code)\n    name = STATUS_CODES.get(code, 'Unknown')\n    print(f'{code} {name:25} [{cat}]')",
    "solution": "STATUS_CODES={200:'OK',201:'Created',204:'No Content',301:'Moved Permanently',304:'Not Modified',400:'Bad Request',401:'Unauthorized',403:'Forbidden',404:'Not Found',500:'Internal Server Error',502:'Bad Gateway',503:'Service Unavailable'}\ndef categorize(code):\n    if 200<=code<300:return 'SUCCESS'\n    if 300<=code<400:return 'REDIRECT'\n    if 400<=code<500:return 'CLIENT_ERROR'\n    if 500<=code<600:return 'SERVER_ERROR'\n    return 'UNKNOWN'\nfor code in [200,201,301,400,404,500,503]:\n    cat=categorize(code)\n    name=STATUS_CODES.get(code,'Unknown')\n    print(f'{code} {name:25} [{cat}]')",
    "hint": "400 is Bad Request, 404 is Not Found, 503 is Service Unavailable. 3xx = REDIRECT, 5xx = SERVER_ERROR.",
    "rubric": "Status codes mapped. categorize function works. All ranges covered. Output formatted."
  },
  {
    "title": "Request Headers & Content Types",
    "theory": "## HTTP Headers\n```python\nheaders = {\n    'Content-Type': 'application/json',\n    'Authorization': 'Bearer token123',\n    'Accept': 'application/json',\n    'User-Agent': 'MyApp/1.0',\n    'Cache-Control': 'no-cache'\n}\n\n# Common Content-Types:\n# application/json  — JSON data\n# text/html         — Web pages\n# multipart/form-data — File uploads\n# application/x-www-form-urlencoded — Form data\n```",
    "instructions": "## Task: Header Builder\n1. Create a function that builds proper headers for different request types\n2. Support: 'json', 'form', 'file', 'auth'\n3. Each type returns appropriate Content-Type and other headers",
    "starterCode": "def build_headers(request_type, token=None):\n    headers = {}\n    \n    if request_type == 'json':\n        headers['Content-Type'] = '___'\n        headers['Accept'] = 'application/json'\n    elif request_type == 'form':\n        headers['Content-Type'] = '___'\n    elif request_type == 'file':\n        headers['Content-Type'] = '___'\n    \n    if token:\n        headers['Authorization'] = f'Bearer {___}'\n    \n    return headers\n\nfor req_type in ['json', 'form', 'file']:\n    h = build_headers(req_type, token='abc123')\n    print(f'\\n{req_type.upper()} Headers:')\n    for k, v in h.items():\n        print(f'  {k}: {v}')",
    "solution": "def build_headers(request_type,token=None):\n    headers={}\n    if request_type=='json':\n        headers['Content-Type']='application/json'\n        headers['Accept']='application/json'\n    elif request_type=='form':headers['Content-Type']='application/x-www-form-urlencoded'\n    elif request_type=='file':headers['Content-Type']='multipart/form-data'\n    if token:headers['Authorization']=f'Bearer {token}'\n    return headers\nfor req_type in ['json','form','file']:\n    h=build_headers(req_type,token='abc123')\n    print(f'\\n{req_type.upper()} Headers:')\n    for k,v in h.items():print(f'  {k}: {v}')",
    "hint": "application/json for JSON. application/x-www-form-urlencoded for forms. multipart/form-data for files.",
    "rubric": "Content-Type set per type. Bearer token added. All 3 types tested. Headers printed."
  },
  {
    "title": "CRUD Operations Explained",
    "theory": "## CRUD = Create, Read, Update, Delete\n```python\n# HTTP Method → CRUD Operation\n# POST   → Create\n# GET    → Read\n# PUT    → Update (full replace)\n# PATCH  → Update (partial)\n# DELETE → Delete\n\n# REST endpoint pattern:\n# GET    /students      — List all\n# GET    /students/1    — Get one\n# POST   /students      — Create\n# PUT    /students/1    — Update\n# DELETE /students/1    — Delete\n```",
    "instructions": "## Task: REST API Simulator\n1. Build an in-memory CRUD system using a list\n2. Implement create, read_all, read_one, update, delete\n3. Simulate REST operations and print results",
    "starterCode": "class RESTSimulator:\n    def __init__(self):\n        self.data = []\n        self.next_id = 1\n    \n    def create(self, item):\n        item['id'] = self.next_id\n        self.next_id += 1\n        self.data.append(item)\n        return f'201 Created: {item}'\n    \n    def read_all(self):\n        return self.___\n    \n    def read_one(self, id):\n        for item in self.data:\n            if item['id'] == ___:\n                return item\n        return '404 Not Found'\n    \n    def update(self, id, updates):\n        for item in self.data:\n            if item['id'] == id:\n                item.___(updates)\n                return f'200 Updated: {item}'\n        return '404 Not Found'\n    \n    def delete(self, id):\n        for i, item in enumerate(self.data):\n            if item['id'] == id:\n                removed = self.data.___(i)\n                return f'200 Deleted: {removed}'\n        return '404 Not Found'\n\napi = RESTSimulator()\nprint(api.create({'name': 'Ada', 'course': 'Python'}))\nprint(api.create({'name': 'Tunde', 'course': 'SQL'}))\nprint(f'All: {api.read_all()}')\nprint(f'One: {api.read_one(1)}')\nprint(api.update(1, {'course': 'AI'}))\nprint(api.delete(2))\nprint(f'Final: {api.read_all()}')",
    "solution": "class RESTSimulator:\n    def __init__(self):self.data=[];self.next_id=1\n    def create(self,item):\n        item['id']=self.next_id;self.next_id+=1\n        self.data.append(item);return f'201 Created: {item}'\n    def read_all(self):return self.data\n    def read_one(self,id):\n        for item in self.data:\n            if item['id']==id:return item\n        return '404 Not Found'\n    def update(self,id,updates):\n        for item in self.data:\n            if item['id']==id:item.update(updates);return f'200 Updated: {item}'\n        return '404 Not Found'\n    def delete(self,id):\n        for i,item in enumerate(self.data):\n            if item['id']==id:return f'200 Deleted: {self.data.pop(i)}'\n        return '404 Not Found'\napi=RESTSimulator()\nprint(api.create({'name':'Ada','course':'Python'}))\nprint(api.create({'name':'Tunde','course':'SQL'}))\nprint(f'All: {api.read_all()}')\nprint(f'One: {api.read_one(1)}')\nprint(api.update(1,{'course':'AI'}))\nprint(api.delete(2))\nprint(f'Final: {api.read_all()}')",
    "hint": "self.data for read_all. item['id'] == id for finding. dict.update() for merging. list.pop(i) for removing.",
    "rubric": "CRUD operations implemented. ID auto-increment. 404 for missing. All operations tested."
  }
],

"REST APIs with FastAPI": [
  {
    "title": "Path Parameters & Query Strings",
    "theory": "## Path & Query Parameters\n```python\nfrom fastapi import FastAPI, Query\napp = FastAPI()\n\n# Path parameter\n@app.get('/students/{student_id}')\ndef get_student(student_id: int):\n    return {'id': student_id}\n\n# Query parameters\n@app.get('/students/')\ndef list_students(skip: int = 0, limit: int = 10, level: str = None):\n    return {'skip': skip, 'limit': limit, 'level': level}\n\n# URL: /students/?skip=0&limit=5&level=beginner\n```",
    "instructions": "## Task: Course Filter API\n1. Create a simulated FastAPI endpoint function\n2. Accept path param: track name\n3. Accept query params: level (default 'Beginner'), limit (default 10)\n4. Filter and return matching courses",
    "starterCode": "# Simulating FastAPI endpoint logic\ncourses_db = [\n    {'title': 'Python Fundamentals', 'track': 'Python Core', 'level': 'Beginner'},\n    {'title': 'OOP in Python', 'track': 'Python Core', 'level': 'Intermediate'},\n    {'title': 'SQL Fundamentals', 'track': 'SQL', 'level': 'Beginner'},\n    {'title': 'REST APIs', 'track': 'Backend', 'level': 'Intermediate'},\n    {'title': 'Decorators', 'track': 'Python Core', 'level': 'Advanced'},\n]\n\ndef get_courses(track: str, level: str = '___', limit: int = ___):\n    results = [\n        c for c in courses_db\n        if c['track'] == ___ and c['level'] == ___\n    ]\n    return results[:___]\n\n# Test different queries\nprint('Python Beginner:', get_courses('Python Core'))\nprint('Python All levels:', get_courses('Python Core', level='Intermediate'))\nprint('SQL:', get_courses('SQL', limit=1))",
    "solution": "courses_db=[{'title':'Python Fundamentals','track':'Python Core','level':'Beginner'},{'title':'OOP in Python','track':'Python Core','level':'Intermediate'},{'title':'SQL Fundamentals','track':'SQL','level':'Beginner'},{'title':'REST APIs','track':'Backend','level':'Intermediate'},{'title':'Decorators','track':'Python Core','level':'Advanced'}]\ndef get_courses(track,level='Beginner',limit=10):\n    results=[c for c in courses_db if c['track']==track and c['level']==level]\n    return results[:limit]\nprint('Python Beginner:',get_courses('Python Core'))\nprint('Python Intermediate:',get_courses('Python Core',level='Intermediate'))\nprint('SQL:',get_courses('SQL',limit=1))",
    "hint": "Default params simulate query strings. List comprehension for filtering. Slice [:limit] for pagination.",
    "rubric": "Function with default params. Filter by track and level. Limit slicing. 3 test cases."
  },
  {
    "title": "Request Body & Pydantic Models",
    "theory": "## Pydantic Models\n```python\nfrom pydantic import BaseModel, Field\n\nclass StudentCreate(BaseModel):\n    name: str\n    email: str\n    score: float = Field(ge=0, le=100)  # 0-100\n    level: str = 'Beginner'\n\n# Auto-validates!\nstudent = StudentCreate(name='Ada', email='ada@mail.com', score=92)\nprint(student.model_dump())  # Dict output\n```",
    "instructions": "## Task: Enrollment Validator\n1. Create a Pydantic model for course enrollment\n2. Include: student_name, email, course_id, experience_level\n3. Add validation: email must contain @, course_id > 0\n4. Test with valid and invalid data",
    "starterCode": "from pydantic import BaseModel, Field, field_validator\n\nclass Enrollment(BaseModel):\n    student_name: str\n    email: str\n    course_id: int = Field(gt=___)\n    experience_level: str = '___'\n    \n    @field_validator('email')\n    @classmethod\n    def validate_email(cls, v):\n        if '___' not in v:\n            raise ValueError('Invalid email')\n        return v.lower()\n\n# Valid\ntry:\n    e1 = Enrollment(student_name='Ada', email='Ada@Mail.com', course_id=1)\n    print(f'Valid: {e1.model_dump()}')\nexcept Exception as e:\n    print(f'Error: {e}')\n\n# Invalid email\ntry:\n    e2 = Enrollment(student_name='Bad', email='no-at-sign', course_id=1)\nexcept Exception as e:\n    print(f'Caught: {e}')\n\n# Invalid course_id\ntry:\n    e3 = Enrollment(student_name='Bad', email='x@y.com', course_id=___)\nexcept Exception as e:\n    print(f'Caught: {e}')",
    "solution": "from pydantic import BaseModel,Field,field_validator\nclass Enrollment(BaseModel):\n    student_name:str\n    email:str\n    course_id:int=Field(gt=0)\n    experience_level:str='Beginner'\n    @field_validator('email')\n    @classmethod\n    def validate_email(cls,v):\n        if '@' not in v:raise ValueError('Invalid email')\n        return v.lower()\ntry:\n    e1=Enrollment(student_name='Ada',email='Ada@Mail.com',course_id=1)\n    print(f'Valid: {e1.model_dump()}')\nexcept Exception as e:print(f'Error: {e}')\ntry:\n    e2=Enrollment(student_name='Bad',email='no-at-sign',course_id=1)\nexcept Exception as e:print(f'Caught: {e}')\ntry:\n    e3=Enrollment(student_name='Bad',email='x@y.com',course_id=0)\nexcept Exception as e:print(f'Caught: {e}')",
    "hint": "Field(gt=0) means greater than 0. '@' in v checks for at sign. .lower() normalizes email.",
    "rubric": "Pydantic model defined. Field validation. Custom validator. Valid and invalid tests. Errors caught."
  },
  {
    "title": "Response Models & Error Handling",
    "theory": "## Response Models\n```python\nfrom pydantic import BaseModel\nfrom fastapi import HTTPException\n\nclass StudentResponse(BaseModel):\n    id: int\n    name: str\n    level: str\n    # password is NOT here = never leaked!\n\n# Raise errors\nif not student:\n    raise HTTPException(\n        status_code=404,\n        detail='Student not found'\n    )\n```",
    "instructions": "## Task: Safe API Response\n1. Create UserCreate and UserResponse models\n2. UserResponse excludes password\n3. Build a mock endpoint that creates users and returns safe responses\n4. Handle duplicate email errors",
    "starterCode": "from pydantic import BaseModel\n\nclass UserCreate(BaseModel):\n    email: str\n    password: str\n    full_name: str\n\nclass UserResponse(BaseModel):\n    id: int\n    email: str\n    full_name: str\n    # Note: NO password field!\n\n# Mock database\nusers_db = []\nnext_id = 1\n\ndef create_user(data: dict):\n    global next_id\n    # Check duplicate\n    for u in users_db:\n        if u['email'] == data['___']:\n            return {'error': 'Email already registered', 'status': ___}\n    \n    user = {'id': next_id, 'email': data['email'], 'full_name': data['full_name'], 'password': data['password']}\n    users_db.append(user)\n    next_id += 1\n    \n    # Return SAFE response (no password)\n    safe = UserResponse(id=user['id'], email=user['___'], full_name=user['___'])\n    return safe.model_dump()\n\nprint(create_user({'email': 'ada@mail.com', 'password': 'secret123', 'full_name': 'Ada'}))\nprint(create_user({'email': 'ada@mail.com', 'password': 'other', 'full_name': 'Ada2'}))\nprint(create_user({'email': 'tunde@mail.com', 'password': 'pass456', 'full_name': 'Tunde'}))",
    "solution": "from pydantic import BaseModel\nclass UserCreate(BaseModel):\n    email:str;password:str;full_name:str\nclass UserResponse(BaseModel):\n    id:int;email:str;full_name:str\nusers_db=[];next_id=1\ndef create_user(data):\n    global next_id\n    for u in users_db:\n        if u['email']==data['email']:return{'error':'Email already registered','status':400}\n    user={'id':next_id,'email':data['email'],'full_name':data['full_name'],'password':data['password']}\n    users_db.append(user);next_id+=1\n    safe=UserResponse(id=user['id'],email=user['email'],full_name=user['full_name'])\n    return safe.model_dump()\nprint(create_user({'email':'ada@mail.com','password':'secret123','full_name':'Ada'}))\nprint(create_user({'email':'ada@mail.com','password':'other','full_name':'Ada2'}))\nprint(create_user({'email':'tunde@mail.com','password':'pass456','full_name':'Tunde'}))",
    "hint": "UserResponse has no password field. Check duplicate by email. model_dump() converts to dict.",
    "rubric": "Two Pydantic models. Password excluded from response. Duplicate check. model_dump() used."
  }
],

# ─── VERSION CONTROL ───
"Git Fundamentals": [
  {
    "title": "Git Config & Init",
    "theory": "## Git Setup\n```python\n# Simulating git commands\ngit_config = {\n    'user.name': 'Ada Okonkwo',\n    'user.email': 'ada@example.com',\n    'init.defaultBranch': 'main'\n}\n\n# git init creates:\n# .git/\n#   ├── HEAD        (current branch pointer)\n#   ├── config      (repo settings)\n#   ├── objects/    (stored commits/files)\n#   └── refs/       (branch pointers)\n```",
    "instructions": "## Task: Git Simulator\n1. Build a simple Git simulator class\n2. Support init, config, add, and status commands\n3. Track staged files and config settings\n4. Print status showing staged vs untracked files",
    "starterCode": "class GitSimulator:\n    def __init__(self):\n        self.initialized = False\n        self.config = {}\n        self.staged = []\n        self.untracked = []\n    \n    def init(self):\n        self.initialized = True\n        return 'Initialized empty Git repository'\n    \n    def set_config(self, key, value):\n        self.config[___] = value\n        return f'Set {key} = {value}'\n    \n    def add(self, filename):\n        if filename in self.untracked:\n            self.untracked.remove(filename)\n        self.___.append(filename)\n        return f'Added {filename} to staging'\n    \n    def status(self):\n        print('On branch main')\n        if self.staged:\n            print('Changes to be committed:')\n            for f in self.staged: print(f'  new file: {f}')\n        if self.___:\n            print('Untracked files:')\n            for f in self.untracked: print(f'  {f}')\n\ngit = GitSimulator()\nprint(git.init())\nprint(git.set_config('user.name', 'Ada'))\ngit.untracked = ['main.py', 'readme.md', 'test.py']\nprint(git.add('main.py'))\nprint(git.add('readme.md'))\ngit.status()",
    "solution": "class GitSimulator:\n    def __init__(self):self.initialized=False;self.config={};self.staged=[];self.untracked=[]\n    def init(self):self.initialized=True;return'Initialized empty Git repository'\n    def set_config(self,key,value):self.config[key]=value;return f'Set {key} = {value}'\n    def add(self,filename):\n        if filename in self.untracked:self.untracked.remove(filename)\n        self.staged.append(filename);return f'Added {filename} to staging'\n    def status(self):\n        print('On branch main')\n        if self.staged:\n            print('Changes to be committed:')\n            for f in self.staged:print(f'  new file: {f}')\n        if self.untracked:\n            print('Untracked files:')\n            for f in self.untracked:print(f'  {f}')\ngit=GitSimulator()\nprint(git.init())\nprint(git.set_config('user.name','Ada'))\ngit.untracked=['main.py','readme.md','test.py']\nprint(git.add('main.py'))\nprint(git.add('readme.md'))\ngit.status()",
    "hint": "self.config[key] = value. self.staged.append(). Remove from untracked when staging.",
    "rubric": "GitSimulator class. init, config, add, status methods. Files move from untracked to staged."
  },
  {
    "title": "Understanding Commits & History",
    "theory": "## Commits\n```python\nimport hashlib\nfrom datetime import datetime\n\n# A commit is a snapshot with:\n# - Hash (unique ID)\n# - Author\n# - Message\n# - Timestamp\n# - Parent commit hash\n\ndef make_hash(content):\n    return hashlib.sha1(content.encode()).hexdigest()[:7]\n\n# Example: make_hash('initial commit') -> 'a1b2c3d'\n```",
    "instructions": "## Task: Commit History\n1. Build a commit system that generates hash IDs\n2. Each commit stores message, timestamp, parent hash\n3. Create 4 commits\n4. Print a git log style history",
    "starterCode": "import hashlib\nfrom datetime import datetime\n\ndef make_hash(content):\n    return hashlib.sha1(content.encode()).hexdigest()[:7]\n\ncommits = []\n\ndef commit(message):\n    parent = commits[-1]['hash'] if ___ else None\n    hash_input = f'{message}{datetime.now()}{parent}'\n    commit_hash = make_hash(___)\n    \n    entry = {\n        'hash': commit_hash,\n        'message': message,\n        'time': datetime.now().strftime('%H:%M:%S'),\n        'parent': ___\n    }\n    commits.append(entry)\n    return f'[{commit_hash}] {message}'\n\nprint(commit('Initial commit'))\nprint(commit('Add main.py'))\nprint(commit('Add database models'))\nprint(commit('Fix login bug'))\n\nprint('\\n=== git log ===')\nfor c in reversed(___):\n    parent = f' (parent: {c[\"parent\"]})' if c['parent'] else ''\n    print(f'{c[\"hash\"]} {c[\"time\"]} {c[\"message\"]}{parent}')",
    "solution": "import hashlib\nfrom datetime import datetime\ndef make_hash(content):return hashlib.sha1(content.encode()).hexdigest()[:7]\ncommits=[]\ndef commit(message):\n    parent=commits[-1]['hash'] if commits else None\n    hash_input=f'{message}{datetime.now()}{parent}'\n    commit_hash=make_hash(hash_input)\n    entry={'hash':commit_hash,'message':message,'time':datetime.now().strftime('%H:%M:%S'),'parent':parent}\n    commits.append(entry)\n    return f'[{commit_hash}] {message}'\nprint(commit('Initial commit'))\nprint(commit('Add main.py'))\nprint(commit('Add database models'))\nprint(commit('Fix login bug'))\nprint('\\n=== git log ===')\nfor c in reversed(commits):\n    parent=f' (parent: {c[\"parent\"]})' if c['parent'] else ''\n    print(f'{c[\"hash\"]} {c[\"time\"]} {c[\"message\"]}{parent}')",
    "hint": "commits[-1] gets last commit. 'if commits' checks if list is non-empty. reversed() for newest first.",
    "rubric": "Hash generated with sha1. Parent chain linked. 4 commits created. Log printed in reverse."
  },
  {
    "title": "Branching Concepts",
    "theory": "## Branches\n```python\n# A branch is just a pointer to a commit\n# main → commit_abc\n# feature → commit_xyz\n\n# Creating and switching:\n# git branch feature\n# git checkout feature\n# OR: git checkout -b feature (create + switch)\n\n# Merging:\n# git checkout main\n# git merge feature\n```",
    "instructions": "## Task: Branch Simulator\n1. Extend the git simulator with branch support\n2. Support: create_branch, checkout, list_branches\n3. Track which branch is currently active\n4. Commits go to the active branch",
    "starterCode": "class BranchSimulator:\n    def __init__(self):\n        self.branches = {'main': []}\n        self.current = 'main'\n    \n    def create_branch(self, name):\n        if name in self.branches:\n            return f'Branch {name} already exists'\n        self.branches[___] = list(self.branches[self.current])\n        return f'Created branch {name}'\n    \n    def checkout(self, name):\n        if name not in self.___:\n            return f'Branch {name} not found'\n        self.current = ___\n        return f'Switched to {name}'\n    \n    def commit(self, message):\n        self.branches[self.___].append(message)\n        return f'[{self.current}] {message}'\n    \n    def log(self):\n        print(f'\\n=== {self.current} ===')\n        for i, msg in enumerate(self.branches[self.current]):\n            print(f'  {i+1}. {msg}')\n\ngit = BranchSimulator()\nprint(git.commit('Initial commit'))\nprint(git.commit('Add models'))\nprint(git.create_branch('feature'))\nprint(git.checkout('feature'))\nprint(git.commit('Add login page'))\nprint(git.commit('Add signup'))\ngit.log()\nprint(git.checkout('main'))\ngit.log()",
    "solution": "class BranchSimulator:\n    def __init__(self):self.branches={'main':[]};self.current='main'\n    def create_branch(self,name):\n        if name in self.branches:return f'Branch {name} exists'\n        self.branches[name]=list(self.branches[self.current])\n        return f'Created branch {name}'\n    def checkout(self,name):\n        if name not in self.branches:return f'Branch {name} not found'\n        self.current=name;return f'Switched to {name}'\n    def commit(self,message):\n        self.branches[self.current].append(message)\n        return f'[{self.current}] {message}'\n    def log(self):\n        print(f'\\n=== {self.current} ===')\n        for i,msg in enumerate(self.branches[self.current]):print(f'  {i+1}. {msg}')\ngit=BranchSimulator()\nprint(git.commit('Initial commit'))\nprint(git.commit('Add models'))\nprint(git.create_branch('feature'))\nprint(git.checkout('feature'))\nprint(git.commit('Add login page'))\nprint(git.commit('Add signup'))\ngit.log()\nprint(git.checkout('main'))\ngit.log()",
    "hint": "Copy parent branch commits with list(). self.current tracks active branch. Commits append to current.",
    "rubric": "Branch dict structure. create copies parent. checkout switches. Commits go to current branch."
  }
],

# ─── AI ENGINEERING ───
"Prompt Engineering": [
  {
    "title": "Prompt Templates & Variables",
    "theory": "## Prompt Templates\n```python\nfrom string import Template\n\n# Simple template\nprompt = Template('Explain $topic to a $level student in $language.')\nresult = prompt.substitute(topic='recursion', level='beginner', language='Python')\n\n# f-string template\ndef make_prompt(topic, level='beginner', style='concise'):\n    return f'''You are a {level}-level coding tutor.\n    Explain {topic} in a {style} way.\n    Include a code example.'''\n```",
    "instructions": "## Task: Prompt Factory\n1. Create a PromptTemplate class that stores a template string\n2. Support variable substitution with .format()\n3. Create 3 different templates: explain, quiz, debug\n4. Generate prompts for different topics",
    "starterCode": "class PromptTemplate:\n    def __init__(self, name, template):\n        self.name = name\n        self.template = template\n    \n    def generate(self, **kwargs):\n        return self.template.format(___)\n    \n    def __repr__(self):\n        return f'PromptTemplate({self.name})'\n\n# Create templates\nexplain = PromptTemplate('explain',\n    'Explain {topic} to a {level} student. Use {language} examples.')\n\nquiz = PromptTemplate('quiz',\n    'Create a {difficulty} quiz question about {topic} in {language}.')\n\ndebug = PromptTemplate('debug',\n    'Debug this {language} code that should {expected}:\\n```\\n{code}\\n```')\n\n# Generate prompts\nprint(explain.generate(topic='recursion', level='beginner', language='Python'))\nprint()\nprint(quiz.generate(topic='loops', difficulty='___', language='Python'))\nprint()\nprint(debug.generate(language='Python', expected='print Hello', code='print(Hello)'))",
    "solution": "class PromptTemplate:\n    def __init__(self,name,template):self.name=name;self.template=template\n    def generate(self,**kwargs):return self.template.format(**kwargs)\n    def __repr__(self):return f'PromptTemplate({self.name})'\nexplain=PromptTemplate('explain','Explain {topic} to a {level} student. Use {language} examples.')\nquiz=PromptTemplate('quiz','Create a {difficulty} quiz question about {topic} in {language}.')\ndebug=PromptTemplate('debug','Debug this {language} code that should {expected}:\\n```\\n{code}\\n```')\nprint(explain.generate(topic='recursion',level='beginner',language='Python'))\nprint()\nprint(quiz.generate(topic='loops',difficulty='medium',language='Python'))\nprint()\nprint(debug.generate(language='Python',expected='print Hello',code='print(Hello)'))",
    "hint": "**kwargs passes keyword args to .format(). Create 3 templates with different placeholders.",
    "rubric": "PromptTemplate class. format(**kwargs) substitution. 3 templates created. All generate correctly."
  },
  {
    "title": "Few-Shot Prompting",
    "theory": "## Few-Shot Learning\nGive the model examples to follow.\n```python\nprompt = '''Classify the sentiment:\n\nText: \"I love this course!\"\nSentiment: Positive\n\nText: \"The homework is terrible\"\nSentiment: Negative\n\nText: \"The class was okay\"\nSentiment: Neutral\n\nText: \"{user_input}\"\nSentiment:'''\n```\nThe model learns the pattern from examples and applies it.",
    "instructions": "## Task: Few-Shot Classifier\n1. Build a few-shot prompt builder for code review classification\n2. Include 3 examples (bug, style, performance)\n3. Generate the prompt for a new code snippet\n4. Parse simulated model output",
    "starterCode": "def build_few_shot(examples, new_input):\n    prompt = 'Classify the code review comment:\\n\\n'\n    \n    for example in ___:\n        prompt += f'Comment: \"{example[\"text\"]}\"\\n'\n        prompt += f'Category: {example[\"___\"]}\\n\\n'\n    \n    prompt += f'Comment: \"{new_input}\"\\nCategory:'\n    return prompt\n\nexamples = [\n    {'text': 'This will crash if the list is empty', 'category': 'Bug'},\n    {'text': 'Use snake_case for variable names', 'category': '___'},\n    {'text': 'This loop runs in O(n^2), consider a hash map', 'category': '___'},\n]\n\nnew_comments = [\n    'Missing null check on line 42',\n    'Rename this function to be more descriptive',\n    'You can avoid this nested loop with a set lookup'\n]\n\nfor comment in new_comments:\n    prompt = build_few_shot(examples, comment)\n    print(f'Input: {comment}')\n    print(f'Prompt length: {len(prompt)} chars')\n    print(f'Examples used: {len(examples)}\\n')",
    "solution": "def build_few_shot(examples,new_input):\n    prompt='Classify the code review comment:\\n\\n'\n    for example in examples:\n        prompt+=f'Comment: \"{example[\"text\"]}\"\\n'\n        prompt+=f'Category: {example[\"category\"]}\\n\\n'\n    prompt+=f'Comment: \"{new_input}\"\\nCategory:'\n    return prompt\nexamples=[{'text':'This will crash if the list is empty','category':'Bug'},{'text':'Use snake_case for variable names','category':'Style'},{'text':'This loop runs in O(n^2), consider a hash map','category':'Performance'}]\nnew_comments=['Missing null check on line 42','Rename this function to be more descriptive','You can avoid this nested loop with a set lookup']\nfor comment in new_comments:\n    prompt=build_few_shot(examples,comment)\n    print(f'Input: {comment}')\n    print(f'Prompt length: {len(prompt)} chars')\n    print(f'Examples used: {len(examples)}\\n')",
    "hint": "Loop through examples list. Access example['category']. Append new_input at the end without answer.",
    "rubric": "Few-shot format with examples. Categories: Bug, Style, Performance. New input appended. All tested."
  },
  {
    "title": "Chain-of-Thought Prompting",
    "theory": "## Chain-of-Thought\nAsk the model to think step-by-step.\n```python\nprompt = '''Solve this step by step:\n\nQuestion: A student completes 3 Python lessons worth 10 XP each,\nand 2 SQL lessons worth 15 XP each. What is their total XP?\n\nStep 1: Calculate Python XP = 3 * 10 = 30\nStep 2: Calculate SQL XP = 2 * 15 = 30\nStep 3: Total = 30 + 30 = 60\n\nAnswer: 60 XP\n'''\n```\nThis dramatically improves reasoning accuracy.",
    "instructions": "## Task: CoT Prompt Builder\n1. Create a function that builds chain-of-thought prompts\n2. It should break problems into numbered steps\n3. Build a CoT prompt for a student grade calculation\n4. Verify by computing the answer programmatically",
    "starterCode": "def build_cot_prompt(question, steps):\n    prompt = f'Solve this step by step:\\n\\nQuestion: {question}\\n\\n'\n    for i, step in enumerate(steps, start=___):\n        prompt += f'Step {i}: {step}\\n'\n    prompt += '\\nAnswer:'\n    return prompt\n\n# Problem: Calculate final grade\nsteps = [\n    'Homework average = (85 + 90 + 78) / 3 = {:.1f}'.format((85+90+78)/___),\n    'Exam average = (92 + 88) / 2 = {:.1f}'.format((92+88)/___),\n    'Final = Homework * 0.4 + Exam * 0.6',\n    'Final = {:.1f} * 0.4 + {:.1f} * 0.6 = {:.1f}'.format(\n        (85+90+78)/3, (92+88)/2,\n        (85+90+78)/3 * 0.4 + (92+88)/2 * ___\n    )\n]\n\nprompt = build_cot_prompt(\n    'Calculate the final grade. Homework is 40% and Exams are 60%.',\n    steps\n)\nprint(prompt)\n\n# Verify\nhw = (85+90+78)/3\nexam = (92+88)/2\nfinal = hw * 0.4 + exam * 0.6\nprint(f'\\nVerified Answer: {final:.1f}')",
    "solution": "def build_cot_prompt(question,steps):\n    prompt=f'Solve this step by step:\\n\\nQuestion: {question}\\n\\n'\n    for i,step in enumerate(steps,start=1):prompt+=f'Step {i}: {step}\\n'\n    prompt+='\\nAnswer:'\n    return prompt\nsteps=['Homework average = (85 + 90 + 78) / 3 = {:.1f}'.format((85+90+78)/3),'Exam average = (92 + 88) / 2 = {:.1f}'.format((92+88)/2),'Final = Homework * 0.4 + Exam * 0.6','Final = {:.1f} * 0.4 + {:.1f} * 0.6 = {:.1f}'.format((85+90+78)/3,(92+88)/2,(85+90+78)/3*0.4+(92+88)/2*0.6)]\nprompt=build_cot_prompt('Calculate the final grade. Homework is 40% and Exams are 60%.',steps)\nprint(prompt)\nhw=(85+90+78)/3\nexam=(92+88)/2\nfinal=hw*0.4+exam*0.6\nprint(f'\\nVerified Answer: {final:.1f}')",
    "hint": "enumerate(steps, start=1) for numbering. Divide by 3 for homework, 2 for exams. 0.6 weight for exams.",
    "rubric": "CoT prompt with numbered steps. Math computed correctly. Weights applied. Answer verified."
  }
],

# ─── MORE PYTHON CORE: INTERMEDIATE ───
"Modules & Packages": [
  {
    "title": "Creating Your Own Module",
    "theory": "## Modules\n```python\n# math_utils.py\ndef add(a, b): return a + b\ndef multiply(a, b): return a * b\nPI = 3.14159\n\n# main.py\nimport math_utils\nmath_utils.add(2, 3)\n\nfrom math_utils import add, PI\nadd(2, 3)\n\nfrom math_utils import *  # Import all (not recommended)\n```",
    "instructions": "## Task: Academy Utils Module\n1. Simulate creating a module with utility functions\n2. Include: calculate_grade, calculate_gpa, format_student\n3. Use the functions as if imported\n4. Print results for multiple students",
    "starterCode": "# Simulating academy_utils module\ndef calculate_grade(score):\n    if score >= 90: return 'A'\n    if score >= 80: return '___'\n    if score >= 70: return 'C'\n    if score >= 60: return 'D'\n    return '___'\n\ndef calculate_gpa(grades):\n    grade_points = {'A': 4.0, 'B': 3.0, 'C': 2.0, 'D': 1.0, 'F': 0.0}\n    total = sum(grade_points.get(g, 0) for g in ___)\n    return round(total / len(grades), 2)\n\ndef format_student(name, scores):\n    grades = [calculate_grade(s) for s in ___]\n    gpa = calculate_gpa(___)\n    return f'{name:15} Grades: {grades}  GPA: {gpa}'\n\n# Using the module\nstudents = {\n    'Ada': [92, 88, 95],\n    'Tunde': [75, 82, 68],\n    'Ngozi': [90, 85, 92],\n}\n\nfor name, scores in students.items():\n    print(format_student(name, scores))",
    "solution": "def calculate_grade(score):\n    if score>=90:return 'A'\n    if score>=80:return 'B'\n    if score>=70:return 'C'\n    if score>=60:return 'D'\n    return 'F'\ndef calculate_gpa(grades):\n    grade_points={'A':4.0,'B':3.0,'C':2.0,'D':1.0,'F':0.0}\n    total=sum(grade_points.get(g,0) for g in grades)\n    return round(total/len(grades),2)\ndef format_student(name,scores):\n    grades=[calculate_grade(s) for s in scores]\n    gpa=calculate_gpa(grades)\n    return f'{name:15} Grades: {grades}  GPA: {gpa}'\nstudents={'Ada':[92,88,95],'Tunde':[75,82,68],'Ngozi':[90,85,92]}\nfor name,scores in students.items():print(format_student(name,scores))",
    "hint": "B for 80+, F for below 60. grades is a list of letters. scores is a list of numbers.",
    "rubric": "Grade thresholds correct. GPA calculation with dict lookup. format_student combines both. All students printed."
  },
  {
    "title": "Working with Standard Library",
    "theory": "## Useful Standard Library Modules\n```python\nimport os          # File/directory operations\nimport json        # JSON parsing\nimport datetime    # Date/time\nimport random      # Random numbers\nimport collections # Counter, defaultdict, etc.\nimport itertools   # Combinations, permutations\nimport functools   # reduce, lru_cache\nimport re          # Regular expressions\n```",
    "instructions": "## Task: Multi-Module Demo\n1. Use `collections.Counter` to count word frequency\n2. Use `random` to generate quiz questions\n3. Use `json` to serialize/deserialize data\n4. Use `datetime` to timestamp everything",
    "starterCode": "from collections import Counter\nimport random\nimport json\nfrom datetime import datetime\n\n# 1. Word frequency\ntext = 'python is great and python is fun and python is powerful'\nword_counts = Counter(text.___())\nprint('Top words:', word_counts.most_common(___))\n\n# 2. Random quiz\nquestions = ['What is a list?', 'What is a dict?', 'What is a loop?', 'What is OOP?']\nquiz = random.sample(questions, ___)\nprint(f'\\nRandom quiz: {quiz}')\n\n# 3. JSON\nstudent = {'name': 'Ada', 'scores': [92, 88, 95], 'active': True}\njson_str = json.___(student, indent=2)\nprint(f'\\nJSON:\\n{json_str}')\nparsed = json.___(json_str)\nprint(f'Parsed name: {parsed[\"name\"]}')\n\n# 4. Timestamp\nnow = datetime.now()\nprint(f'\\nTimestamp: {now.strftime(\"%Y-%m-%d %H:%M:%S\")}')",
    "solution": "from collections import Counter\nimport random\nimport json\nfrom datetime import datetime\ntext='python is great and python is fun and python is powerful'\nword_counts=Counter(text.split())\nprint('Top words:',word_counts.most_common(3))\nquestions=['What is a list?','What is a dict?','What is a loop?','What is OOP?']\nquiz=random.sample(questions,2)\nprint(f'\\nRandom quiz: {quiz}')\nstudent={'name':'Ada','scores':[92,88,95],'active':True}\njson_str=json.dumps(student,indent=2)\nprint(f'\\nJSON:\\n{json_str}')\nparsed=json.loads(json_str)\nprint(f'Parsed name: {parsed[\"name\"]}')\nnow=datetime.now()\nprint(f'\\nTimestamp: {now.strftime(\"%Y-%m-%d %H:%M:%S\")}')",
    "hint": "Counter(text.split()). most_common(3). random.sample(list, k). json.dumps() and json.loads().",
    "rubric": "Counter used. most_common(). random.sample(). JSON dumps/loads. datetime formatted."
  },
  {
    "title": "Virtual Environments & pip",
    "theory": "## Virtual Environments\n```python\n# Create\n# python -m venv myenv\n\n# Activate\n# Windows: myenv\\\\Scripts\\\\activate\n# Mac/Linux: source myenv/bin/activate\n\n# Install packages\n# pip install fastapi sqlalchemy\n\n# Save dependencies\n# pip freeze > requirements.txt\n\n# Install from requirements\n# pip install -r requirements.txt\n\n# requirements.txt example:\n# fastapi==0.104.1\n# sqlalchemy==2.0.23\n# uvicorn==0.24.0\n```",
    "instructions": "## Task: Dependency Manager\n1. Build a simple package dependency resolver\n2. Support install, uninstall, list, freeze commands\n3. Track installed packages with versions\n4. Generate a requirements.txt format output",
    "starterCode": "class PackageManager:\n    def __init__(self):\n        self.installed = {}\n    \n    def install(self, package, version='latest'):\n        self.installed[___] = version\n        return f'Installed {package}=={version}'\n    \n    def uninstall(self, package):\n        if package in self.installed:\n            del self.installed[___]\n            return f'Uninstalled {package}'\n        return f'{package} not found'\n    \n    def list_packages(self):\n        for pkg, ver in sorted(self.installed.___):\n            print(f'  {pkg}=={ver}')\n    \n    def freeze(self):\n        lines = [f'{pkg}=={ver}' for pkg, ver in sorted(self.installed.items())]\n        return '\\n'.join(___)\n\npm = PackageManager()\nprint(pm.install('fastapi', '0.104.1'))\nprint(pm.install('sqlalchemy', '2.0.23'))\nprint(pm.install('uvicorn', '0.24.0'))\nprint(pm.install('pydantic', '2.5.0'))\n\nprint('\\n=== Installed ===')\npm.list_packages()\n\nprint(pm.uninstall('pydantic'))\n\nprint('\\n=== requirements.txt ===')\nprint(pm.freeze())",
    "solution": "class PackageManager:\n    def __init__(self):self.installed={}\n    def install(self,package,version='latest'):self.installed[package]=version;return f'Installed {package}=={version}'\n    def uninstall(self,package):\n        if package in self.installed:del self.installed[package];return f'Uninstalled {package}'\n        return f'{package} not found'\n    def list_packages(self):\n        for pkg,ver in sorted(self.installed.items()):print(f'  {pkg}=={ver}')\n    def freeze(self):\n        lines=[f'{pkg}=={ver}' for pkg,ver in sorted(self.installed.items())]\n        return'\\n'.join(lines)\npm=PackageManager()\nprint(pm.install('fastapi','0.104.1'))\nprint(pm.install('sqlalchemy','2.0.23'))\nprint(pm.install('uvicorn','0.24.0'))\nprint(pm.install('pydantic','2.5.0'))\nprint('\\n=== Installed ===')\npm.list_packages()\nprint(pm.uninstall('pydantic'))\nprint('\\n=== requirements.txt ===')\nprint(pm.freeze())",
    "hint": "self.installed[package] = version. del self.installed[package]. sorted(dict.items()). '\\n'.join(lines).",
    "rubric": "Install adds to dict. Uninstall removes. list_packages sorted. freeze generates requirements format."
  }
],

"List Comprehensions": [
  {
    "title": "Nested Comprehensions",
    "theory": "## Nested List Comprehensions\n```python\n# Flatten a 2D list\nmatrix = [[1,2,3], [4,5,6], [7,8,9]]\nflat = [num for row in matrix for num in row]\n# [1, 2, 3, 4, 5, 6, 7, 8, 9]\n\n# Create a 2D grid\ngrid = [[i*j for j in range(1,4)] for i in range(1,4)]\n# [[1,2,3], [2,4,6], [3,6,9]]\n\n# Conditional nested\neven_from_matrix = [n for row in matrix for n in row if n % 2 == 0]\n# [2, 4, 6, 8]\n```",
    "instructions": "## Task: Matrix Operations\n1. Create a 5x5 multiplication table using nested comprehension\n2. Flatten it to a single list\n3. Filter only values greater than 10\n4. Create a dict mapping value to its position",
    "starterCode": "# 5x5 multiplication table\ntable = [[r * c for c in range(1, ___)] for r in range(1, ___)]\n\nprint('Multiplication Table:')\nfor row in table:\n    print([f'{n:3}' for n in row])\n\n# Flatten\nflat = [n for row in ___ for n in ___]\nprint(f'\\nFlattened: {flat}')\n\n# Filter > 10\nbig = [n for n in flat if n > ___]\nprint(f'Values > 10: {sorted(set(big))}')\n\n# Position map\npositions = {\n    table[r][c]: (r+1, c+1)\n    for r in range(___)\n    for c in range(5)\n}\nprint(f'\\nPosition of 12: row {positions[12][0]}, col {positions[12][1]}')",
    "solution": "table=[[r*c for c in range(1,6)] for r in range(1,6)]\nprint('Multiplication Table:')\nfor row in table:print([f'{n:3}' for n in row])\nflat=[n for row in table for n in row]\nprint(f'\\nFlattened: {flat}')\nbig=[n for n in flat if n>10]\nprint(f'Values > 10: {sorted(set(big))}')\npositions={table[r][c]:(r+1,c+1) for r in range(5) for c in range(5)}\nprint(f'\\nPosition of 12: row {positions[12][0]}, col {positions[12][1]}')",
    "hint": "range(1, 6) for 1-5. Nested for in comprehension flattens. Dict comprehension for positions.",
    "rubric": "5x5 table created. Flattened correctly. Filtered > 10. Position dict maps values."
  },
  {
    "title": "Generator Expressions vs List Comps",
    "theory": "## Generators vs Lists\n```python\n# List comprehension — creates full list in memory\nnums_list = [x**2 for x in range(1000000)]  # Uses lots of RAM!\n\n# Generator expression — lazy, one at a time\nnums_gen = (x**2 for x in range(1000000))   # Almost no RAM!\n\n# Use generators with:\nsum(x**2 for x in range(100))     # Sum\nmax(x**2 for x in range(100))     # Max\nany(x > 50 for x in scores)       # Any match?\nall(x > 0 for x in scores)        # All match?\n```",
    "instructions": "## Task: Memory Efficient Processing\n1. Create a large dataset of 100,000 numbers\n2. Compare list comp vs generator for sum, any, all\n3. Use generators with sum(), any(), all(), max()\n4. Print results and explain when to use each",
    "starterCode": "import sys\n\n# Compare memory\nlist_comp = [x**2 for x in range(10000)]\ngen_expr = (x**2 for x in range(10000))\n\nprint(f'List size: {sys.getsizeof(list_comp):,} bytes')\nprint(f'Generator size: {sys.getsizeof(gen_expr):,} bytes')\n\n# Efficient aggregations with generators\nscores = [72, 85, 90, 68, 95, 82, 77, 91, 88, 73, 45, 98]\n\ntotal = sum(s for s in scores)\naverage = total / ___(scores)\npassing = sum(1 for s in scores if s >= ___)\nall_pass = all(s >= ___ for s in scores)\nany_perfect = any(s == ___ for s in scores)\nhighest = max(s for s in ___)\n\nprint(f'\\nTotal: {total}')\nprint(f'Average: {average:.1f}')\nprint(f'Passing (>=70): {passing}/{len(scores)}')\nprint(f'All passing: {all_pass}')\nprint(f'Any perfect (100): {any_perfect}')\nprint(f'Highest: {highest}')",
    "solution": "import sys\nlist_comp=[x**2 for x in range(10000)]\ngen_expr=(x**2 for x in range(10000))\nprint(f'List size: {sys.getsizeof(list_comp):,} bytes')\nprint(f'Generator size: {sys.getsizeof(gen_expr):,} bytes')\nscores=[72,85,90,68,95,82,77,91,88,73,45,98]\ntotal=sum(s for s in scores)\naverage=total/len(scores)\npassing=sum(1 for s in scores if s>=70)\nall_pass=all(s>=70 for s in scores)\nany_perfect=any(s==100 for s in scores)\nhighest=max(s for s in scores)\nprint(f'\\nTotal: {total}')\nprint(f'Average: {average:.1f}')\nprint(f'Passing (>=70): {passing}/{len(scores)}')\nprint(f'All passing: {all_pass}')\nprint(f'Any perfect (100): {any_perfect}')\nprint(f'Highest: {highest}')",
    "hint": "len(scores) for count. >= 70 for passing. == 100 for perfect. Generator uses () not [].",
    "rubric": "Memory comparison shown. sum() with generator. all() and any() used. Correct thresholds."
  },
  {
    "title": "Set & Dict Comprehensions",
    "theory": "## Set & Dict Comprehensions\n```python\n# Set comprehension (unique values)\nunique_lengths = {len(word) for word in ['hello', 'world', 'hi']}\n# {2, 5}\n\n# Dict comprehension\nsquares = {x: x**2 for x in range(5)}\n# {0: 0, 1: 1, 2: 4, 3: 9, 4: 16}\n\n# Filtering\npassing = {name: score for name, score in grades.items() if score >= 70}\n```",
    "instructions": "## Task: Data Transformation Pipeline\n1. Given raw student data, use set comp to find unique courses\n2. Use dict comp to create a grade lookup\n3. Use dict comp to group students by course\n4. Chain comprehensions for a final report",
    "starterCode": "students = [\n    {'name': 'Ada', 'course': 'Python', 'score': 92},\n    {'name': 'Tunde', 'course': 'SQL', 'score': 78},\n    {'name': 'Ngozi', 'course': 'Python', 'score': 85},\n    {'name': 'Kemi', 'course': 'AI', 'score': 95},\n    {'name': 'Bayo', 'course': 'SQL', 'score': 70},\n]\n\n# Unique courses (set comprehension)\nunique_courses = {s['___'] for s in students}\nprint(f'Courses: {unique_courses}')\n\n# Grade lookup (dict comprehension)\ngrades = {s['name']: 'A' if s['score']>=90 else 'B' if s['score']>=80 else 'C'\n          for s in ___}\nprint(f'Grades: {grades}')\n\n# Top scorers only (filtered dict comp)\nhonors = {s['name']: s['score'] for s in students if s['score'] >= ___}\nprint(f'Honors (90+): {honors}')\n\n# Count per course\nfrom collections import Counter\ncourse_counts = Counter(s['___'] for s in students)\nprint(f'Per course: {dict(course_counts)}')",
    "solution": "students=[{'name':'Ada','course':'Python','score':92},{'name':'Tunde','course':'SQL','score':78},{'name':'Ngozi','course':'Python','score':85},{'name':'Kemi','course':'AI','score':95},{'name':'Bayo','course':'SQL','score':70}]\nunique_courses={s['course'] for s in students}\nprint(f'Courses: {unique_courses}')\ngrades={s['name']:'A' if s['score']>=90 else 'B' if s['score']>=80 else 'C' for s in students}\nprint(f'Grades: {grades}')\nhonors={s['name']:s['score'] for s in students if s['score']>=90}\nprint(f'Honors (90+): {honors}')\nfrom collections import Counter\ncourse_counts=Counter(s['course'] for s in students)\nprint(f'Per course: {dict(course_counts)}')",
    "hint": "s['course'] for set comp. students for dict comp source. >= 90 for honors. Counter for counting.",
    "rubric": "Set comprehension for unique. Dict comp with ternary grades. Filtered dict comp. Counter used."
  }
],

}

# ══════════════════════════════════════════════════════
# INJECTION ENGINE (same as batch 1)
# ══════════════════════════════════════════════════════
def inject_lessons(filepath, new_lessons):
    with open(filepath, 'r', encoding='utf-8') as f:
        content = f.read()
    injected = 0
    for course_name, lessons in new_lessons.items():
        course_pos = content.find(f'"{course_name}"')
        if course_pos == -1:
            print(f'  SKIP: "{course_name}" not found')
            continue
        lessons_key = content.find('"lessons"', course_pos)
        if lessons_key == -1:
            continue
        bracket_start = content.find('[', lessons_key)
        depth = 0
        bracket_end = -1
        for i in range(bracket_start, min(bracket_start + 100000, len(content))):
            if content[i] == '[': depth += 1
            elif content[i] == ']':
                depth -= 1
                if depth == 0:
                    bracket_end = i
                    break
        if bracket_end == -1:
            continue
        new_entries = ''
        for lesson in lessons:
            new_entries += ',\n      ' + json.dumps(lesson, ensure_ascii=False)
        content = content[:bracket_end] + new_entries + '\n    ' + content[bracket_end:]
        injected += len(lessons)
        print(f'  OK: +{len(lessons)} lessons to "{course_name}"')
    with open(filepath, 'w', encoding='utf-8') as f:
        f.write(content)
    print(f'\n=== Batch 2 TOTAL: {injected} new lessons ===')

if __name__ == '__main__':
    inject_lessons('frontend/src/data/courses.js', NEW_LESSONS)
