"""
Batch 10: Backend Design, AI Image Processing, Web Accessibility
"""
import json, os

LESSONS_BATCH10 = {
    # ─── BACKEND ───
    "RESTful Design": [
        {"title": "REST Principles", "theory": "## Representational State Transfer\nREST is an architectural style for designing networked applications.\n\nKey Principles:\n- **Client-Server**: Separation of concerns.\n- **Stateless**: Each request contains all information needed to process it (no server sessions).\n- **Cacheable**: Responses should specify if they can be cached.\n- **Uniform Interface**: Consistent ways to access resources (URIs).\n\nResources are nouns (e.g., `/users`), actions are HTTP verbs (e.g., `GET`, `POST`).", "instructions": "## Task: RESTful Routing Matcher\n1. Match the action to the correct RESTful HTTP Verb + Route combination.\n2. Actions: 'Get all users', 'Create a user', 'Get specific user', 'Delete a user'\n3. Match them to: `GET /users`, `POST /users`, `GET /users/:id`, `DELETE /users/:id`", "starterCode": "routes = {\n    'Get all users': '___',\n    'Create a user': '___',\n    'Get specific user': '___',\n    'Delete a user': '___'\n}\n\nfor action, route in routes.items():\n    print(f\"{action:20} -> {route}\")", "solution": "routes = {\n    'Get all users': 'GET /users',\n    'Create a user': 'POST /users',\n    'Get specific user': 'GET /users/:id',\n    'Delete a user': 'DELETE /users/:id'\n}\n\nfor action, route in routes.items():\n    print(f\"{action:20} -> {route}\")", "hint": "GET to fetch, POST to create, DELETE to remove. Use /users/:id for specific items.", "rubric": "All 4 routes correctly matched to RESTful verbs and URIs."},
        {"title": "HTTP Status Codes", "theory": "## Server Responses\nWhen a server responds to a request, it includes a status code to indicate what happened.\n\n- **2xx Success**: 200 OK, 201 Created, 204 No Content\n- **3xx Redirection**: 301 Moved Permanently\n- **4xx Client Error**: 400 Bad Request, 401 Unauthorized, 403 Forbidden, 404 Not Found\n- **5xx Server Error**: 500 Internal Server Error, 502 Bad Gateway", "instructions": "## Task: Status Code Handler\n1. Write a function that returns a human-readable message based on the HTTP status code.\n2. Handle 200, 401, 404, and 500.", "starterCode": "def handle_status(code):\n    if code == ___:\n        return \"Success! Data fetched.\"\n    elif code == ___:\n        return \"Unauthorized! Please log in.\"\n    elif code == ___:\n        return \"Not Found! Resource does not exist.\"\n    elif code == ___:\n        return \"Server Error! Our engineers are on it.\"\n    return \"Unknown status code\"\n\ncodes = [200, 401, 404, 500]\nfor c in codes:\n    print(f\"{c}: {handle_status(c)}\")", "solution": "def handle_status(code):\n    if code == 200:\n        return \"Success! Data fetched.\"\n    elif code == 401:\n        return \"Unauthorized! Please log in.\"\n    elif code == 404:\n        return \"Not Found! Resource does not exist.\"\n    elif code == 500:\n        return \"Server Error! Our engineers are on it.\"\n    return \"Unknown status code\"\n\ncodes = [200, 401, 404, 500]\nfor c in codes:\n    print(f\"{c}: {handle_status(c)}\")", "hint": "Match the codes to the messages (200, 401, 404, 500).", "rubric": "Function correctly identifies all 4 status codes."}
    ],
    "Microservices": [
        {"title": "Monolith vs Microservices", "theory": "## Breaking Up the App\n- **Monolith**: All code (auth, payments, catalog) is in one giant repository and runs as a single process. Hard to scale specific parts.\n- **Microservices**: Small, independent services that communicate via APIs. You can scale the Payment service independently of the Catalog service.\n\nMicroservices introduce complexity: network latency, distributed data, and harder debugging.", "instructions": "## Task: Architecture Comparison\n1. Create a dictionary that categorizes traits to either 'Monolith' or 'Microservices'.\n2. Traits: 'Single Codebase', 'Independent Deployments', 'Complex Networking', 'Easier to Debug initially'", "starterCode": "traits = {\n    'Single Codebase': '___',\n    'Independent Deployments': '___',\n    'Complex Networking': '___',\n    'Easier to Debug initially': '___'\n}\n\nfor trait, arch in traits.items():\n    print(f\"{trait:30} -> {arch}\")", "solution": "traits = {\n    'Single Codebase': 'Monolith',\n    'Independent Deployments': 'Microservices',\n    'Complex Networking': 'Microservices',\n    'Easier to Debug initially': 'Monolith'\n}\n\nfor trait, arch in traits.items():\n    print(f\"{trait:30} -> {arch}\")", "hint": "Monolith = single, easy to debug early on. Microservices = independent, complex network.", "rubric": "Traits correctly mapped to Monolith or Microservices."}
    ],
    # ─── FRONTEND ───
    "Web Accessibility": [
        {"title": "Semantic HTML", "theory": "## Designing for Everyone\nAccessibility (a11y) ensures users with disabilities can use your app. Screen readers rely heavily on **Semantic HTML**.\n\n- Instead of `<div class=\"header\">`, use `<header>`\n- Instead of `<span class=\"button\">`, use `<button>`\n- Use `<nav>`, `<main>`, `<article>`, `<footer>`\n\nThis provides structural meaning to the browser and assistive technologies.", "instructions": "## Task: Semantic Refactor\n1. You are given a string of bad HTML using only `div` tags.\n2. Create a mapped version that replaces the generic tags with semantic ones: `header`, `nav`, `main`, `footer`.", "starterCode": "bad_html = {\n    'div_header': '___',\n    'div_nav': '___',\n    'div_content': '___',\n    'div_footer': '___'\n}\n\nfor bad, good in bad_html.items():\n    print(f\"Replace <{bad}> with semantic <{good}>\")", "solution": "bad_html = {\n    'div_header': 'header',\n    'div_nav': 'nav',\n    'div_content': 'main',\n    'div_footer': 'footer'\n}\n\nfor bad, good in bad_html.items():\n    print(f\"Replace <{bad}> with semantic <{good}>\")", "hint": "Match the class name to the semantic HTML5 tag.", "rubric": "All 4 generic divs matched to their proper HTML5 semantic tags."},
        {"title": "ARIA Attributes", "theory": "## Accessible Rich Internet Applications\nWhen HTML5 tags aren't enough (e.g., for custom complex widgets), ARIA attributes provide extra context.\n\n- `aria-hidden=\"true\"`: Hides an element from screen readers (e.g., a decorative icon)\n- `aria-label`: Provides a label when there is no visible text (e.g., an icon-only button)\n- `aria-expanded`: Tells if a dropdown is open or closed", "instructions": "## Task: Apply ARIA\n1. Match the use case to the correct ARIA attribute.\n2. Attributes: 'aria-hidden', 'aria-label', 'aria-expanded'", "starterCode": "aria_usage = {\n    'Decorative SVG icon': '___',\n    'Button with only a magnifying glass icon': '___',\n    'Accordion menu that is currently open': '___'\n}\n\nfor usage, attr in aria_usage.items():\n    print(f\"{usage:42} -> {attr}\")", "solution": "aria_usage = {\n    'Decorative SVG icon': 'aria-hidden',\n    'Button with only a magnifying glass icon': 'aria-label',\n    'Accordion menu that is currently open': 'aria-expanded'\n}\n\nfor usage, attr in aria_usage.items():\n    print(f\"{usage:42} -> {attr}\")", "hint": "Hidden for decorative. Label for icon-only. Expanded for open/closed menus.", "rubric": "Use cases correctly matched with their ARIA attributes."}
    ],
    # ─── AI ENGINEERING ───
    "Image Processing": [
        {"title": "Pixels and Channels", "theory": "## How Computers See Images\nAn image is just a massive grid (matrix) of numbers.\n\n- **Grayscale**: 2D grid. Values from 0 (black) to 255 (white).\n- **Color (RGB)**: 3D grid. It has 3 color \"channels\": Red, Green, and Blue.\n\nA 1080p image is `1920 x 1080 x 3` values.", "instructions": "## Task: Image Matrix\n1. Create a simulated 2x2 grayscale image (a 2D list/array).\n2. Set the top-left to 0 (black) and bottom-right to 255 (white).\n3. Set the others to 128 (gray).", "starterCode": "image_matrix = [\n    [___, ___],  # Top row (Black, Gray)\n    [___, ___]   # Bottom row (Gray, White)\n]\n\nprint(\"2x2 Grayscale Image Matrix:\")\nfor row in image_matrix:\n    print(row)", "solution": "image_matrix = [\n    [0, 128],  # Top row (Black, Gray)\n    [128, 255]   # Bottom row (Gray, White)\n]\n\nprint(\"2x2 Grayscale Image Matrix:\")\nfor row in image_matrix:\n    print(row)", "hint": "Black is 0, Gray is 128, White is 255.", "rubric": "Matrix correctly constructed with [0, 128] and [128, 255]."}
    ],
    "OpenCV Basics": [
        {"title": "OpenCV Intro", "theory": "## The Computer Vision Library\nOpenCV (`cv2` in Python) is the standard library for image processing.\n\n```python\nimport cv2\n\n# Read an image\nimg = cv2.imread('dog.jpg')\n\n# Convert to grayscale\ngray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)\n\n# Show image\ncv2.imshow('Gray Dog', gray)\n```\nNote: OpenCV uses BGR (Blue, Green, Red) format, not RGB!", "instructions": "## Task: OpenCV Command Matcher\n1. Match the OpenCV function to its description.\n2. Functions: `imread`, `cvtColor`, `imwrite`, `imshow`", "starterCode": "cv2_funcs = {\n    'Load image from disk': 'cv2.___',\n    'Change color space': 'cv2.___',\n    'Save image to disk': 'cv2.___',\n    'Display image in a window': 'cv2.___'\n}\n\nfor desc, func in cv2_funcs.items():\n    print(f\"{desc:30} -> {func}\")", "solution": "cv2_funcs = {\n    'Load image from disk': 'cv2.imread',\n    'Change color space': 'cv2.cvtColor',\n    'Save image to disk': 'cv2.imwrite',\n    'Display image in a window': 'cv2.imshow'\n}\n\nfor desc, func in cv2_funcs.items():\n    print(f\"{desc:30} -> {func}\")", "hint": "imread (read), cvtColor (convert color), imwrite (write), imshow (show).", "rubric": "All 4 functions matched accurately to their descriptions."}
    ],
    # ─── SQL & DATABASES ───
    "Database Design": [
        {"title": "Entity-Relationship (ER)", "theory": "## Modeling Data\nBefore writing SQL, you design the database using an ER diagram.\n\n- **Entities**: Nouns (Users, Products, Orders)\n- **Attributes**: Properties of entities (User: Name, Email)\n- **Relationships**: How entities connect\n  - 1-to-1: User has 1 Profile\n  - 1-to-Many: User has Many Orders\n  - Many-to-Many: Students have Many Classes, Classes have Many Students", "instructions": "## Task: Relationship Types\n1. Match the scenario to the correct relationship type.\n2. Types: '1-to-1', '1-to-Many', 'Many-to-Many'", "starterCode": "relationships = {\n    'A Customer can place multiple Orders': '___',\n    'A Person has one Passport': '___',\n    'Authors write multiple Books; Books can have multiple Authors': '___'\n}\n\nfor scenario, rel_type in relationships.items():\n    print(f\"{scenario:65}\\n-> {rel_type}\\n\")", "solution": "relationships = {\n    'A Customer can place multiple Orders': '1-to-Many',\n    'A Person has one Passport': '1-to-1',\n    'Authors write multiple Books; Books can have multiple Authors': 'Many-to-Many'\n}\n\nfor scenario, rel_type in relationships.items():\n    print(f\"{scenario:65}\\n-> {rel_type}\\n\")", "hint": "Customer->Orders is 1-to-Many. Authors<->Books is Many-to-Many.", "rubric": "Scenarios accurately mapped to their relationship types."}
    ]
}

def apply_lessons(tracks_dir):
    from rebuild_curriculum import track_courses
    total = 0
    for track_name, levels in track_courses.items():
        safe_name = track_name.lower().replace(" ", "_").replace("&", "").replace("__", "_") + ".json"
        filepath = os.path.join(tracks_dir, safe_name)
        if not os.path.exists(filepath): continue
        with open(filepath, 'r', encoding='utf-8') as f:
            track_data = json.load(f)
        updated = False
        for course_name in track_data:
            if course_name in LESSONS_BATCH10:
                track_data[course_name]['lessons'] = LESSONS_BATCH10[course_name]
                updated = True
                total += len(LESSONS_BATCH10[course_name])
        if updated:
            with open(filepath, 'w', encoding='utf-8') as f:
                json.dump(track_data, f, indent=2, ensure_ascii=False)
    print(f'Batch 10: Applied {total} lessons')
    os.system('python build_courses.py')

if __name__ == '__main__':
    apply_lessons(os.path.join('curriculum', 'tracks'))
