"""
Batch 14: Advanced Rust, System Design Case Studies
"""
import json, os

LESSONS_BATCH14 = {
    # ─── SYSTEM DESIGN & ARCHITECTURE ───
    "Designing Uber": [
        {"title": "Real-time Location", "theory": "## Tracking Cars\nUber needs to track millions of cars in real-time. How do they do it?\n\n- They use a **Geospatial Database** (like Redis Geo or PostgreSQL with PostGIS).\n- The world is divided into grids (e.g., using Google S2 or Uber H3 libraries).\n- Cars constantly send their location via WebSockets.\n- When a rider requests a car, the system searches the grid for the nearest cars.", "instructions": "## Task: Grid Assignment Simulator\n1. Imagine a city is a 100x100 grid.\n2. Write a function that takes an X, Y coordinate and assigns it to a 10x10 \"Sector\".\n3. E.g., Coordinate (15, 22) belongs to Sector X:1, Y:2.", "starterCode": "def assign_sector(x, y):\n    # Divide by 10 and round down (integer division)\n    sector_x = x ___ 10\n    sector_y = y ___ 10\n    return f\"Sector-{sector_x}-{sector_y}\"\n\ncars = [\n    {'id': 'CarA', 'x': 15, 'y': 22},\n    {'id': 'CarB', 'x': 89, 'y': 95},\n    {'id': 'CarC', 'x': 12, 'y': 28}\n]\n\nfor car in cars:\n    sector = assign_sector(car['x'], car['y'])\n    print(f\"{car['id']} is in {sector}\")", "solution": "def assign_sector(x, y):\n    # Divide by 10 and round down (integer division)\n    sector_x = x // 10\n    sector_y = y // 10\n    return f\"Sector-{sector_x}-{sector_y}\"\n\ncars = [\n    {'id': 'CarA', 'x': 15, 'y': 22},\n    {'id': 'CarB', 'x': 89, 'y': 95},\n    {'id': 'CarC', 'x': 12, 'y': 28}\n]\n\nfor car in cars:\n    sector = assign_sector(car['x'], car['y'])\n    print(f\"{car['id']} is in {sector}\")", "hint": "Use // for integer division in Python.", "rubric": "Cars are mapped to Sector-1-2, Sector-8-9, and Sector-1-2."},
        {"title": "Matching Algorithm", "theory": "## Finding the Best Driver\nThe closest driver isn't always the best one. The matching algorithm considers:\n\n- **ETA**: Time to reach the rider (factoring in traffic).\n- **Direction**: Is the driver already heading that way?\n- **Driver Ratings**: Maintaining quality.\n\nThis requires heavy computational power, often using machine learning models.", "instructions": "## Task: Simple Matcher\n1. You have a rider at (10, 10).\n2. Calculate the 'Manhattan Distance' to 3 drivers.\n3. Return the ID of the closest driver.", "starterCode": "def get_distance(x1, y1, x2, y2):\n    # Manhattan distance: |x1 - x2| + |y1 - y2|\n    return abs(x1 - x2) + abs(___ - ___)\n\nrider = (10, 10)\ndrivers = {\n    'DriverX': (15, 12),\n    'DriverY': (8, 9),\n    'DriverZ': (20, 20)\n}\n\nbest_driver = None\nmin_dist = float('inf')\n\nfor d_id, coords in drivers.items():\n    dist = get_distance(rider[0], rider[1], coords[0], coords[1])\n    print(f\"{d_id} is {dist} units away\")\n    if dist < ___:\n        ___ = dist\n        ___ = d_id\n\nprint(f\"\\nDispatching: {best_driver}\")", "solution": "def get_distance(x1, y1, x2, y2):\n    # Manhattan distance: |x1 - x2| + |y1 - y2|\n    return abs(x1 - x2) + abs(y1 - y2)\n\nrider = (10, 10)\ndrivers = {\n    'DriverX': (15, 12),\n    'DriverY': (8, 9),\n    'DriverZ': (20, 20)\n}\n\nbest_driver = None\nmin_dist = float('inf')\n\nfor d_id, coords in drivers.items():\n    dist = get_distance(rider[0], rider[1], coords[0], coords[1])\n    print(f\"{d_id} is {dist} units away\")\n    if dist < min_dist:\n        min_dist = dist\n        best_driver = d_id\n\nprint(f\"\\nDispatching: {best_driver}\")", "hint": "abs(y1 - y2). Check if dist < min_dist. Set min_dist and best_driver.", "rubric": "DriverY is chosen because they are 3 units away."}
    ],
    "Designing Netflix": [
        {"title": "Video Streaming", "theory": "## CDNs and Video Encoding\nHow does Netflix stream video to 200 million people without crashing?\n\n1. **Encoding**: They compress original videos into dozens of different resolutions and bitrates.\n2. **CDN (Content Delivery Network)**: Netflix built 'Open Connect'. They put custom servers *inside* your local ISP (like Comcast). When you stream a movie, it's often coming from a server just a few miles away, not across the country.\n3. **Adaptive Bitrate Streaming**: The video player constantly checks your internet speed. If it drops, it seamlessly switches to a lower quality chunk of the video.", "instructions": "## Task: Adaptive Bitrate Simulator\n1. Simulate a video player checking bandwidth.\n2. If bandwidth > 10 Mbps, play 4K.\n3. If bandwidth > 5 Mbps, play 1080p.\n4. Else, play 720p.", "starterCode": "def select_quality(bandwidth_mbps):\n    if bandwidth_mbps > ___:\n        return \"4K\"\n    elif bandwidth_mbps > ___:\n        return \"1080p\"\n    else:\n        return \"___\"\n\nnetwork_fluctuations = [15.2, 11.0, 6.5, 2.1, 8.0, 25.0]\n\nfor i, speed in enumerate(network_fluctuations):\n    quality = select_quality(speed)\n    print(f\"Minute {i+1}: Speed={speed:4.1f} Mbps -> Streaming at {quality}\")", "solution": "def select_quality(bandwidth_mbps):\n    if bandwidth_mbps > 10:\n        return \"4K\"\n    elif bandwidth_mbps > 5:\n        return \"1080p\"\n    else:\n        return \"720p\"\n\nnetwork_fluctuations = [15.2, 11.0, 6.5, 2.1, 8.0, 25.0]\n\nfor i, speed in enumerate(network_fluctuations):\n    quality = select_quality(speed)\n    print(f\"Minute {i+1}: Speed={speed:4.1f} Mbps -> Streaming at {quality}\")", "hint": "> 10 for 4K. > 5 for 1080p. Else 720p.", "rubric": "Resolutions dynamically adapt based on the simulated network speed."}
    ],
    # ─── SYSTEMS PROGRAMMING (RUST) ───
    "Memory Safety": [
        {"title": "Lifetimes", "theory": "## Keeping References Valid\nRust must guarantee that all references are valid (no dangling pointers).\n\nWhen a function takes multiple references, the compiler sometimes needs help knowing how long they live. We use **lifetimes** (annotated with `'a`).\n\n```rust\n// 'a means \"both x and y must live as long as the returned reference\"\nfn longest<'a>(x: &'a str, y: &'a str) -> &'a str {\n    if x.len() > y.len() { x } else { y }\n}\n```", "instructions": "## Task: Add Lifetimes\n1. You have a `get_first` function that takes a reference to a string and returns a reference to its first word.\n2. Since it takes one reference and returns one reference, Rust can usually infer this (Lifetime Elision).\n3. But for this exercise, manually add the explicit `'a` lifetime annotations.", "starterCode": "fn get_first<___>(s: ___ str) -> ___ str {\n    let bytes = s.as_bytes();\n    for (i, &item) in bytes.iter().enumerate() {\n        if item == b' ' {\n            return &s[0..i];\n        }\n    }\n    &s[..]\n}\n\nfn main() {\n    let text = String::from(\"Rust is safe\");\n    let word = get_first(&text);\n    println!(\"First word: {}\", word);\n}", "solution": "fn get_first<'a>(s: &'a str) -> &'a str {\n    let bytes = s.as_bytes();\n    for (i, &item) in bytes.iter().enumerate() {\n        if item == b' ' {\n            return &s[0..i];\n        }\n    }\n    &s[..]\n}\n\nfn main() {\n    let text = String::from(\"Rust is safe\");\n    let word = get_first(&text);\n    println!(\"First word: {}\", word);\n}", "hint": "<'a> in the diamond brackets. &'a str for both types.", "rubric": "Explicit lifetimes applied correctly. Output is 'Rust'."}
    ],
    "Concurrency": [
        {"title": "Threads in Rust", "theory": "## Fearless Concurrency\nRust prevents data races at compile time. \n\n```rust\nuse std::thread;\nuse std::time::Duration;\n\nfn main() {\n    let handle = thread::spawn(|| {\n        println!(\"Hello from a thread!\");\n    });\n    \n    handle.join().unwrap(); // Wait for thread to finish\n}\n```", "instructions": "## Task: Spawn a Thread\n1. Use `thread::spawn` to run a closure.\n2. Inside the thread, print numbers 1 to 3.\n3. Call `join()` on the returned handle so the main thread waits.", "starterCode": "use std::___;\nuse std::time::Duration;\n\nfn main() {\n    let handle = thread::___(|| {\n        for i in 1..=3 {\n            println!(\"Thread: {}\", i);\n            thread::sleep(Duration::from_millis(10));\n        }\n    });\n\n    for i in 1..=3 {\n        println!(\"Main: {}\", i);\n        thread::sleep(Duration::from_millis(10));\n    }\n\n    // Wait for the spawned thread\n    handle.___().unwrap();\n}", "solution": "use std::thread;\nuse std::time::Duration;\n\nfn main() {\n    let handle = thread::spawn(|| {\n        for i in 1..=3 {\n            println!(\"Thread: {}\", i);\n            thread::sleep(Duration::from_millis(10));\n        }\n    });\n\n    for i in 1..=3 {\n        println!(\"Main: {}\", i);\n        thread::sleep(Duration::from_millis(10));\n    }\n\n    // Wait for the spawned thread\n    handle.join().unwrap();\n}", "hint": "std::thread. thread::spawn. handle.join().", "rubric": "Thread spawned correctly and joined at the end."}
    ],
    "Macros": [
        {"title": "Code that writes Code", "theory": "## Metaprogramming\nMacros in Rust (like `println!`, `vec!`) look like functions but end with a `!`. \n\nThey expand into standard Rust code *before* the compiler compiles the program. This allows them to take a variable number of arguments.\n\n```rust\n// Creating a Vector using a macro\nlet v1 = vec![1, 2, 3];\n```", "instructions": "## Task: Use Macros\n1. Use the `vec!` macro to create a vector containing 10, 20, 30.\n2. Use the `format!` macro to combine two strings without printing them.\n3. Use `println!` to print the formatted string.", "starterCode": "fn main() {\n    // Create a vector\n    let numbers = ___![10, 20, 30];\n    \n    // Format a string (like python f-strings, returns a String)\n    let text = ___!(\"The first number is {}\", numbers[0]);\n    \n    // Print it\n    ___!(\"{}\", text);\n}", "solution": "fn main() {\n    // Create a vector\n    let numbers = vec![10, 20, 30];\n    \n    // Format a string (like python f-strings, returns a String)\n    let text = format!(\"The first number is {}\", numbers[0]);\n    \n    // Print it\n    println!(\"{}\", text);\n}", "hint": "vec!, format!, println!", "rubric": "vec, format, and println macros used correctly."}
    ],
    "Unsafe Rust": [
        {"title": "The Unsafe Keyword", "theory": "## Disabling Safety Checks\nSometimes you need to do things the Rust compiler can't verify (like calling C code, or writing a low-level OS driver).\n\nYou can use the `unsafe` block. Inside it, you can:\n- Dereference raw pointers\n- Call unsafe functions\n- Mutate static variables\n\n```rust\nlet mut num = 5;\nlet r1 = &num as *const i32; // Raw pointer\n\nunsafe {\n    println!(\"r1 is: {}\", *r1); // Dereferencing is unsafe\n}\n```", "instructions": "## Task: Dereference a Raw Pointer\n1. You are given a raw pointer to a number.\n2. You must wrap the dereference operation inside an `unsafe` block.\n3. Print the value.", "starterCode": "fn main() {\n    let num = 42;\n    \n    // Create a raw pointer (this is safe)\n    let raw_ptr = &num as *const i32;\n    \n    // Dereferencing it is unsafe!\n    ___ {\n        println!(\"The secret number is: {}\", ___raw_ptr);\n    }\n}", "solution": "fn main() {\n    let num = 42;\n    \n    // Create a raw pointer (this is safe)\n    let raw_ptr = &num as *const i32;\n    \n    // Dereferencing it is unsafe!\n    unsafe {\n        println!(\"The secret number is: {}\", *raw_ptr);\n    }\n}", "hint": "unsafe { }. Use * to dereference.", "rubric": "unsafe block wraps the *raw_ptr dereference."}
    ]
}

def apply_lessons(tracks_dir):
    from rebuild_curriculum import track_courses
    total = 0
    for track_name, levels in track_courses.items():
        safe_name = track_name.lower().replace(" ", "_").replace("&", "").replace("__", "_") + ".json"
        filepath = os.path.join(tracks_dir, safe_name)
        if not os.path.exists(filepath): continue
        with open(filepath, 'r', encoding='utf-8') as f:
            track_data = json.load(f)
        updated = False
        for course_name in track_data:
            if course_name in LESSONS_BATCH14:
                track_data[course_name]['lessons'] = LESSONS_BATCH14[course_name]
                updated = True
                total += len(LESSONS_BATCH14[course_name])
        if updated:
            with open(filepath, 'w', encoding='utf-8') as f:
                json.dump(track_data, f, indent=2, ensure_ascii=False)
    print(f'Batch 14: Applied {total} lessons')
    os.system('python build_courses.py')

if __name__ == '__main__':
    apply_lessons(os.path.join('curriculum', 'tracks'))
