"""
Batch 21: Retry missing courses by iterating all files directly
"""
import json, os

# Include ALL previously missed courses from earlier batches that failed due to filename mismatches.
LESSONS_BATCH21 = {}

# From Batch 10
LESSONS_BATCH21.update({
    "RESTful Design": [
        {"title": "REST Principles", "theory": "## Representational State Transfer\\nREST is an architectural style for designing networked applications.\\n\\nKey Principles:\\n- **Client-Server**: Separation of concerns.\\n- **Stateless**: Each request contains all information needed to process it (no server sessions).\\n- **Cacheable**: Responses should specify if they can be cached.\\n- **Uniform Interface**: Consistent ways to access resources (URIs).\\n\\nResources are nouns (e.g., `/users`), actions are HTTP verbs (e.g., `GET`, `POST`).", "instructions": "## Task: RESTful Routing Matcher\\n1. Match the action to the correct RESTful HTTP Verb + Route combination.\\n2. Actions: 'Get all users', 'Create a user', 'Get specific user', 'Delete a user'\\n3. Match them to: `GET /users`, `POST /users`, `GET /users/:id`, `DELETE /users/:id`", "starterCode": "routes = {\\n    'Get all users': '___',\\n    'Create a user': '___',\\n    'Get specific user': '___',\\n    'Delete a user': '___'\\n}\\n\\nfor action, route in routes.items():\\n    print(f\"{action:20} -> {route}\")", "solution": "routes = {\\n    'Get all users': 'GET /users',\\n    'Create a user': 'POST /users',\\n    'Get specific user': 'GET /users/:id',\\n    'Delete a user': 'DELETE /users/:id'\\n}\\n\\nfor action, route in routes.items():\\n    print(f\"{action:20} -> {route}\")", "hint": "GET to fetch, POST to create, DELETE to remove. Use /users/:id for specific items.", "rubric": "All 4 routes correctly matched to RESTful verbs and URIs."},
        {"title": "HTTP Status Codes", "theory": "## Server Responses\\nWhen a server responds to a request, it includes a status code to indicate what happened.\\n\\n- **2xx Success**: 200 OK, 201 Created, 204 No Content\\n- **3xx Redirection**: 301 Moved Permanently\\n- **4xx Client Error**: 400 Bad Request, 401 Unauthorized, 403 Forbidden, 404 Not Found\\n- **5xx Server Error**: 500 Internal Server Error, 502 Bad Gateway", "instructions": "## Task: Status Code Handler\\n1. Write a function that returns a human-readable message based on the HTTP status code.\\n2. Handle 200, 401, 404, and 500.", "starterCode": "def handle_status(code):\\n    if code == ___:\\n        return \"Success! Data fetched.\"\\n    elif code == ___:\\n        return \"Unauthorized! Please log in.\"\\n    elif code == ___:\\n        return \"Not Found! Resource does not exist.\"\\n    elif code == ___:\\n        return \"Server Error! Our engineers are on it.\"\\n    return \"Unknown status code\"\\n\\ncodes = [200, 401, 404, 500]\\nfor c in codes:\\n    print(f\"{c}: {handle_status(c)}\")", "solution": "def handle_status(code):\\n    if code == 200:\\n        return \"Success! Data fetched.\"\\n    elif code == 401:\\n        return \"Unauthorized! Please log in.\"\\n    elif code == 404:\\n        return \"Not Found! Resource does not exist.\"\\n    elif code == 500:\\n        return \"Server Error! Our engineers are on it.\"\\n    return \"Unknown status code\"\\n\\ncodes = [200, 401, 404, 500]\\nfor c in codes:\\n    print(f\"{c}: {handle_status(c)}\")", "hint": "Match the codes to the messages (200, 401, 404, 500).", "rubric": "Function correctly identifies all 4 status codes."}
    ],
    "Microservices": [
        {"title": "Monolith vs Microservices", "theory": "## Breaking Up the App\\n- **Monolith**: All code (auth, payments, catalog) is in one giant repository and runs as a single process. Hard to scale specific parts.\\n- **Microservices**: Small, independent services that communicate via APIs. You can scale the Payment service independently of the Catalog service.\\n\\nMicroservices introduce complexity: network latency, distributed data, and harder debugging.", "instructions": "## Task: Architecture Comparison\\n1. Create a dictionary that categorizes traits to either 'Monolith' or 'Microservices'.\\n2. Traits: 'Single Codebase', 'Independent Deployments', 'Complex Networking', 'Easier to Debug initially'", "starterCode": "traits = {\\n    'Single Codebase': '___',\\n    'Independent Deployments': '___',\\n    'Complex Networking': '___',\\n    'Easier to Debug initially': '___'\\n}\\n\\nfor trait, arch in traits.items():\\n    print(f\"{trait:30} -> {arch}\")", "solution": "traits = {\\n    'Single Codebase': 'Monolith',\\n    'Independent Deployments': 'Microservices',\\n    'Complex Networking': 'Microservices',\\n    'Easier to Debug initially': 'Monolith'\\n}\\n\\nfor trait, arch in traits.items():\\n    print(f\"{trait:30} -> {arch}\")", "hint": "Monolith = single, easy to debug early on. Microservices = independent, complex network.", "rubric": "Traits correctly mapped to Monolith or Microservices."}
    ]
})

# From Batch 11
LESSONS_BATCH21.update({
    "GraphQL": [
        {"title": "Intro to GraphQL", "theory": "## A Query Language for APIs\\nUnlike REST (where you hit multiple URLs for different data), GraphQL exposes a single endpoint (e.g., `/graphql`).\\n\\n- The **Client** dictates exactly what data it wants.\\n- Prevents **Over-fetching** (getting too much data) and **Under-fetching** (needing to make 5 requests to get everything).\\n\\n```graphql\\nquery {\\n  user(id: 1) {\\n    name\\n    posts {\\n      title\\n    }\\n  }\\n}\\n```", "instructions": "## Task: The Problem with REST\\n1. Define 'overfetching' as downloading more data than needed.\\n2. Define 'underfetching' as needing multiple API calls to get enough data.\\n3. Create a dictionary matching scenarios to these terms.", "starterCode": "graphql_benefits = {\\n    'Fetching a User profile just to get their name, but getting 5MB of history too': '___',\\n    'Calling /users, then /users/1/posts, then /posts/2/comments just to show a page': '___'\\n}\\n\\nfor scenario, term in graphql_benefits.items():\\n    print(f\"Scenario:\\n{scenario}\\n-> Problem: {term}\\n\")", "solution": "graphql_benefits = {\\n    'Fetching a User profile just to get their name, but getting 5MB of history too': 'overfetching',\\n    'Calling /users, then /users/1/posts, then /posts/2/comments just to show a page': 'underfetching'\\n}\\n\\nfor scenario, term in graphql_benefits.items():\\n    print(f\"Scenario:\\n{scenario}\\n-> Problem: {term}\\n\")", "hint": "Overfetching = too much data. Underfetching = too many requests.", "rubric": "Scenarios correctly matched to overfetching and underfetching."},
        {"title": "Schemas and Resolvers", "theory": "## How it Works\\nOn the server, you define a **Schema** (the shape of the data) and **Resolvers** (functions that actually fetch the data).\\n\\n```javascript\\n// 1. Schema\\ntype Query {\\n  hello: String\\n}\\n\\n// 2. Resolver\\nconst resolvers = {\\n  Query: {\\n    hello: () => 'Hello world!',\\n  },\\n};\\n```", "instructions": "## Task: Write a Resolver\\n1. You have a simulated database `mock_db`.\\n2. Write a resolver function `get_user(id)` that returns the user dict.\\n3. Return `None` if the user doesn't exist.", "starterCode": "mock_db = {\\n    1: {'name': 'Alice', 'role': 'Admin'},\\n    2: {'name': 'Bob', 'role': 'User'}\\n}\\n\\ndef get_user_resolver(user_id):\\n    # Return the user from mock_db or None\\n    return mock_db.___(___)\\n\\n# Simulating a GraphQL Query: query { user(id: 1) { name } }\\nresult = get_user_resolver(1)\\nprint(\"User 1 Name:\", result['name'])\\n\\n# Simulating missing user\\nprint(\"User 99:\", get_user_resolver(99))", "solution": "mock_db = {\\n    1: {'name': 'Alice', 'role': 'Admin'},\\n    2: {'name': 'Bob', 'role': 'User'}\\n}\\n\\ndef get_user_resolver(user_id):\\n    # Return the user from mock_db or None\\n    return mock_db.get(user_id)\\n\\n# Simulating a GraphQL Query: query { user(id: 1) { name } }\\nresult = get_user_resolver(1)\\nprint(\"User 1 Name:\", result['name'])\\n\\n# Simulating missing user\\nprint(\"User 99:\", get_user_resolver(99))", "hint": "Use the .get(key) dictionary method to safely fetch or return None.", "rubric": "Resolver safely fetches existing users and returns None for missing ones."}
    ]
})

# From Batch 13
LESSONS_BATCH21.update({
    "API Connections": [
        {"title": "Webhooks vs Polling", "theory": "## Getting Real-time Data\\nIf you want an AI agent to respond when a new email arrives, how does it know an email arrived?\\n\\n- **Polling**: The agent asks the server every 5 minutes: \"Any new emails?\" (Inefficient, lots of wasted API calls).\\n- **Webhooks**: You give the email server a URL. When an email arrives, the server immediately sends a POST request to that URL (Efficient, instant).", "instructions": "## Task: Webhook Server Mock\\n1. Build a mock webhook endpoint in Python.\\n2. When a `POST` request hits the endpoint, it should trigger the AI agent.\\n3. We will simulate this with a simple function call.", "starterCode": "def ai_agent_process(data):\\n    print(\"AI Agent processing new data:\", data['message'])\\n\\ndef webhook_endpoint(request_method, payload):\\n    if request_method != '___':\\n        return \"Error: Only POST allowed\"\\n        \\n    # Webhooks usually send JSON payloads\\n    print(\"Webhook received payload!\")\\n    \\n    # Trigger the agent immediately\\n    ___(payload)\\n    \\n    return \"Success: 200 OK\"\\n\\n# Simulate GitHub sending a webhook when a repo gets a star\\ngithub_payload = {'event': 'star', 'message': 'User Bob starred your repo!'}\\n\\nprint(webhook_endpoint('GET', github_payload))\\nprint(\"---\")\\nprint(webhook_endpoint('POST', github_payload))", "solution": "def ai_agent_process(data):\\n    print(\"AI Agent processing new data:\", data['message'])\\n\\ndef webhook_endpoint(request_method, payload):\\n    if request_method != 'POST':\\n        return \"Error: Only POST allowed\"\\n        \\n    # Webhooks usually send JSON payloads\\n    print(\"Webhook received payload!\")\\n    \\n    # Trigger the agent immediately\\n    ai_agent_process(payload)\\n    \\n    return \"Success: 200 OK\"\\n\\n# Simulate GitHub sending a webhook when a repo gets a star\\ngithub_payload = {'event': 'star', 'message': 'User Bob starred your repo!'}\\n\\nprint(webhook_endpoint('GET', github_payload))\\nprint(\"---\")\\nprint(webhook_endpoint('POST', github_payload))", "hint": "Method should be 'POST'. Call ai_agent_process(payload).", "rubric": "GET request is rejected. POST request triggers the AI agent processing."}
    ]
})

# From Batch 15
LESSONS_BATCH21.update({
    "Automated Content": [
        {"title": "Content Generation", "theory": "## AI Writers at Scale\\nAutomated content pipelines take raw data and turn it into polished content automatically.\\n\\nPipeline flow:\\n1. **Ingest**: Read a raw JSON feed (e.g., weather data).\\n2. **Prompt Construction**: Inject the data into a prompt template.\\n3. **LLM Generation**: Ask the AI to write a natural language summary.\\n4. **Publish**: Send the summary to a CMS or Twitter.", "instructions": "## Task: Weather Bot Simulator\\n1. You have raw weather data in a dictionary.\\n2. Create a function that formats a prompt for the AI.\\n3. The prompt should say: \"Write a friendly weather report for [City]. The temp is [Temp] and it's [Condition].\"", "starterCode": "def create_prompt(weather_data):\\n    city = weather_data['___']\\n    temp = weather_data['___']\\n    condition = weather_data['___']\\n    \\n    return f\"Write a friendly weather report for {___}. The temp is {___} and it's {___}.\"\\n\\nraw_data = {\\n    'city': 'Seattle',\\n    'temp': '65F',\\n    'condition': 'raining as usual'\\n}\\n\\nprompt = create_prompt(raw_data)\\nprint(\"Generated Prompt to send to LLM:\\n\", prompt)", "solution": "def create_prompt(weather_data):\\n    city = weather_data['city']\\n    temp = weather_data['temp']\\n    condition = weather_data['condition']\\n    \\n    return f\"Write a friendly weather report for {city}. The temp is {temp} and it's {condition}.\"\\n\\nraw_data = {\\n    'city': 'Seattle',\\n    'temp': '65F',\\n    'condition': 'raining as usual'\\n}\\n\\nprompt = create_prompt(raw_data)\\nprint(\"Generated Prompt to send to LLM:\\n\", prompt)", "hint": "Extract keys: 'city', 'temp', 'condition'. Inject them into the f-string.", "rubric": "Prompt correctly incorporates the data from the dictionary."}
    ]
})

# From Batch 16
LESSONS_BATCH21.update({
    "Email Automation": [
        {"title": "Programmatic Email", "theory": "## Sending and Receiving via API\\nAutomating emails is a core part of many workflows (e.g., sending receipts, newsletter campaigns, or having an AI read customer support emails).\\n\\n- **Sending (SMTP/APIs)**: Tools like SendGrid or AWS SES allow you to send emails via HTTP requests, which is much more reliable than SMTP.\\n- **Receiving (IMAP/Webhooks)**: Instead of polling an inbox with IMAP, modern systems use webhooks to instantly notify your server when an email arrives.", "instructions": "## Task: SendGrid Simulator\\n1. Simulate sending an email using a mock SendGrid API function.\\n2. The function should accept `to_email`, `subject`, and `body`.\\n3. Return a success message with the recipient's email.", "starterCode": "def mock_sendgrid_api(to_email, subject, body):\\n    # Simulate HTTP POST request to api.sendgrid.com\\n    payload = {\\n        \"personalizations\": [{\"to\": [{\"email\": to_email}]}],\\n        \"subject\": subject,\\n        \"content\": [{\"type\": \"text/plain\", \"value\": body}]\\n    }\\n    \\n    print(\"Sending payload to SendGrid:\\n\", payload)\\n    return f\"202 Accepted: Email sent to {___}\"\\n\\nresponse = mock_sendgrid_api(\"alice@example.com\", \"Welcome!\", \"Thanks for signing up.\")\\nprint(\"\\nResponse:\", response)", "solution": "def mock_sendgrid_api(to_email, subject, body):\\n    # Simulate HTTP POST request to api.sendgrid.com\\n    payload = {\\n        \"personalizations\": [{\"to\": [{\"email\": to_email}]}],\\n        \"subject\": subject,\\n        \"content\": [{\"type\": \"text/plain\", \"value\": body}]\\n    }\\n    \\n    print(\"Sending payload to SendGrid:\\n\", payload)\\n    return f\"202 Accepted: Email sent to {to_email}\"\\n\\nresponse = mock_sendgrid_api(\"alice@example.com\", \"Welcome!\", \"Thanks for signing up.\")\\nprint(\"\\nResponse:\", response)", "hint": "Use the to_email variable in the return string.", "rubric": "Successfully simulates sending an email and prints the 202 Accepted message with the correct email."}
    ],
    "Evaluation": [
        {"title": "Evaluating LLM Outputs", "theory": "## How do you test AI?\\nStandard unit tests (`assert 2+2 == 4`) don't work for generative AI because the output is slightly different every time.\\n\\nEvaluation methods:\\n1. **Exact Match / Regex**: Check if the output contains a specific keyword or JSON structure.\\n2. **Semantic Similarity**: Use embeddings to check if the *meaning* is close to a reference answer.\\n3. **LLM-as-a-Judge**: Use a stronger LLM (like GPT-4) to grade the output of a smaller model (like Llama 3) based on a rubric.", "instructions": "## Task: LLM as a Judge\\n1. Simulate an LLM judge evaluating a generated response.\\n2. If the response contains the word 'sorry' or 'cannot', score it 0 (refusal).\\n3. Otherwise, score it 100.", "starterCode": "def llm_judge(generated_text):\\n    lower_text = generated_text.___()\\n    if 'sorry' in lower_text or 'cannot' in lower_text:\\n        return ___\\n    return ___\\n\\nresponse1 = \"I'm sorry, I cannot fulfill that request as it violates safety policies.\"\\nresponse2 = \"The capital of France is Paris.\"\\n\\nprint(f\"Response 1 Score: {llm_judge(response1)}\")\\nprint(f\"Response 2 Score: {llm_judge(response2)}\")", "solution": "def llm_judge(generated_text):\\n    lower_text = generated_text.lower()\\n    if 'sorry' in lower_text or 'cannot' in lower_text:\\n        return 0\\n    return 100\\n\\nresponse1 = \"I'm sorry, I cannot fulfill that request as it violates safety policies.\"\\nresponse2 = \"The capital of France is Paris.\"\\n\\nprint(f\"Response 1 Score: {llm_judge(response1)}\")\\nprint(f\"Response 2 Score: {llm_judge(response2)}\")", "hint": "Convert to lower(). Return 0 for refusal, 100 for success.", "rubric": "Response 1 scores 0, Response 2 scores 100."}
    ]
})

# From Batch 17
LESSONS_BATCH21.update({
    "Autonomous Execution": [
        {"title": "Letting the AI Drive", "theory": "## Operating in a Loop\\nAn autonomous agent doesn't stop after answering one question. It operates in a loop (like AutoGPT).\\n\\n1. **Think**: \"What should I do next?\"\\n2. **Act**: Use a tool (e.g., search Google).\\n3. **Observe**: Read the search results.\\n4. **Loop**: Go back to step 1 until the final goal is reached.\\n\\n*Danger*: If the loop has no limits, it can rack up huge API bills or get stuck in infinite loops.", "instructions": "## Task: The ReAct Loop\\n1. Simulate an autonomous loop that runs until `goal_reached` is True.\\n2. Add a `max_steps` safeguard to prevent infinite loops.\\n3. The loop should stop after 3 steps, returning 'Timeout' if the goal wasn't reached.", "starterCode": "def autonomous_agent(goal, max_steps=3):\\n    step = 0\\n    goal_reached = False\\n    \\n    while not goal_reached and step < ___:\\n        step += 1\\n        print(f\"Step {step}: Thinking & Acting...\")\\n        \\n        # Simulate finding the answer on step 4 (which is past the limit!)\\n        if step == 4:\\n            goal_reached = True\\n            \\n    if not goal_reached:\\n        return \"Error: ___ reached without solving goal.\"\\n    return \"Success!\"\\n\\nresult = autonomous_agent(\"Find the cure for aging\")\\nprint(result)", "solution": "def autonomous_agent(goal, max_steps=3):\\n    step = 0\\n    goal_reached = False\\n    \\n    while not goal_reached and step < max_steps:\\n        step += 1\\n        print(f\"Step {step}: Thinking & Acting...\")\\n        \\n        # Simulate finding the answer on step 4 (which is past the limit!)\\n        if step == 4:\\n            goal_reached = True\\n            \\n    if not goal_reached:\\n        return \"Error: Timeout reached without solving goal.\"\\n    return \"Success!\"\\n\\nresult = autonomous_agent(\"Find the cure for aging\")\\nprint(result)", "hint": "step < max_steps. Return 'Timeout'.", "rubric": "Loop runs 3 times and returns the Timeout error, successfully preventing an infinite loop."}
    ]
})

def apply_lessons(tracks_dir):
    total = 0
    # Process EVERY json file directly instead of using track_courses keys which might be mismatched
    for filename in os.listdir(tracks_dir):
        if not filename.endswith('.json'):
            continue
            
        filepath = os.path.join(tracks_dir, filename)
        with open(filepath, 'r', encoding='utf-8') as f:
            track_data = json.load(f)
            
        updated = False
        for course_name in track_data:
            if course_name in LESSONS_BATCH21:
                track_data[course_name]['lessons'] = LESSONS_BATCH21[course_name]
                updated = True
                total += len(LESSONS_BATCH21[course_name])
                print(f"Applied {course_name} in {filename}")
                
        if updated:
            with open(filepath, 'w', encoding='utf-8') as f:
                json.dump(track_data, f, indent=2, ensure_ascii=False)
                
    print(f'Batch 21: Applied {total} lessons')
    os.system('python build_courses.py')

if __name__ == '__main__':
    apply_lessons(os.path.join('curriculum', 'tracks'))
