"""
Batch 19: Model Deployment, Transfer Learning, Computer Vision
"""
import json, os

LESSONS_BATCH19 = {
    # ─── DATA ENGINEERING ───
    "Model Deployment": [
        {"title": "Serving ML Models", "theory": "## From Notebook to Production\nTraining a model in a Jupyter Notebook is easy. Serving it to thousands of users is hard.\n\nWays to deploy:\n- **Batch Inference**: Run the model once a day on new data and save the results to a database.\n- **Real-time API**: Wrap the model in a FastAPI or Flask app. Users send HTTP requests with data, the model predicts and returns the result instantly.\n- **Edge Computing**: Run the model directly on the user's phone (e.g., Apple CoreML).", "instructions": "## Task: Mock FastAPI Deployment\n1. Simulate wrapping an ML model inside a web API.\n2. Create a function `predict_endpoint` that takes a JSON dictionary payload.\n3. The model needs a 'feature_x' to predict. If it's missing, return a 400 Error.", "starterCode": "def mock_model_predict(x):\n    return x * 2.5\n\ndef predict_endpoint(payload):\n    # 1. Validate payload\n    if 'feature_x' not in ___:\n        return {\"status\": 400, \"error\": \"Missing feature_x\"}\n        \n    # 2. Extract data\n    x = payload['___']\n    \n    # 3. Call model\n    prediction = mock_model_predict(x)\n    \n    # 4. Return result\n    return {\"status\": ___, \"prediction\": prediction}\n\nprint(\"Valid Request:\", predict_endpoint({\"feature_x\": 10}))\nprint(\"Invalid Request:\", predict_endpoint({\"age\": 25}))", "solution": "def mock_model_predict(x):\n    return x * 2.5\n\ndef predict_endpoint(payload):\n    # 1. Validate payload\n    if 'feature_x' not in payload:\n        return {\"status\": 400, \"error\": \"Missing feature_x\"}\n        \n    # 2. Extract data\n    x = payload['feature_x']\n    \n    # 3. Call model\n    prediction = mock_model_predict(x)\n    \n    # 4. Return result\n    return {\"status\": 200, \"prediction\": prediction}\n\nprint(\"Valid Request:\", predict_endpoint({\"feature_x\": 10}))\nprint(\"Invalid Request:\", predict_endpoint({\"age\": 25}))", "hint": "Check if 'feature_x' is in payload. Extract payload['feature_x']. Return status 200.", "rubric": "Valid request returns status 200 and prediction 25.0. Invalid request returns 400."}
    ],
    "Drift Detection": [
        {"title": "Concept Drift", "theory": "## Models Degrade Over Time\nIf you train a model to predict housing prices in 2019, it will be terrible at predicting prices in 2024. The world changes, but the model doesn't.\n\n- **Data Drift**: The incoming data changes (e.g., a sensor breaks and starts sending weird numbers).\n- **Concept Drift**: The relationship between the data and the target changes (e.g., inflation changes the meaning of a '$500,000 house').\n\nYou must monitor the *distribution* of incoming data to detect drift and trigger a retraining pipeline.", "instructions": "## Task: Simple Drift Detector\n1. Calculate the average (mean) of a feature in the training data.\n2. Compare it to the average of the live production data.\n3. If the difference is greater than the threshold (10.0), flag it as drift.", "starterCode": "def check_drift(train_data, live_data, threshold=10.0):\n    # Calculate averages\n    train_mean = sum(train_data) / len(___)\n    live_mean = sum(live_data) / len(___)\n    \n    # Calculate absolute difference\n    diff = abs(train_mean - ___)\n    print(f\"Train Mean: {train_mean:.1f} | Live Mean: {live_mean:.1f} | Diff: {diff:.1f}\")\n    \n    if diff > ___:\n        return \"ALERT: Data Drift Detected! Retrain Model.\"\n    return \"Data is stable.\"\n\ntrain = [50, 52, 48, 51, 49]\nlive_week1 = [51, 49, 53, 50, 48] # Stable\nlive_week2 = [75, 80, 72, 78, 85] # Drifted\n\nprint(\"Week 1 Check:\", check_drift(train, live_week1))\nprint(\"\\nWeek 2 Check:\", check_drift(train, live_week2))", "solution": "def check_drift(train_data, live_data, threshold=10.0):\n    # Calculate averages\n    train_mean = sum(train_data) / len(train_data)\n    live_mean = sum(live_data) / len(live_data)\n    \n    # Calculate absolute difference\n    diff = abs(train_mean - live_mean)\n    print(f\"Train Mean: {train_mean:.1f} | Live Mean: {live_mean:.1f} | Diff: {diff:.1f}\")\n    \n    if diff > threshold:\n        return \"ALERT: Data Drift Detected! Retrain Model.\"\n    return \"Data is stable.\"\n\ntrain = [50, 52, 48, 51, 49]\nlive_week1 = [51, 49, 53, 50, 48] # Stable\nlive_week2 = [75, 80, 72, 78, 85] # Drifted\n\nprint(\"Week 1 Check:\", check_drift(train, live_week1))\nprint(\"\\nWeek 2 Check:\", check_drift(train, live_week2))", "hint": "len(train_data), len(live_data). abs(train_mean - live_mean). Compare diff to threshold.", "rubric": "Code correctly identifies Week 1 as stable and Week 2 as drifted."}
    ],
    # ─── AI ENGINEERING ───
    "Transfer Learning": [
        {"title": "Don't Start from Scratch", "theory": "## Standing on the Shoulders of Giants\nTraining an image recognition model from scratch requires millions of images and thousands of dollars in GPU time.\n\n**Transfer Learning** allows you to download a pre-trained model (like ResNet, trained by Google/Microsoft) that already knows how to see shapes, edges, and objects.\n\nYou \"freeze\" the early layers (so they don't change), and only train the very last layer on your specific dataset (e.g., distinguishing between hotdogs and not hotdogs).", "instructions": "## Task: Freeze Layers\n1. Simulate a pre-trained model as a list of layers.\n2. Iterate through the layers. If the layer is not the 'Final_Classification_Layer', set its `trainable` property to False.\n3. This freezes the foundational knowledge of the model.", "starterCode": "class Layer:\n    def __init__(self, name):\n        self.name = name\n        self.trainable = True # By default, layers can be trained\n\nmodel_layers = [\n    Layer(\"Conv1_Edges\"),\n    Layer(\"Conv2_Shapes\"),\n    Layer(\"Conv3_Objects\"),\n    Layer(\"Final_Classification_Layer\")\n]\n\ndef apply_transfer_learning(layers):\n    for layer in layers:\n        if layer.name != \"___\":\n            layer.___ = ___\n            print(f\"Froze {layer.name}\")\n        else:\n            print(f\"Kept {layer.name} trainable\")\n\napply_transfer_learning(model_layers)", "solution": "class Layer:\n    def __init__(self, name):\n        self.name = name\n        self.trainable = True # By default, layers can be trained\n\nmodel_layers = [\n    Layer(\"Conv1_Edges\"),\n    Layer(\"Conv2_Shapes\"),\n    Layer(\"Conv3_Objects\"),\n    Layer(\"Final_Classification_Layer\")\n]\n\ndef apply_transfer_learning(layers):\n    for layer in layers:\n        if layer.name != \"Final_Classification_Layer\":\n            layer.trainable = False\n            print(f\"Froze {layer.name}\")\n        else:\n            print(f\"Kept {layer.name} trainable\")\n\napply_transfer_learning(model_layers)", "hint": "Check against 'Final_Classification_Layer'. Set layer.trainable to False.", "rubric": "All layers except the final one are frozen (trainable = False)."}
    ],
    "Object Detection": [
        {"title": "Bounding Boxes", "theory": "## Where is the Object?\nImage Classification says: \"This is a picture of a dog.\"\nObject Detection says: \"There is a dog at coordinates (X, Y) with width W and height H.\"\n\nPopular Object Detection algorithms:\n- **YOLO (You Only Look Once)**: Extremely fast, great for real-time video.\n- **Faster R-CNN**: Very accurate, but slower.", "instructions": "## Task: Bounding Box Area\n1. You are given the coordinates of a bounding box: `(x_min, y_min, x_max, y_max)`.\n2. Calculate the width and height of the box.\n3. Calculate the area of the box (width * height).", "starterCode": "def calculate_bbox_area(bbox):\n    x_min, y_min, x_max, y_max = bbox\n    \n    width = ___ - ___\n    height = ___ - ___\n    \n    area = ___ * ___\n    return area\n\n# A box representing a detected car\ncar_box = (100, 50, 300, 150) # (x_min, y_min, x_max, y_max)\n\nprint(\"Bounding Box Area:\", calculate_bbox_area(car_box), \"pixels\")", "solution": "def calculate_bbox_area(bbox):\n    x_min, y_min, x_max, y_max = bbox\n    \n    width = x_max - x_min\n    height = y_max - y_min\n    \n    area = width * height\n    return area\n\n# A box representing a detected car\ncar_box = (100, 50, 300, 150) # (x_min, y_min, x_max, y_max)\n\nprint(\"Bounding Box Area:\", calculate_bbox_area(car_box), \"pixels\")", "hint": "Width is x_max - x_min. Height is y_max - y_min.", "rubric": "Calculates the area correctly as 20000 pixels."}
    ],
    "GANs": [
        {"title": "Generative Adversarial Networks", "theory": "## The Forger and the Detective\nGANs are used to generate fake images (like deepfakes or AI art).\n\nThey consist of two neural networks fighting each other:\n1. **Generator**: The \"Forger\". It tries to create fake images from random noise.\n2. **Discriminator**: The \"Detective\". It looks at images and tries to guess if they are real (from the dataset) or fake (from the Generator).\n\nThey train together until the Generator makes images so good that the Discriminator is forced to guess 50/50.", "instructions": "## Task: GAN Simulator\n1. Simulate the training loop of a GAN.\n2. The Generator's skill increases by 1 each epoch.\n3. The Discriminator's skill increases by 1 each epoch.\n4. If the Generator's skill is equal to or greater than the Discriminator's, the Generator \"wins\" that round.", "starterCode": "def simulate_gan_training(epochs):\n    generator_skill = 10\n    discriminator_skill = 15 # Detective starts with an advantage\n    \n    for epoch in range(1, epochs + 1):\n        # Both get better over time, but generator learns slightly faster here\n        generator_skill += 2\n        discriminator_skill += 1\n        \n        if generator_skill >= ___:\n            print(f\"Epoch {epoch}: Generator fooled the Discriminator!\")\n        else:\n            print(f\"Epoch {epoch}: Discriminator caught the fake.\")\n\nsimulate_gan_training(7)", "solution": "def simulate_gan_training(epochs):\n    generator_skill = 10\n    discriminator_skill = 15 # Detective starts with an advantage\n    \n    for epoch in range(1, epochs + 1):\n        # Both get better over time, but generator learns slightly faster here\n        generator_skill += 2\n        discriminator_skill += 1\n        \n        if generator_skill >= discriminator_skill:\n            print(f\"Epoch {epoch}: Generator fooled the Discriminator!\")\n        else:\n            print(f\"Epoch {epoch}: Discriminator caught the fake.\")\n\nsimulate_gan_training(7)", "hint": "Compare generator_skill to discriminator_skill.", "rubric": "Generator eventually catches up and fools the discriminator around epoch 5."}
    ]
}

def apply_lessons(tracks_dir):
    from rebuild_curriculum import track_courses
    total = 0
    for track_name, levels in track_courses.items():
        safe_name = track_name.lower().replace(" ", "_").replace("&", "").replace("__", "_") + ".json"
        filepath = os.path.join(tracks_dir, safe_name)
        if not os.path.exists(filepath): continue
        with open(filepath, 'r', encoding='utf-8') as f:
            track_data = json.load(f)
        updated = False
        for course_name in track_data:
            if course_name in LESSONS_BATCH19:
                track_data[course_name]['lessons'] = LESSONS_BATCH19[course_name]
                updated = True
                total += len(LESSONS_BATCH19[course_name])
        if updated:
            with open(filepath, 'w', encoding='utf-8') as f:
                json.dump(track_data, f, indent=2, ensure_ascii=False)
    print(f'Batch 19: Applied {total} lessons')
    os.system('python build_courses.py')

if __name__ == '__main__':
    apply_lessons(os.path.join('curriculum', 'tracks'))
