"""
Batch 18: Fine-tuning, Apache Spark, Advanced Data Science
"""
import json, os

LESSONS_BATCH18 = {
    # ─── AI ENGINEERING ───
    "Fine-tuning Models": [
        {"title": "When to Fine-tune?", "theory": "## Teaching Old Dogs New Tricks\nYou don't always need to fine-tune an LLM. Often, **RAG** (Retrieval-Augmented Generation) or good **Prompt Engineering** is enough.\n\nFine-tune when:\n- You want the model to learn a specific *format* or *tone* (e.g., answering like Shakespeare).\n- You have thousands of highly specific examples (e.g., medical diagnostics).\n\nFine-tuning updates the actual \"weights\" of the neural network using backpropagation.", "instructions": "## Task: RAG vs Fine-tuning\n1. Match the scenario to the best approach: 'RAG', 'Prompt Engineering', or 'Fine-tuning'.\n2. Scenarios: \n   - 'Teaching a model to output strict proprietary JSON structures.'\n   - 'Allowing a model to answer questions about today\\'s news.'\n   - 'Telling a model to be polite in a single instruction.'", "starterCode": "scenarios = {\n    'Teaching a model to output strict proprietary JSON structures.': '___',\n    'Allowing a model to answer questions about todays news.': '___',\n    'Telling a model to be polite in a single instruction.': '___'\n}\n\nfor scenario, method in scenarios.items():\n    print(f\"Scenario: {scenario}\\nMethod: {method}\\n\")", "solution": "scenarios = {\n    'Teaching a model to output strict proprietary JSON structures.': 'Fine-tuning',\n    'Allowing a model to answer questions about todays news.': 'RAG',\n    'Telling a model to be polite in a single instruction.': 'Prompt Engineering'\n}\n\nfor scenario, method in scenarios.items():\n    print(f\"Scenario: {scenario}\\nMethod: {method}\\n\")", "hint": "Format/Structure = Fine-tuning. New knowledge = RAG. Simple instruction = Prompt Engineering.", "rubric": "Scenarios are correctly matched to Fine-tuning, RAG, and Prompt Engineering."}
    ],
    "Evaluating AI Output": [
        {"title": "BLEU and ROUGE", "theory": "## Scoring Text\nHow do we automatically score translation or summarization tasks?\n\n- **BLEU**: Used mostly for Translation. It checks how many words/phrases in the AI output match the human reference.\n- **ROUGE**: Used mostly for Summarization. It measures recall (how much of the human reference was captured by the AI).", "instructions": "## Task: Simple Word Overlap\n1. Implement a basic evaluation metric that calculates the percentage of words in the AI generated text that appear in the reference text.\n2. Both sentences should be lowercased and split into sets of words.", "starterCode": "def calculate_overlap(reference, generated):\n    ref_words = set(reference.___().split())\n    gen_words = set(generated.___().___())\n    \n    # Find intersection of both sets\n    overlap = ref_words.___(gen_words)\n    \n    # Calculate percentage (0.0 to 1.0)\n    score = len(overlap) / len(___)\n    return score\n\nref = \"The quick brown fox jumps over the lazy dog\"\ngen = \"The fast brown fox jumps over a lazy dog\"\n\nscore = calculate_overlap(ref, gen)\nprint(f\"Overlap Score: {score * 100:.1f}%\")", "solution": "def calculate_overlap(reference, generated):\n    ref_words = set(reference.lower().split())\n    gen_words = set(generated.lower().split())\n    \n    # Find intersection of both sets\n    overlap = ref_words.intersection(gen_words)\n    \n    # Calculate percentage (0.0 to 1.0)\n    score = len(overlap) / len(gen_words)\n    return score\n\nref = \"The quick brown fox jumps over the lazy dog\"\ngen = \"The fast brown fox jumps over a lazy dog\"\n\nscore = calculate_overlap(ref, gen)\nprint(f\"Overlap Score: {score * 100:.1f}%\")", "hint": "Use .lower() and .split(). Use .intersection() to find common words. Divide by len(gen_words).", "rubric": "Calculates an overlap score successfully."}
    ],
    # ─── DATA SCIENCE ───
    "Feature Engineering": [
        {"title": "One-Hot Encoding", "theory": "## Converting Categories to Numbers\nMachine Learning models can't understand words like 'Red', 'Blue', or 'Green'. We must convert them to numbers.\n\nIf we just assign Red=1, Blue=2, Green=3 (Label Encoding), the model might think Green > Red. \n\n**One-Hot Encoding** creates a new binary column for each category.", "instructions": "## Task: Create Dummy Variables\n1. Use Pandas `get_dummies()` to apply One-Hot Encoding to the 'Color' column.\n2. Note how it creates new columns with 0s and 1s.", "starterCode": "import pandas as pd\n\ndf = pd.DataFrame({\n    'ID': [1, 2, 3],\n    'Color': ['Red', 'Blue', 'Red']\n})\n\nprint(\"Original:\")\nprint(df)\n\n# Apply One-Hot Encoding\ndf_encoded = pd.___(df, columns=['___'])\n\nprint(\"\\nEncoded:\")\nprint(df_encoded)", "solution": "import pandas as pd\n\ndf = pd.DataFrame({\n    'ID': [1, 2, 3],\n    'Color': ['Red', 'Blue', 'Red']\n})\n\nprint(\"Original:\")\nprint(df)\n\n# Apply One-Hot Encoding\ndf_encoded = pd.get_dummies(df, columns=['Color'])\n\nprint(\"\\nEncoded:\")\nprint(df_encoded)", "hint": "Use pd.get_dummies() and pass 'Color' as the column.", "rubric": "Dataframe correctly expands into Color_Red and Color_Blue columns."}
    ],
    "Advanced ML Models": [
        {"title": "Random Forests", "theory": "## The Wisdom of Crowds\nA Decision Tree makes decisions based on simple splits (e.g., Is Age > 30?). However, single trees are prone to **overfitting** (memorizing the training data).\n\nA **Random Forest** trains hundreds of different Decision Trees on random subsets of the data and averages their predictions. This creates a much stronger, more robust model.", "instructions": "## Task: Ensemble Simulator\n1. Simulate a Random Forest predicting whether it will rain.\n2. You have 3 simulated 'trees' that vote True or False.\n3. Return the majority vote.", "starterCode": "def random_forest_predict(tree1_vote, tree2_vote, tree3_vote):\n    votes = [tree1_vote, tree2_vote, tree3_vote]\n    \n    # Count how many True votes there are\n    true_count = sum(___)\n    \n    # Return True if majority (>= 2) voted True\n    return true_count >= ___\n\n# Trees output: False, True, True\nprediction = random_forest_predict(False, True, True)\nprint(\"Random Forest Prediction (Will it rain?):\", prediction)", "solution": "def random_forest_predict(tree1_vote, tree2_vote, tree3_vote):\n    votes = [tree1_vote, tree2_vote, tree3_vote]\n    \n    # Count how many True votes there are\n    true_count = sum(votes)\n    \n    # Return True if majority (>= 2) voted True\n    return true_count >= 2\n\n# Trees output: False, True, True\nprediction = random_forest_predict(False, True, True)\nprint(\"Random Forest Prediction (Will it rain?):\", prediction)", "hint": "sum(votes) counts the True values (since True is 1 in Python). Check if it's >= 2.", "rubric": "Function returns True because 2 out of 3 trees voted True."}
    ],
    # ─── DATA ENGINEERING ───
    "Apache Spark": [
        {"title": "Big Data Processing", "theory": "## In-Memory Speed\nWhen data is too big for Pandas (which requires all data to fit in RAM on one machine), we use **Apache Spark**.\n\nSpark distributes the data across a cluster of computers and processes it in parallel. It uses **RDDs** (Resilient Distributed Datasets) and DataFrames.\n\nBecause it does much of its processing in RAM, it's 100x faster than older Hadoop MapReduce systems.", "instructions": "## Task: MapReduce Simulator\n1. Simulate the Map and Reduce phases of a distributed big data job.\n2. Map phase: Square every number in a list.\n3. Reduce phase: Sum all the squared numbers together.", "starterCode": "def mock_spark_job(data):\n    print(\"Original Data:\", data)\n    \n    # 1. Map Phase (Applies function to every element)\n    # Square each number\n    mapped = list(map(lambda x: ___, data))\n    print(\"Mapped Data:\", mapped)\n    \n    # 2. Reduce Phase (Aggregates list into a single value)\n    from functools import reduce\n    # Sum all numbers\n    result = reduce(lambda a, b: ___, mapped)\n    \n    return result\n\nbig_data = [1, 2, 3, 4, 5]\nfinal_result = mock_spark_job(big_data)\nprint(\"Final Reduced Result:\", final_result)", "solution": "def mock_spark_job(data):\n    print(\"Original Data:\", data)\n    \n    # 1. Map Phase (Applies function to every element)\n    # Square each number\n    mapped = list(map(lambda x: x**2, data))\n    print(\"Mapped Data:\", mapped)\n    \n    # 2. Reduce Phase (Aggregates list into a single value)\n    from functools import reduce\n    # Sum all numbers\n    result = reduce(lambda a, b: a + b, mapped)\n    \n    return result\n\nbig_data = [1, 2, 3, 4, 5]\nfinal_result = mock_spark_job(big_data)\nprint(\"Final Reduced Result:\", final_result)", "hint": "lambda x: x**2 to square. lambda a, b: a + b to sum.", "rubric": "Data is squared ([1, 4, 9, 16, 25]) and then summed (55)."}
    ],
    "Kafka Streaming": [
        {"title": "Real-time Data Pipelines", "theory": "## Event Streams\nTraditionally, data is processed in \"batches\" (e.g., every night at midnight). \n\n**Apache Kafka** enables \"streaming\" architecture. As soon as an event happens (e.g., a user clicks a button), it is published to a Kafka **Topic**. Consumers immediately read from that topic and process the data in real-time.", "instructions": "## Task: Pub/Sub Architecture\n1. Simulate a simple Publisher/Subscriber model.\n2. Create a `Topic` class that holds subscribers.\n3. When `publish` is called, it iterates through all subscribers and calls their `receive` method.", "starterCode": "class Topic:\n    def __init__(self, name):\n        self.name = name\n        self.subscribers = []\n        \n    def subscribe(self, sub):\n        self.subscribers.___(sub)\n        \n    def publish(self, message):\n        for sub in self.___:\n            sub.___(message)\n\nclass Consumer:\n    def __init__(self, name):\n        self.name = name\n        \n    def receive(self, message):\n        print(f\"{self.name} processed event: {message}\")\n\nclicks_topic = Topic(\"UserClicks\")\nclicks_topic.subscribe(Consumer(\"AnalyticsDB\"))\nclicks_topic.subscribe(Consumer(\"FraudDetection\"))\n\nclicks_topic.publish(\"User 99 clicked Checkout\")", "solution": "class Topic:\n    def __init__(self, name):\n        self.name = name\n        self.subscribers = []\n        \n    def subscribe(self, sub):\n        self.subscribers.append(sub)\n        \n    def publish(self, message):\n        for sub in self.subscribers:\n            sub.receive(message)\n\nclass Consumer:\n    def __init__(self, name):\n        self.name = name\n        \n    def receive(self, message):\n        print(f\"{self.name} processed event: {message}\")\n\nclicks_topic = Topic(\"UserClicks\")\nclicks_topic.subscribe(Consumer(\"AnalyticsDB\"))\nclicks_topic.subscribe(Consumer(\"FraudDetection\"))\n\nclicks_topic.publish(\"User 99 clicked Checkout\")", "hint": "append() to add. Loop over self.subscribers. Call sub.receive(message).", "rubric": "Both AnalyticsDB and FraudDetection process the event when published."}
    ]
}

def apply_lessons(tracks_dir):
    from rebuild_curriculum import track_courses
    total = 0
    for track_name, levels in track_courses.items():
        safe_name = track_name.lower().replace(" ", "_").replace("&", "").replace("__", "_") + ".json"
        filepath = os.path.join(tracks_dir, safe_name)
        if not os.path.exists(filepath): continue
        with open(filepath, 'r', encoding='utf-8') as f:
            track_data = json.load(f)
        updated = False
        for course_name in track_data:
            if course_name in LESSONS_BATCH18:
                track_data[course_name]['lessons'] = LESSONS_BATCH18[course_name]
                updated = True
                total += len(LESSONS_BATCH18[course_name])
        if updated:
            with open(filepath, 'w', encoding='utf-8') as f:
                json.dump(track_data, f, indent=2, ensure_ascii=False)
    print(f'Batch 18: Applied {total} lessons')
    os.system('python build_courses.py')

if __name__ == '__main__':
    apply_lessons(os.path.join('curriculum', 'tracks'))
