"""
Batch 20: AI Integrations, Go Backend, Cloud Operators
"""
import json, os

LESSONS_BATCH20 = {
    # ─── AGENTIC AI & AUTOMATION ───
    "MCP Intro": [
        {"title": "Model Context Protocol", "theory": "## Connecting AI to Tools\nThe Model Context Protocol (MCP) is an open standard that enables AI models to securely connect to external data sources and tools.\n\nInstead of hardcoding every integration (like Slack, GitHub, Database) directly into an AI, MCP provides a universal bridge. The AI connects to an MCP Server, which handles the specific API calls.", "instructions": "## Task: The Protocol Bridge\n1. Identify the 3 main components of the MCP architecture.\n2. Create a dictionary matching them: 'MCP Client', 'MCP Server', 'External Data Source'.", "starterCode": "mcp_architecture = {\n    'The AI application (like Claude Desktop or an Agent)': '___',\n    'The bridge that translates standard MCP requests into specific API calls': '___',\n    'The actual system (like GitHub or a SQL database)': '___'\n}\n\nfor desc, component in mcp_architecture.items():\n    print(f\"{component:25} -> {desc}\")", "solution": "mcp_architecture = {\n    'The AI application (like Claude Desktop or an Agent)': 'MCP Client',\n    'The bridge that translates standard MCP requests into specific API calls': 'MCP Server',\n    'The actual system (like GitHub or a SQL database)': 'External Data Source'\n}\n\nfor desc, component in mcp_architecture.items():\n    print(f\"{component:25} -> {desc}\")", "hint": "Client is the AI. Server is the bridge. External Data Source is the system.", "rubric": "Architecture components correctly mapped to their descriptions."}
    ],
    "ReAct Prompting": [
        {"title": "Reasoning and Acting", "theory": "## Think, Then Act\nReAct (Reasoning and Acting) is a prompting framework that forces the LLM to explain its thought process *before* it takes an action.\n\n`Thought: I need to find the capital of France.`\n`Action: Search[Capital of France]`\n`Observation: Paris is the capital.`\n`Thought: Now I have the answer.`\n`Final Answer: The capital is Paris.`", "instructions": "## Task: ReAct Parser\n1. Write a function that parses a ReAct output string.\n2. Extract the 'Thought' and the 'Action'.", "starterCode": "def parse_react(text):\n    lines = text.split('\\n')\n    thought = None\n    action = None\n    \n    for line in lines:\n        if line.startswith('Thought: '):\n            thought = line.split('Thought: ')[___]\n        elif line.startswith('Action: '):\n            action = line.split('Action: ')[___]\n            \n    return thought, action\n\noutput = \"\"\"Thought: I need to check the weather in Tokyo.\nAction: WeatherAPI[Tokyo]\nObservation: 75F and sunny.\"\"\"\n\nt, a = parse_react(output)\nprint(\"Extracted Thought:\", t)\nprint(\"Extracted Action:\", a)", "solution": "def parse_react(text):\n    lines = text.split('\\n')\n    thought = None\n    action = None\n    \n    for line in lines:\n        if line.startswith('Thought: '):\n            thought = line.split('Thought: ')[1]\n        elif line.startswith('Action: '):\n            action = line.split('Action: ')[1]\n            \n    return thought, action\n\noutput = \"\"\"Thought: I need to check the weather in Tokyo.\nAction: WeatherAPI[Tokyo]\nObservation: 75F and sunny.\"\"\"\n\nt, a = parse_react(output)\nprint(\"Extracted Thought:\", t)\nprint(\"Extracted Action:\", a)", "hint": "Use index [1] to get the second part of the split string.", "rubric": "Successfully extracts 'I need to check the weather in Tokyo.' and 'WeatherAPI[Tokyo]'."}
    ],
    "MCP Servers": [
        {"title": "Building an MCP Server", "theory": "## Exposing Tools\nAn MCP Server exposes 'Resources', 'Prompts', and 'Tools' to the MCP Client.\n\n- **Resources**: Static data (e.g., read a file).\n- **Prompts**: Reusable prompt templates.\n- **Tools**: Functions the AI can execute (e.g., run a bash command, query a database).", "instructions": "## Task: Tool Definition\n1. Define a mock MCP Tool in JSON format.\n2. The tool is named 'calculator', it takes two 'number' inputs (a and b), and returns a number.", "starterCode": "import json\n\nmock_tool_definition = {\n    \"name\": \"calculator\",\n    \"description\": \"Adds two numbers together.\",\n    \"inputSchema\": {\n        \"type\": \"object\",\n        \"properties\": {\n            \"a\": {\"type\": \"___\"},\n            \"b\": {\"type\": \"___\"}\n        },\n        \"required\": [\"a\", \"b\"]\n    }\n}\n\nprint(json.dumps(mock_tool_definition, indent=2))", "solution": "import json\n\nmock_tool_definition = {\n    \"name\": \"calculator\",\n    \"description\": \"Adds two numbers together.\",\n    \"inputSchema\": {\n        \"type\": \"object\",\n        \"properties\": {\n            \"a\": {\"type\": \"number\"},\n            \"b\": {\"type\": \"number\"}\n        },\n        \"required\": [\"a\", \"b\"]\n    }\n}\n\nprint(json.dumps(mock_tool_definition, indent=2))", "hint": "The type should be 'number'.", "rubric": "Tool schema is correctly defined with 'number' types."}
    ],
    "Zapier Basics": [
        {"title": "No-Code Automation", "theory": "## Triggers and Actions\nZapier connects thousands of apps without writing code.\n\nA Zap consists of:\n- **Trigger**: The event that starts the automation (e.g., \"When a new row is added to Google Sheets\").\n- **Action(s)**: What happens next (e.g., \"Send a message in Slack\").", "instructions": "## Task: Mock Zap Runner\n1. Simulate a Zap.\n2. When a trigger event occurs, execute all actions in order.", "starterCode": "class MockZap:\n    def __init__(self, trigger_name):\n        self.trigger = trigger_name\n        self.actions = []\n        \n    def add_action(self, action_func):\n        self.actions.___(action_func)\n        \n    def run(self, data):\n        print(f\"--- Zap Triggered by: {self.trigger} ---\")\n        print(f\"Data: {data}\")\n        for action in self.___:\n            action(data)\n\ndef send_slack(data):\n    print(f\"[Slack] New Lead: {data['name']}\")\n\ndef add_to_crm(data):\n    print(f\"[CRM] Added {data['name']} to Sales Pipeline.\")\n\nzap = MockZap(\"New Google Sheet Row\")\nzap.add_action(___)\nzap.add_action(___)\n\n# Trigger event happens\nzap.run({'name': 'Alice Smith', 'email': 'alice@example.com'})", "solution": "class MockZap:\n    def __init__(self, trigger_name):\n        self.trigger = trigger_name\n        self.actions = []\n        \n    def add_action(self, action_func):\n        self.actions.append(action_func)\n        \n    def run(self, data):\n        print(f\"--- Zap Triggered by: {self.trigger} ---\")\n        print(f\"Data: {data}\")\n        for action in self.actions:\n            action(data)\n\ndef send_slack(data):\n    print(f\"[Slack] New Lead: {data['name']}\")\n\ndef add_to_crm(data):\n    print(f\"[CRM] Added {data['name']} to Sales Pipeline.\")\n\nzap = MockZap(\"New Google Sheet Row\")\nzap.add_action(send_slack)\nzap.add_action(add_to_crm)\n\n# Trigger event happens\nzap.run({'name': 'Alice Smith', 'email': 'alice@example.com'})", "hint": "append action_func. Loop over self.actions. Pass send_slack and add_to_crm.", "rubric": "Zap successfully triggers the Slack and CRM functions in order."}
    ],
    "Custom Webhooks": [
        {"title": "Connecting to APIs", "theory": "## Webhooks Overview\nWebhooks are automated messages sent from apps when something happens. They have a payload (usually JSON) and are sent to a unique URL.", "instructions": "## Task: Handle Incoming Webhook\n1. Write a function that acts as a webhook receiver.\n2. It must verify that the payload contains an 'event_type'.", "starterCode": "def handle_webhook(payload):\n    if '___' not in payload:\n        return \"Error: Missing event type\"\n        \n    event = payload['___']\n    if event == 'user_signup':\n        return \"Processed new user!\"\n    else:\n        return f\"Ignored event: {event}\"\n\nprint(handle_webhook({'event_type': 'user_signup', 'email': 'test@test.com'}))\nprint(handle_webhook({'data': 'no event type'}))", "solution": "def handle_webhook(payload):\n    if 'event_type' not in payload:\n        return \"Error: Missing event type\"\n        \n    event = payload['event_type']\n    if event == 'user_signup':\n        return \"Processed new user!\"\n    else:\n        return f\"Ignored event: {event}\"\n\nprint(handle_webhook({'event_type': 'user_signup', 'email': 'test@test.com'}))\nprint(handle_webhook({'data': 'no event type'}))", "hint": "Check for 'event_type'.", "rubric": "Correctly processes the signup and rejects the missing type."}
    ],
    "Enterprise AI Bots": [
        {"title": "Internal Knowledge Base", "theory": "## RAG in the Enterprise\nEnterprises don't want to upload their secret documents to public AI models. They build internal RAG pipelines using private vector databases.", "instructions": "## Task: Document Access Control\n1. Before returning a RAG document, verify the user has the correct role.", "starterCode": "docs = {\n    'doc1': {'text': 'Company Holiday Schedule', 'required_role': 'employee'},\n    'doc2': {'text': 'Q3 Financial Projections', 'required_role': 'exec'}\n}\n\ndef rag_search(doc_id, user_role):\n    doc = docs.get(doc_id)\n    if not doc:\n        return \"Doc not found\"\n        \n    if doc['required_role'] == 'exec' and user_role != '___':\n        return \"Access Denied\"\n        \n    return doc['text']\n\nprint(\"Employee asking for Q3:\", rag_search('doc2', 'employee'))\nprint(\"Exec asking for Q3:\", rag_search('doc2', 'exec'))", "solution": "docs = {\n    'doc1': {'text': 'Company Holiday Schedule', 'required_role': 'employee'},\n    'doc2': {'text': 'Q3 Financial Projections', 'required_role': 'exec'}\n}\n\ndef rag_search(doc_id, user_role):\n    doc = docs.get(doc_id)\n    if not doc:\n        return \"Doc not found\"\n        \n    if doc['required_role'] == 'exec' and user_role != 'exec':\n        return \"Access Denied\"\n        \n    return doc['text']\n\nprint(\"Employee asking for Q3:\", rag_search('doc2', 'employee'))\nprint(\"Exec asking for Q3:\", rag_search('doc2', 'exec'))", "hint": "Check if user_role != 'exec'.", "rubric": "Access is denied to the employee and granted to the exec."}
    ],
    "Voice AI Agents": [
        {"title": "Speech-to-Text Pipelines", "theory": "## STT -> LLM -> TTS\nA Voice AI consists of:\n1. **Speech-to-Text (STT)**: Whisper converts audio to text.\n2. **LLM**: Processes text and generates a response.\n3. **Text-to-Speech (TTS)**: ElevenLabs converts response text back to audio.", "instructions": "## Task: Voice Pipeline Mock\n1. Simulate the three steps of a voice agent.", "starterCode": "def stt_mock(audio_bytes):\n    return \"What time is it?\"\n    \ndef llm_mock(text):\n    return \"It is 3 PM.\"\n    \ndef tts_mock(text):\n    return f\"[AUDIO DATA of '{text}']\"\n\ndef run_voice_agent(audio_input):\n    user_text = ___(audio_input)\n    ai_response = ___(user_text)\n    audio_output = ___(ai_response)\n    return audio_output\n\nprint(run_voice_agent(\"[USER AUDIO BYTES]\"))", "solution": "def stt_mock(audio_bytes):\n    return \"What time is it?\"\n    \ndef llm_mock(text):\n    return \"It is 3 PM.\"\n    \ndef tts_mock(text):\n    return f\"[AUDIO DATA of '{text}']\"\n\ndef run_voice_agent(audio_input):\n    user_text = stt_mock(audio_input)\n    ai_response = llm_mock(user_text)\n    audio_output = tts_mock(ai_response)\n    return audio_output\n\nprint(run_voice_agent(\"[USER AUDIO BYTES]\"))", "hint": "Call stt, then llm, then tts in order.", "rubric": "Successfully simulates the STT -> LLM -> TTS flow."}
    ],
    # ─── BACKEND (GO) ───
    "Structs & Interfaces": [
        {"title": "Object-Oriented Go?", "theory": "## Structs over Classes\nGo doesn't have classes. It has `structs` (custom data types) and `interfaces` (behavior contracts).\n\n```go\ntype Animal interface {\n    Speak() string\n}\n\ntype Dog struct {}\nfunc (d Dog) Speak() string { return \"Woof\" }\n```", "instructions": "## Task: Implement an Interface\n1. Create a `Circle` struct.\n2. Implement the `Shape` interface's `Area` method.", "starterCode": "// Go pseudocode syntax for understanding\ntype Shape interface {\n    Area() float64\n}\n\ntype Circle struct {\n    Radius float64\n}\n\n// Method receiver attached to Circle\nfunc (c ___) Area() float64 {\n    return 3.14 * c.Radius * c.Radius\n}\n\nfunc main() {\n    c := Circle{Radius: 5}\n    print(\"Area:\", c.Area())\n}\n\n// PYTHON SIMULATOR\nclass Circle:\n    def __init__(self, r): self.Radius = r\n    def Area(self): return 3.14 * self.Radius ** 2\n\nprint(\"Python output:\", Circle(5).Area())", "solution": "// Go pseudocode syntax for understanding\ntype Shape interface {\n    Area() float64\n}\n\ntype Circle struct {\n    Radius float64\n}\n\n// Method receiver attached to Circle\nfunc (c Circle) Area() float64 {\n    return 3.14 * c.Radius * c.Radius\n}\n\nfunc main() {\n    c := Circle{Radius: 5}\n    print(\"Area:\", c.Area())\n}\n\n// PYTHON SIMULATOR\nclass Circle:\n    def __init__(self, r): self.Radius = r\n    def Area(self): return 3.14 * self.Radius ** 2\n\nprint(\"Python output:\", Circle(5).Area())", "hint": "The method receiver needs the struct name 'Circle'.", "rubric": "Go pseudocode demonstrates a proper method receiver for the interface."}
    ],
    "Go Web Servers": [
        {"title": "net/http", "theory": "## Built-in Web Servers\nGo's standard library `net/http` is incredibly powerful. You often don't even need a framework to build a fast web server.", "instructions": "## Task: Simple HTTP Handler\n1. Write a basic HTTP handler function that writes 'Hello Go' to the response.", "starterCode": "/*\npackage main\n\nimport (\n    \"fmt\"\n    \"net/http\"\n)\n\nfunc handler(w http.ResponseWriter, r *http.Request) {\n    fmt.Fprintf(___, \"Hello Go\")\n}\n\nfunc main() {\n    http.HandleFunc(\"/\", ___)\n    http.ListenAndServe(\":8080\", nil)\n}\n*/\nprint(\"Review the Go code in comments!\")", "solution": "/*\npackage main\n\nimport (\n    \"fmt\"\n    \"net/http\"\n)\n\nfunc handler(w http.ResponseWriter, r *http.Request) {\n    fmt.Fprintf(w, \"Hello Go\")\n}\n\nfunc main() {\n    http.HandleFunc(\"/\", handler)\n    http.ListenAndServe(\":8080\", nil)\n}\n*/\nprint(\"Review the Go code in comments!\")", "hint": "Use 'w' for ResponseWriter and pass 'handler' to HandleFunc.", "rubric": "Go pseudocode correctly defines a basic net/http handler."}
    ],
    # ─── CLOUD & DEVOPS ───
    "Kubernetes Basics": [
        {"title": "Orchestrating Containers", "theory": "## Managing Docker at Scale\nIf you have 1 container, use Docker. If you have 10,000 containers across 50 servers, use Kubernetes (K8s).\n\n- **Pod**: The smallest unit in K8s (usually contains 1 container).\n- **Deployment**: Manages Pods (e.g., \"Make sure exactly 3 copies of my API pod are always running\").\n- **Service**: Gives a stable IP address so other parts of the app can talk to the Pods.", "instructions": "## Task: YAML Matcher\n1. Match the K8s object type to its role.\n2. Roles: 'Pod', 'Deployment', 'Service'", "starterCode": "k8s_objects = {\n    'Provides a stable network IP for internal communication': '___',\n    'Ensures exactly N replicas are running at all times': '___',\n    'The actual running container(s)': '___'\n}\n\nfor desc, obj in k8s_objects.items():\n    print(f\"{obj:15}: {desc}\")", "solution": "k8s_objects = {\n    'Provides a stable network IP for internal communication': 'Service',\n    'Ensures exactly N replicas are running at all times': 'Deployment',\n    'The actual running container(s)': 'Pod'\n}\n\nfor desc, obj in k8s_objects.items():\n    print(f\"{obj:15}: {desc}\")", "hint": "Service for Network. Deployment for Replicas. Pod for Container.", "rubric": "Objects correctly mapped to their roles."}
    ]
}

def apply_lessons(tracks_dir):
    from rebuild_curriculum import track_courses
    total = 0
    for track_name, levels in track_courses.items():
        safe_name = track_name.lower().replace(" ", "_").replace("&", "").replace("__", "_") + ".json"
        filepath = os.path.join(tracks_dir, safe_name)
        if not os.path.exists(filepath): continue
        with open(filepath, 'r', encoding='utf-8') as f:
            track_data = json.load(f)
        updated = False
        for course_name in track_data:
            if course_name in LESSONS_BATCH20:
                track_data[course_name]['lessons'] = LESSONS_BATCH20[course_name]
                updated = True
                total += len(LESSONS_BATCH20[course_name])
        if updated:
            with open(filepath, 'w', encoding='utf-8') as f:
                json.dump(track_data, f, indent=2, ensure_ascii=False)
    print(f'Batch 20: Applied {total} lessons')
    os.system('python build_courses.py')

if __name__ == '__main__':
    apply_lessons(os.path.join('curriculum', 'tracks'))
