"""
Batch 9: System Design, Serverless, Auth, State Management
"""
import json, os

LESSONS_BATCH9 = {
    # ─── SYSTEM DESIGN & ARCHITECTURE ───
    "Message Queues": [
        {"title": "Decoupling Systems", "theory": "## Asynchronous Messaging\nMessage queues (like RabbitMQ, Kafka, AWS SQS) allow systems to communicate asynchronously.\n\nInstead of Service A calling Service B directly (which fails if B is down), Service A puts a message on the queue. Service B reads it when ready.\n\nBenefits:\n- **Decoupling**: Services don't need to know about each other.\n- **Scalability**: Add more consumers if the queue gets too long.\n- **Reliability**: Messages aren't lost if a service crashes.", "instructions": "## Task: Message Queue Simulator\n1. Create a `MessageQueue` class with `publish` and `consume` methods\n2. Use a standard list to represent the queue (FIFO)\n3. Publish 3 tasks and consume them sequentially", "starterCode": "class MessageQueue:\n    def __init__(self):\n        self.queue = []\n        \n    def publish(self, message):\n        self.queue.___(message)\n        print(f\"Published: {message}\")\n        \n    def consume(self):\n        if not self.queue:\n            return None\n        return self.queue.___(0)\n\nmq = MessageQueue()\nmq.publish(\"Process Order #123\")\nmq.publish(\"Send Email to Alice\")\nmq.publish(\"Generate PDF Report\")\n\nprint(\"\\n--- Consumer Worker ---\")\nwhile True:\n    task = mq.consume()\n    if task is None:\n        print(\"No more tasks!\")\n        break\n    print(f\"Working on: {task}\")", "solution": "class MessageQueue:\n    def __init__(self):\n        self.queue = []\n        \n    def publish(self, message):\n        self.queue.append(message)\n        print(f\"Published: {message}\")\n        \n    def consume(self):\n        if not self.queue:\n            return None\n        return self.queue.pop(0)\n\nmq = MessageQueue()\nmq.publish(\"Process Order #123\")\nmq.publish(\"Send Email to Alice\")\nmq.publish(\"Generate PDF Report\")\n\nprint(\"\\n--- Consumer Worker ---\")\nwhile True:\n    task = mq.consume()\n    if task is None:\n        print(\"No more tasks!\")\n        break\n    print(f\"Working on: {task}\")", "hint": ".append() adds to end. .pop(0) removes from front.", "rubric": "Messages published, then consumed in the same order (FIFO)."},
        {"title": "CAP Theorem", "theory": "## Consistency, Availability, Partition Tolerance\nThe CAP Theorem states that a distributed database can only guarantee two of these three characteristics:\n\n1. **Consistency**: All nodes see the same data at the same time.\n2. **Availability**: Every request gets a response (success/failure).\n3. **Partition Tolerance**: The system continues to operate despite network failures between nodes.\n\nSince networks *will* fail (P is required), you must choose between Consistency (CP) or Availability (AP).", "instructions": "## Task: CAP Matcher\n1. Match databases to their typical CAP categorization\n2. Match: 'MongoDB' (CP), 'Cassandra' (AP), 'Relational/MySQL' (CA - technically single node)\n3. Print the categorizations", "starterCode": "databases = {\n    'MongoDB (Default)': '___',          # Chooses Consistency over Availability during partitions\n    'Cassandra': '___',                  # Chooses Availability over Consistency (eventual consistency)\n    'MySQL (Single Node)': '___'         # Doesn't handle partitions natively\n}\n\nfor db, category in databases.items():\n    print(f\"{db:22}: {category}\")", "solution": "databases = {\n    'MongoDB (Default)': 'CP',          # Chooses Consistency over Availability during partitions\n    'Cassandra': 'AP',                  # Chooses Availability over Consistency (eventual consistency)\n    'MySQL (Single Node)': 'CA'         # Doesn't handle partitions natively\n}\n\nfor db, category in databases.items():\n    print(f\"{db:22}: {category}\")", "hint": "MongoDB is CP. Cassandra is AP. MySQL single node is CA.", "rubric": "Databases matched to their CAP categories correctly."}
    ],
    # ─── CLOUD & DEVOPS ───
    "Serverless": [
        {"title": "What is Serverless?", "theory": "## Functions as a Service (FaaS)\nServerless (like AWS Lambda) means you write code, and the cloud provider handles the servers. You only pay for the milliseconds your code actually runs.\n\n```python\n# Standard AWS Lambda Handler\ndef lambda_handler(event, context):\n    user_id = event.get('userId')\n    return {\n        'statusCode': 200,\n        'body': f\"Hello, User {user_id}!\"\n    }\n```", "instructions": "## Task: Write a Lambda Function\n1. Implement `lambda_handler(event, context)`\n2. It should extract `action` and `amount` from the `event` dictionary\n3. Return a 200 status code and a success message in the body", "starterCode": "def lambda_handler(event, context):\n    action = event.get('___')\n    amount = event.get('___')\n    \n    # Simulate some logic\n    message = f\"Successfully processed {action} for ${amount}\"\n    \n    return {\n        'statusCode': ___,\n        'body': ___\n    }\n\nmock_event = {'action': 'refund', 'amount': 45.50}\nresponse = lambda_handler(mock_event, {})\nprint(response)", "solution": "def lambda_handler(event, context):\n    action = event.get('action')\n    amount = event.get('amount')\n    \n    # Simulate some logic\n    message = f\"Successfully processed {action} for ${amount}\"\n    \n    return {\n        'statusCode': 200,\n        'body': message\n    }\n\nmock_event = {'action': 'refund', 'amount': 45.50}\nresponse = lambda_handler(mock_event, {})\nprint(response)", "hint": "Extract 'action' and 'amount'. Return 200 status and the message.", "rubric": "Handler extracts data and returns proper dict format."}
    ],
    # ─── BACKEND ───
    "Authentication": [
        {"title": "JWT (JSON Web Tokens)", "theory": "## Stateless Authentication\nInstead of storing session IDs in a database, JWTs contain the user data inside the token itself, signed with a secret key.\n\nThree parts of a JWT:\n1. **Header**: Algorithm used\n2. **Payload**: The user data (e.g., `{\"user_id\": 42}`)\n3. **Signature**: Cryptographic proof the token wasn't altered", "instructions": "## Task: JWT Simulator\n1. Simulate creating a JWT by Base64 encoding a payload\n2. Use the `base64` library in Python\n3. Decode the token to read the payload", "starterCode": "import base64\nimport json\n\ndef create_token(payload_dict):\n    json_str = json.dumps(payload_dict)\n    # Encode to bytes, then base64, then decode back to string\n    b64_bytes = base64.b64encode(json_str.encode('utf-8'))\n    return b64_bytes.decode('utf-8')\n\ndef decode_token(token_str):\n    json_bytes = base64.b64decode(___)\n    json_str = json_bytes.___('utf-8')\n    return json.___(___)\n\npayload = {'user_id': 123, 'role': 'admin'}\ntoken = create_token(payload)\nprint(\"Generated Token:\", token)\n\ndecoded = decode_token(token)\nprint(\"Decoded Payload:\", decoded)", "solution": "import base64\nimport json\n\ndef create_token(payload_dict):\n    json_str = json.dumps(payload_dict)\n    # Encode to bytes, then base64, then decode back to string\n    b64_bytes = base64.b64encode(json_str.encode('utf-8'))\n    return b64_bytes.decode('utf-8')\n\ndef decode_token(token_str):\n    json_bytes = base64.b64decode(token_str)\n    json_str = json_bytes.decode('utf-8')\n    return json.loads(json_str)\n\npayload = {'user_id': 123, 'role': 'admin'}\ntoken = create_token(payload)\nprint(\"Generated Token:\", token)\n\ndecoded = decode_token(token)\nprint(\"Decoded Payload:\", decoded)", "hint": "Pass token_str to b64decode. Use .decode() to convert to string. json.loads() converts string to dict.", "rubric": "Token is encoded and decoded correctly back into a dictionary."}
    ],
    # ─── FRONTEND ───
    "State Management": [
        {"title": "Global State", "theory": "## Prop Drilling vs Global State\nWhen many components need the same data (like the logged-in user), passing it down as props is annoying (\"prop drilling\").\n\nGlobal State solutions (like Redux, Zustand, or React Context) store data outside the components so any component can access it directly.\n\n```javascript\n// Zustand example\nconst useStore = create((set) => ({\n  bears: 0,\n  increasePopulation: () => set((state) => ({ bears: state.bears + 1 })),\n}))\n```", "instructions": "## Task: Simple Global Store\n1. Create a Store class that holds state and listeners\n2. When state updates, call all listeners\n3. This simulates how Redux/Zustand works under the hood", "starterCode": "class Store {\n  constructor(initialState) {\n    this.state = initialState;\n    this.listeners = [];\n  }\n  \n  subscribe(listener) {\n    this.listeners.___(listener);\n  }\n  \n  setState(newState) {\n    this.state = { ...this.state, ...newState };\n    // Notify all listeners\n    this.listeners.forEach(listener => ___(this.state));\n  }\n}\n\nconst store = new Store({ user: null, theme: 'light' });\n\nstore.subscribe((state) => console.log(\"Component A sees:\", state.theme));\nstore.subscribe((state) => console.log(\"Component B sees user:\", state.user));\n\nconsole.log(\"Updating theme...\");\nstore.setState({ theme: 'dark' });\n\nconsole.log(\"Logging in user...\");\nstore.setState({ user: 'Alice' });", "solution": "class Store {\n  constructor(initialState) {\n    this.state = initialState;\n    this.listeners = [];\n  }\n  \n  subscribe(listener) {\n    this.listeners.push(listener);\n  }\n  \n  setState(newState) {\n    this.state = { ...this.state, ...newState };\n    // Notify all listeners\n    this.listeners.forEach(listener => listener(this.state));\n  }\n}\n\nconst store = new Store({ user: null, theme: 'light' });\n\nstore.subscribe((state) => console.log(\"Component A sees:\", state.theme));\nstore.subscribe((state) => console.log(\"Component B sees user:\", state.user));\n\nconsole.log(\"Updating theme...\");\nstore.setState({ theme: 'dark' });\n\nconsole.log(\"Logging in user...\");\nstore.setState({ user: 'Alice' });", "hint": "push() to add listener. listener(this.state) to call it.", "rubric": "Listeners are notified on every state change."}
    ],
    # ─── DATA STRUCTURES & ALGORITHMS ───
    "Dynamic Programming": [
        {"title": "Memoization", "theory": "## Remembering Past Results\nDynamic Programming (DP) optimizes recursive algorithms by storing the results of expensive function calls.\n\nFibonacci is the classic example:\n```python\n# Slow (O(2^n))\ndef fib(n):\n    if n <= 1: return n\n    return fib(n-1) + fib(n-2)\n```\nIf we compute `fib(5)`, we compute `fib(3)` multiple times. DP fixes this.", "instructions": "## Task: Memoized Fibonacci\n1. Implement Fibonacci using a dictionary (memo) to cache results\n2. Check if `n` is in `memo`. If so, return it.\n3. Otherwise, compute it, save it to `memo`, and return it", "starterCode": "def fib_memo(n, memo=None):\n    if memo is None: memo = {}\n    \n    if n in ___:\n        return memo[n]\n    if n <= 1:\n        return n\n        \n    # Compute and save\n    result = fib_memo(n-1, memo) + fib_memo(n-2, memo)\n    ___[n] = result\n    \n    return result\n\nprint(\"Fib(10):\", fib_memo(10))\nprint(\"Fib(50):\", fib_memo(50)) # Would take years without memoization!", "solution": "def fib_memo(n, memo=None):\n    if memo is None: memo = {}\n    \n    if n in memo:\n        return memo[n]\n    if n <= 1:\n        return n\n        \n    # Compute and save\n    result = fib_memo(n-1, memo) + fib_memo(n-2, memo)\n    memo[n] = result\n    \n    return result\n\nprint(\"Fib(10):\", fib_memo(10))\nprint(\"Fib(50):\", fib_memo(50)) # Would take years without memoization!", "hint": "Check `if n in memo`. Save to `memo[n] = result`.", "rubric": "Fib(50) computes instantly due to memoization."}
    ]
}

def apply_lessons(tracks_dir):
    from rebuild_curriculum import track_courses
    total = 0
    for track_name, levels in track_courses.items():
        safe_name = track_name.lower().replace(" ", "_").replace("&", "").replace("__", "_") + ".json"
        filepath = os.path.join(tracks_dir, safe_name)
        if not os.path.exists(filepath): continue
        with open(filepath, 'r', encoding='utf-8') as f:
            track_data = json.load(f)
        updated = False
        for course_name in track_data:
            if course_name in LESSONS_BATCH9:
                track_data[course_name]['lessons'] = LESSONS_BATCH9[course_name]
                updated = True
                total += len(LESSONS_BATCH9[course_name])
        if updated:
            with open(filepath, 'w', encoding='utf-8') as f:
                json.dump(track_data, f, indent=2, ensure_ascii=False)
    print(f'Batch 9: Applied {total} lessons')
    os.system('python build_courses.py')

if __name__ == '__main__':
    apply_lessons(os.path.join('curriculum', 'tracks'))
