"""
Batch 11: GraphQL, React Native, AI Vectors, Memory Systems
"""
import json, os

LESSONS_BATCH11 = {
    # ─── BACKEND ───
    "GraphQL": [
        {"title": "Intro to GraphQL", "theory": "## A Query Language for APIs\nUnlike REST (where you hit multiple URLs for different data), GraphQL exposes a single endpoint (e.g., `/graphql`).\n\n- The **Client** dictates exactly what data it wants.\n- Prevents **Over-fetching** (getting too much data) and **Under-fetching** (needing to make 5 requests to get everything).\n\n```graphql\nquery {\n  user(id: 1) {\n    name\n    posts {\n      title\n    }\n  }\n}\n```", "instructions": "## Task: The Problem with REST\n1. Define 'overfetching' as downloading more data than needed.\n2. Define 'underfetching' as needing multiple API calls to get enough data.\n3. Create a dictionary matching scenarios to these terms.", "starterCode": "graphql_benefits = {\n    'Fetching a User profile just to get their name, but getting 5MB of history too': '___',\n    'Calling /users, then /users/1/posts, then /posts/2/comments just to show a page': '___'\n}\n\nfor scenario, term in graphql_benefits.items():\n    print(f\"Scenario:\\n{scenario}\\n-> Problem: {term}\\n\")", "solution": "graphql_benefits = {\n    'Fetching a User profile just to get their name, but getting 5MB of history too': 'overfetching',\n    'Calling /users, then /users/1/posts, then /posts/2/comments just to show a page': 'underfetching'\n}\n\nfor scenario, term in graphql_benefits.items():\n    print(f\"Scenario:\\n{scenario}\\n-> Problem: {term}\\n\")", "hint": "Overfetching = too much data. Underfetching = too many requests.", "rubric": "Scenarios correctly matched to overfetching and underfetching."},
        {"title": "Schemas and Resolvers", "theory": "## How it Works\nOn the server, you define a **Schema** (the shape of the data) and **Resolvers** (functions that actually fetch the data).\n\n```javascript\n// 1. Schema\ntype Query {\n  hello: String\n}\n\n// 2. Resolver\nconst resolvers = {\n  Query: {\n    hello: () => 'Hello world!',\n  },\n};\n```", "instructions": "## Task: Write a Resolver\n1. You have a simulated database `mock_db`.\n2. Write a resolver function `get_user(id)` that returns the user dict.\n3. Return `None` if the user doesn't exist.", "starterCode": "mock_db = {\n    1: {'name': 'Alice', 'role': 'Admin'},\n    2: {'name': 'Bob', 'role': 'User'}\n}\n\ndef get_user_resolver(user_id):\n    # Return the user from mock_db or None\n    return mock_db.___(___)\n\n# Simulating a GraphQL Query: query { user(id: 1) { name } }\nresult = get_user_resolver(1)\nprint(\"User 1 Name:\", result['name'])\n\n# Simulating missing user\nprint(\"User 99:\", get_user_resolver(99))", "solution": "mock_db = {\n    1: {'name': 'Alice', 'role': 'Admin'},\n    2: {'name': 'Bob', 'role': 'User'}\n}\n\ndef get_user_resolver(user_id):\n    # Return the user from mock_db or None\n    return mock_db.get(user_id)\n\n# Simulating a GraphQL Query: query { user(id: 1) { name } }\nresult = get_user_resolver(1)\nprint(\"User 1 Name:\", result['name'])\n\n# Simulating missing user\nprint(\"User 99:\", get_user_resolver(99))", "hint": "Use the .get(key) dictionary method to safely fetch or return None.", "rubric": "Resolver safely fetches existing users and returns None for missing ones."}
    ],
    # ─── MOBILE (REACT NATIVE) ───
    "UI Components": [
        {"title": "View and Text", "theory": "## The Building Blocks\nIn React Native, you use native-backed components instead of HTML.\n\n- **`<View>`**: Like a `<div>`. The fundamental container. Used for layout (Flexbox), styling, and grouping.\n- **`<Text>`**: Like a `<span>` or `<p>`. You CANNOT put text directly inside a `<View>`, it MUST be inside a `<Text>` component.", "instructions": "## Task: Component Validations\n1. Analyze some simulated React Native code blocks.\n2. Determine if they are valid (True) or invalid (False).\n3. Remember: Text must be inside `<Text>`.", "starterCode": "validations = {\n    '<View>Hello World</View>': ___,\n    '<View><Text>Hello World</Text></View>': ___,\n    '<div><p>Hello</p></div>': ___  # This is React Native, not React Web!\n}\n\nfor code, is_valid in validations.items():\n    print(f\"Code: {code}\\nValid? {is_valid}\\n\")", "solution": "validations = {\n    '<View>Hello World</View>': False,\n    '<View><Text>Hello World</Text></View>': True,\n    '<div><p>Hello</p></div>': False  # This is React Native, not React Web!\n}\n\nfor code, is_valid in validations.items():\n    print(f\"Code: {code}\\nValid? {is_valid}\\n\")", "hint": "Text inside a View without <Text> is False. <div> is False in React Native.", "rubric": "Only the <View><Text> combination is marked as True."}
    ],
    "Local Storage": [
        {"title": "AsyncStorage", "theory": "## Saving Data on the Device\nReact Native uses `AsyncStorage` (or similar libraries) to save key-value data persistently on the phone.\n\nIt is **asynchronous** (returns a Promise), unlike `localStorage` on the web.\n\n```javascript\n// Saving\nawait AsyncStorage.setItem('@theme', 'dark');\n\n// Reading\nconst theme = await AsyncStorage.getItem('@theme');\n```", "instructions": "## Task: AsyncStorage Simulator\n1. Build a mock `AsyncStorage` class using Python's `async/await`.\n2. Implement `set_item(key, value)` and `get_item(key)`.", "starterCode": "import asyncio\n\nclass MockAsyncStorage:\n    def __init__(self):\n        self.storage = {}\n        \n    ___ def set_item(self, key, value):\n        # Simulate a small delay\n        await asyncio.sleep(0.1)\n        self.storage[key] = ___\n        \n    ___ def get_item(self, key):\n        await asyncio.sleep(0.1)\n        return self.storage.___(___)\n\nasync def main():\n    db = MockAsyncStorage()\n    ___ db.set_item('@token', 'xyz_123')\n    token = ___ db.get_item('@token')\n    print(\"Retrieved Token:\", token)\n\n# Run the async function (simulate React Native environment)\nasyncio.run(main())", "solution": "import asyncio\n\nclass MockAsyncStorage:\n    def __init__(self):\n        self.storage = {}\n        \n    async def set_item(self, key, value):\n        # Simulate a small delay\n        await asyncio.sleep(0.1)\n        self.storage[key] = value\n        \n    async def get_item(self, key):\n        await asyncio.sleep(0.1)\n        return self.storage.get(key)\n\nasync def main():\n    db = MockAsyncStorage()\n    await db.set_item('@token', 'xyz_123')\n    token = await db.get_item('@token')\n    print(\"Retrieved Token:\", token)\n\n# Run the async function (simulate React Native environment)\nasyncio.run(main())", "hint": "Use `async def` for functions and `await` when calling them. Use `.get(key)` for dictionary lookup.", "rubric": "Async functions implemented correctly and data is stored/retrieved."}
    ],
    # ─── AI ENGINEERING ───
    "Vector Databases": [
        {"title": "What are Embeddings?", "theory": "## Words to Numbers\nLLMs don't understand words; they understand numbers. We convert text into lists of numbers called **Embeddings** (or Vectors).\n\nWords with similar meanings will have vectors that are closer together in space.\n- `[0.1, 0.9]` might be 'Dog'\n- `[0.2, 0.8]` might be 'Cat'\n- `[0.9, -0.1]` might be 'Car'", "instructions": "## Task: Vector Similarity\n1. Calculate the similarity between a query vector and a list of database vectors.\n2. We will use a simple absolute difference sum (lower is more similar).\n3. Find the most similar vector to `[0.1, 0.9]`.", "starterCode": "def calculate_distance(vec1, vec2):\n    # Simple distance: sum of absolute differences\n    return abs(vec1[0] - vec2[0]) + abs(vec1[1] - vec2[1])\n\nquery = [0.1, 0.9]  # \"Dog\"\ndb = {\n    'Cat': [0.2, 0.8],\n    'Car': [0.9, -0.1],\n    'Fish': [0.3, 0.7]\n}\n\nbest_match = None\nmin_distance = float('inf')\n\nfor word, vector in db.items():\n    dist = ___(query, vector)\n    print(f\"Distance to {word}: {dist:.2f}\")\n    if dist < min_distance:\n        min_distance = dist\n        best_match = ___\n\nprint(f\"\\nMost similar to query: {best_match}\")", "solution": "def calculate_distance(vec1, vec2):\n    # Simple distance: sum of absolute differences\n    return abs(vec1[0] - vec2[0]) + abs(vec1[1] - vec2[1])\n\nquery = [0.1, 0.9]  # \"Dog\"\ndb = {\n    'Cat': [0.2, 0.8],\n    'Car': [0.9, -0.1],\n    'Fish': [0.3, 0.7]\n}\n\nbest_match = None\nmin_distance = float('inf')\n\nfor word, vector in db.items():\n    dist = calculate_distance(query, vector)\n    print(f\"Distance to {word}: {dist:.2f}\")\n    if dist < min_distance:\n        min_distance = dist\n        best_match = word\n\nprint(f\"\\nMost similar to query: {best_match}\")", "hint": "Call calculate_distance. Save the 'word' as the best_match.", "rubric": "Calculates distances and correctly identifies Cat as the most similar."},
        {"title": "Using Vector DBs", "theory": "## Searching Vectors\nOnce you have embeddings, you store them in a **Vector Database** (like Pinecone, Milvus, or ChromaDB).\n\nWhen a user asks a question:\n1. Convert the question into a vector.\n2. Ask the Vector DB to find the most similar vectors.\n3. Return the text associated with those vectors.", "instructions": "## Task: Vector Search Pipeline\n1. Build a mock vector search pipeline.\n2. Take a user query, \"embed\" it, and search the mock database.", "starterCode": "class MockPinecone:\n    def __init__(self):\n        # Text attached to vectors\n        self.data = [\n            (\"To reset your password, click 'Forgot Password'.\", [0.8, 0.1]),\n            (\"Our refund policy is 30 days.\", [0.2, 0.9])\n        ]\n        \n    def search(self, query_vector):\n        # Mock search: Return the first item if vector[0] is high, else second\n        if query_vector[0] > 0.5:\n            return self.data[0][0]\n        return self.data[1][0]\n\ndef embed_text(text):\n    # Mock embedding\n    if 'password' in text.lower(): return [0.9, 0.0]\n    if 'refund' in text.lower(): return [0.1, 0.8]\n    return [0.5, 0.5]\n\ndb = MockPinecone()\n\nuser_question = \"How do I get a refund?\"\nvector = ___(user_question)\nanswer = db.___(vector)\n\nprint(f\"Q: {user_question}\")\nprint(f\"Found Info: {answer}\")", "solution": "class MockPinecone:\n    def __init__(self):\n        # Text attached to vectors\n        self.data = [\n            (\"To reset your password, click 'Forgot Password'.\", [0.8, 0.1]),\n            (\"Our refund policy is 30 days.\", [0.2, 0.9])\n        ]\n        \n    def search(self, query_vector):\n        # Mock search: Return the first item if vector[0] is high, else second\n        if query_vector[0] > 0.5:\n            return self.data[0][0]\n        return self.data[1][0]\n\ndef embed_text(text):\n    # Mock embedding\n    if 'password' in text.lower(): return [0.9, 0.0]\n    if 'refund' in text.lower(): return [0.1, 0.8]\n    return [0.5, 0.5]\n\ndb = MockPinecone()\n\nuser_question = \"How do I get a refund?\"\nvector = embed_text(user_question)\nanswer = db.search(vector)\n\nprint(f\"Q: {user_question}\")\nprint(f\"Found Info: {answer}\")", "hint": "Call embed_text on the question. Call db.search on the vector.", "rubric": "Pipeline successfully retrieves the refund policy based on the mock vector search."}
    ],
    # ─── AGENTIC AI ───
    "Memory Systems": [
        {"title": "Agent Memory", "theory": "## Remembering Context\nAgents need memory to hold conversations. \n\n- **Short-term Memory**: The current chat history (often constrained by the LLM context window).\n- **Long-term Memory**: Saving important facts to a database (often a Vector DB) and retrieving them later.", "instructions": "## Task: Short-Term Chat Buffer\n1. Create a `ChatMemory` class that stores a list of messages.\n2. Implement an `add_message(role, content)` method.\n3. Add a limit so it only keeps the last 3 messages (so we don't overflow the LLM token limit).", "starterCode": "class ChatMemory:\n    def __init__(self, limit=3):\n        self.messages = []\n        self.limit = limit\n        \n    def add_message(self, role, content):\n        self.messages.append({'role': role, 'content': content})\n        # Ensure we don't exceed the limit by keeping only the last N items\n        if len(self.messages) > self.___:\n            self.messages = self.messages[-self.___:]\n            \n    def show(self):\n        for m in self.messages:\n            print(f\"[{m['role'].upper()}] {m['content']}\")\n\nmemory = ChatMemory(limit=2)\nmemory.add_message('user', 'Hi')\nmemory.add_message('assistant', 'Hello, how can I help?')\nmemory.add_message('user', 'What is your name?')\n\n# The first 'user: Hi' message should be forgotten\nmemory.show()", "solution": "class ChatMemory:\n    def __init__(self, limit=3):\n        self.messages = []\n        self.limit = limit\n        \n    def add_message(self, role, content):\n        self.messages.append({'role': role, 'content': content})\n        # Ensure we don't exceed the limit by keeping only the last N items\n        if len(self.messages) > self.limit:\n            self.messages = self.messages[-self.limit:]\n            \n    def show(self):\n        for m in self.messages:\n            print(f\"[{m['role'].upper()}] {m['content']}\")\n\nmemory = ChatMemory(limit=2)\nmemory.add_message('user', 'Hi')\nmemory.add_message('assistant', 'Hello, how can I help?')\nmemory.add_message('user', 'What is your name?')\n\n# The first 'user: Hi' message should be forgotten\nmemory.show()", "hint": "Use self.limit. Python list slicing [-limit:] gets the last N elements.", "rubric": "Memory successfully truncates to the last 2 messages."}
    ]
}

def apply_lessons(tracks_dir):
    from rebuild_curriculum import track_courses
    total = 0
    for track_name, levels in track_courses.items():
        safe_name = track_name.lower().replace(" ", "_").replace("&", "").replace("__", "_") + ".json"
        filepath = os.path.join(tracks_dir, safe_name)
        if not os.path.exists(filepath): continue
        with open(filepath, 'r', encoding='utf-8') as f:
            track_data = json.load(f)
        updated = False
        for course_name in track_data:
            if course_name in LESSONS_BATCH11:
                track_data[course_name]['lessons'] = LESSONS_BATCH11[course_name]
                updated = True
                total += len(LESSONS_BATCH11[course_name])
        if updated:
            with open(filepath, 'w', encoding='utf-8') as f:
                json.dump(track_data, f, indent=2, ensure_ascii=False)
    print(f'Batch 11: Applied {total} lessons')
    os.system('python build_courses.py')

if __name__ == '__main__':
    apply_lessons(os.path.join('curriculum', 'tracks'))
