"""
Batch 27: AI Engineering Missing Content
"""
import json, os

LESSONS_BATCH27 = {
    # ─── AI ENGINEERING ───
    "Intro to LLMs": [
        {"title": "What is an LLM?", "theory": "## Next Word Predictors\\nLarge Language Models (LLMs) like GPT-4 or Llama 3 are fundamentally 'Next Word Predictors'.\\n\\nThey have been trained on massive amounts of text data to understand context, grammar, and facts, allowing them to predict what word should logically follow a given prompt.\\n\\nDespite their intelligence, they do not 'think' like humans do; they calculate probabilities.", "instructions": "## Task: Tokenizer Simulator\\n1. LLMs don't read words, they read 'tokens' (chunks of words).\\n2. Create a basic function that splits a sentence into tokens by spaces.", "starterCode": "def tokenize_sentence(sentence):\\n    # Split the sentence by spaces to simulate basic tokenization\\n    tokens = sentence.___()\\n    return tokens\\n\\ntext = \"The quick brown fox jumped over the lazy dog.\"\\nprint(\"Original text:\", text)\\nprint(\"Tokens:\", tokenize_sentence(text))", "solution": "def tokenize_sentence(sentence):\\n    # Split the sentence by spaces to simulate basic tokenization\\n    tokens = sentence.split()\\n    return tokens\\n\\ntext = \"The quick brown fox jumped over the lazy dog.\"\\nprint(\"Original text:\", text)\\nprint(\"Tokens:\", tokenize_sentence(text))", "hint": "Use the split() method.", "rubric": "Code correctly splits the sentence into a list of words."},
        {"title": "Temperature", "theory": "## Controlling Creativity\\nWhen calling an LLM API, you can set the `temperature` parameter (usually between 0.0 and 1.0).\\n\\n- **Low Temperature (0.1)**: Highly deterministic, repetitive, factual. Best for coding or data extraction.\\n- **High Temperature (0.9)**: Highly random, creative, diverse. Best for creative writing or brainstorming.", "instructions": "## Task: Temperature Selector\\n1. Based on the task description, return either '0.1' or '0.9' for the ideal temperature.", "starterCode": "def select_temperature(task):\\n    task = task.lower()\\n    if 'extract JSON' in task or 'code' in task:\\n        return ___\\n    elif 'write a poem' in task or 'brainstorm' in task:\\n        return ___\\n    return 0.5\\n\\nprint(\"Task: Extract JSON -> Temp:\", select_temperature('extract JSON data'))\\nprint(\"Task: Write a poem -> Temp:\", select_temperature('write a poem about the sea'))", "solution": "def select_temperature(task):\\n    task = task.lower()\\n    if 'extract JSON' in task or 'code' in task:\\n        return 0.1\\n    elif 'write a poem' in task or 'brainstorm' in task:\\n        return 0.9\\n    return 0.5\\n\\nprint(\"Task: Extract JSON -> Temp:\", select_temperature('extract JSON data'))\\nprint(\"Task: Write a poem -> Temp:\", select_temperature('write a poem about the sea'))", "hint": "Return 0.1 for data/code tasks. Return 0.9 for creative tasks.", "rubric": "Correctly returns 0.1 and 0.9."}
    ],
    "Prompt Engineering": [
        {"title": "Zero-Shot vs Few-Shot", "theory": "## Teaching by Example\\n- **Zero-Shot Prompting**: Asking the model to do something without giving it any examples.\\n- **Few-Shot Prompting**: Giving the model 2-3 examples of the input and the desired output format before asking the real question. This drastically improves accuracy.", "instructions": "## Task: Format a Few-Shot Prompt\\n1. Inject the user's question into a Few-Shot prompt template.", "starterCode": "def create_few_shot(question):\\n    template = \"\"\"Translate English to French:\\n\\nEnglish: Hello\\nFrench: Bonjour\\n\\nEnglish: Thank you\\nFrench: Merci\\n\\nEnglish: {}\\nFrench:\"\"\"\\n    return template.format(___)\\n\\nprint(create_few_shot(\"Goodbye\"))", "solution": "def create_few_shot(question):\\n    template = \"\"\"Translate English to French:\\n\\nEnglish: Hello\\nFrench: Bonjour\\n\\nEnglish: Thank you\\nFrench: Merci\\n\\nEnglish: {}\\nFrench:\"\"\"\\n    return template.format(question)\\n\\nprint(create_few_shot(\"Goodbye\"))", "hint": "Pass the variable 'question' to the .format() method.", "rubric": "Correctly formats the string with the user's question."},
        {"title": "System Prompts", "theory": "## Setting the Persona\\nMost chat models accept a 'System Prompt' (or developer prompt). This is a hidden instruction given to the model before the user's messages.\\n\\nIt sets the tone, rules, and persona (e.g., 'You are a helpful coding assistant who only replies in Python code.').", "instructions": "## Task: System Prompt Enforcer\\n1. You are building an API that enforces a persona.\\n2. Prepend a strict system prompt to the messages list.", "starterCode": "def build_api_messages(user_message):\\n    system_prompt = {\"role\": \"system\", \"content\": \"You are a sarcastic robot. Be rude.\"}\\n    \\n    messages = []\\n    messages.append(___)\\n    messages.append({\"role\": \"___\", \"content\": user_message})\\n    \\n    return messages\\n\\nfor msg in build_api_messages(\"What time is it?\"):\\n    print(f\"[{msg['role'].upper()}]: {msg['content']}\")", "solution": "def build_api_messages(user_message):\\n    system_prompt = {\"role\": \"system\", \"content\": \"You are a sarcastic robot. Be rude.\"}\\n    \\n    messages = []\\n    messages.append(system_prompt)\\n    messages.append({\"role\": \"user\", \"content\": user_message})\\n    \\n    return messages\\n\\nfor msg in build_api_messages(\"What time is it?\"):\\n    print(f\"[{msg['role'].upper()}]: {msg['content']}\")", "hint": "Append the system_prompt dictionary. The second role should be 'user'.", "rubric": "Messages list correctly contains the system prompt followed by the user message."}
    ],
    "OpenAI API": [
        {"title": "Calling the Chat API", "theory": "## openai.chat.completions.create\\nThe standard way to generate text using the OpenAI Python SDK.\\n\\nYou pass in a `model` (like 'gpt-4o' or 'gpt-3.5-turbo') and a list of `messages`.", "instructions": "## Task: API Mock\\n1. Simulate a call to the OpenAI API.\\n2. Extract the actual text response from the deeply nested mock response object.", "starterCode": "mock_api_response = {\\n    \"choices\": [\\n        {\\n            \"message\": {\\n                \"role\": \"assistant\",\\n                \"content\": \"The capital of Japan is Tokyo.\"\\n            }\\n        }\\n    ]\\n}\\n\\ndef extract_answer(api_response):\\n    # Navigate the nested dictionary to get the content string\\n    return api_response['___'][0]['___']['___']\\n\\nprint(\"Extracted:\", extract_answer(mock_api_response))", "solution": "mock_api_response = {\\n    \"choices\": [\\n        {\\n            \"message\": {\\n                \"role\": \"assistant\",\\n                \"content\": \"The capital of Japan is Tokyo.\"\\n            }\\n        }\\n    ]\\n}\\n\\ndef extract_answer(api_response):\\n    # Navigate the nested dictionary to get the content string\\n    return api_response['choices'][0]['message']['content']\\n\\nprint(\"Extracted:\", extract_answer(mock_api_response))", "hint": "['choices'][0]['message']['content']", "rubric": "Successfully extracts the content string."},
        {"title": "Streaming Responses", "theory": "## Typewriter Effect\\nWhen an LLM generates a long essay, the user shouldn't have to wait 10 seconds for the entire text to appear.\\n\\nBy setting `stream=True` in the API call, the API returns chunks of text as they are generated, allowing you to create a smooth 'typewriter' effect on the frontend.", "instructions": "## Task: Stream Processing\\n1. Simulate processing a streaming response.\\n2. Iterate through the chunks and print them on the same line to form a sentence.", "starterCode": "import time\\n\\nmock_stream = [\"Hello\", \", \", \"how \", \"are \", \"you \", \"today?\"]\\n\\ndef process_stream(stream):\\n    for chunk in stream:\\n        # end='' prevents a newline after every print\\n        # flush=True forces the terminal to output immediately\\n        print(___, end='', flush=True)\\n        time.sleep(0.2) # Simulate network delay\\n    print() # Final newline\\n\\nprint(\"Starting stream...\")\\nprocess_stream(mock_stream)", "solution": "import time\\n\\nmock_stream = [\"Hello\", \", \", \"how \", \"are \", \"you \", \"today?\"]\\n\\ndef process_stream(stream):\\n    for chunk in stream:\\n        # end='' prevents a newline after every print\\n        # flush=True forces the terminal to output immediately\\n        print(chunk, end='', flush=True)\\n        time.sleep(0.2) # Simulate network delay\\n    print() # Final newline\\n\\nprint(\"Starting stream...\")\\nprocess_stream(mock_stream)", "hint": "Print the 'chunk' variable.", "rubric": "Prints the full sentence smoothly."}
    ],
    "RAG Architecture": [
        {"title": "Retrieval Augmented Gen", "theory": "## Giving AI Memory\\nLLMs are frozen in time. GPT-4 doesn't know about yesterday's news or your company's internal wiki.\\n\\n**RAG** solves this.\\n1. **Retrieve**: Search your private database for documents relevant to the user's question.\\n2. **Augment**: Paste those documents into the prompt.\\n3. **Generate**: Ask the LLM to answer the question *using only the provided documents*.", "instructions": "## Task: The RAG Prompt\\n1. Simulate the 'Augment' phase.\\n2. Inject the retrieved document and the user's question into the final prompt template.", "starterCode": "def build_rag_prompt(user_query, retrieved_doc):\\n    template = \"\"\"You are a helpful assistant.\\n\\nUse the following context to answer the user's question. If the answer is not in the context, say \"I don't know\".\\n\\nContext:\\n{}\\n\\nQuestion: {}\\n\\nAnswer:\"\"\"\\n    \\n    return template.format(___, ___)\\n\\ndoc = \"The secret WiFi password is 'guest123'.\"\\nquery = \"What is the WiFi password?\"\\n\\nprint(build_rag_prompt(query, doc))", "solution": "def build_rag_prompt(user_query, retrieved_doc):\\n    template = \"\"\"You are a helpful assistant.\\n\\nUse the following context to answer the user's question. If the answer is not in the context, say \"I don't know\".\\n\\nContext:\\n{}\\n\\nQuestion: {}\\n\\nAnswer:\"\"\"\\n    \\n    return template.format(retrieved_doc, user_query)\\n\\ndoc = \"The secret WiFi password is 'guest123'.\"\\nquery = \"What is the WiFi password?\"\\n\\nprint(build_rag_prompt(query, doc))", "hint": "Pass retrieved_doc first, then user_query.", "rubric": "Correctly formats the prompt with the doc as context and query as the question."}
    ],
    "LangChain": [
        {"title": "Chaining Prompts", "theory": "## LLM Frameworks\\nLangChain is a popular Python framework that makes building complex AI pipelines easier.\\n\\nInstead of writing raw API calls, you can define 'Chains'. For example, you can chain PromptTemplate -> LLM -> OutputParser.", "instructions": "## Task: Simple Chain Simulator\\n1. Simulate a basic LangChain pipeline.\\n2. Pass data from the template step to the LLM step.", "starterCode": "class MockLLM:\\n    def invoke(self, prompt):\\n        return f\"[LLM Output for: {prompt}]\"\\n\\ndef simple_chain(topic):\\n    template = f\"Write a 1 sentence summary about {topic}.\"\\n    \\n    llm = MockLLM()\\n    \\n    # Pass the formatted template into the LLM invoke method\\n    result = llm.___(___)\\n    return result\\n\\nprint(simple_chain(\"Artificial Intelligence\"))", "solution": "class MockLLM:\\n    def invoke(self, prompt):\\n        return f\"[LLM Output for: {prompt}]\"\\n\\ndef simple_chain(topic):\\n    template = f\"Write a 1 sentence summary about {topic}.\"\\n    \\n    llm = MockLLM()\\n    \\n    # Pass the formatted template into the LLM invoke method\\n    result = llm.invoke(template)\\n    return result\\n\\nprint(simple_chain(\"Artificial Intelligence\"))", "hint": "llm.invoke(template)", "rubric": "Successfully calls the invoke method with the template."}
    ],
    "AI Agents": [
        {"title": "Tool Calling", "theory": "## Giving AI Hands\\nBy default, an LLM can only output text. To let it actually *do* things (like search Google or query a database), we use **Tool Calling** (also known as Function Calling).\\n\\nYou provide the LLM with a list of tools (functions) and their descriptions. If the LLM decides it needs to use a tool, it outputs a JSON object requesting the tool's execution.", "instructions": "## Task: Function Router\\n1. The LLM has requested a tool call. It returned a JSON object with the tool name and arguments.\\n2. Route the request to the correct Python function.", "starterCode": "def get_weather(location):\\n    return f\"It is sunny in {location}!\"\\n    \\ndef calculate_math(expression):\\n    return f\"{expression} = 42\"\\n\\ndef execute_tool(llm_tool_call):\\n    tool_name = llm_tool_call['name']\\n    args = llm_tool_call['arguments']\\n    \\n    if tool_name == 'get_weather':\\n        return ___(args['location'])\\n    elif tool_name == 'calculate_math':\\n        return ___(args['expression'])\\n    return \"Tool not found\"\\n\\n# Mock LLM Output\\ncall1 = {'name': 'get_weather', 'arguments': {'location': 'London'}}\\ncall2 = {'name': 'calculate_math', 'arguments': {'expression': '10 + 32'}}\\n\\nprint(execute_tool(call1))\\nprint(execute_tool(call2))", "solution": "def get_weather(location):\\n    return f\"It is sunny in {location}!\"\\n    \\ndef calculate_math(expression):\\n    return f\"{expression} = 42\"\\n\\ndef execute_tool(llm_tool_call):\\n    tool_name = llm_tool_call['name']\\n    args = llm_tool_call['arguments']\\n    \\n    if tool_name == 'get_weather':\\n        return get_weather(args['location'])\\n    elif tool_name == 'calculate_math':\\n        return calculate_math(args['expression'])\\n    return \"Tool not found\"\\n\\n# Mock LLM Output\\ncall1 = {'name': 'get_weather', 'arguments': {'location': 'London'}}\\ncall2 = {'name': 'calculate_math', 'arguments': {'expression': '10 + 32'}}\\n\\nprint(execute_tool(call1))\\nprint(execute_tool(call2))", "hint": "Call get_weather and calculate_math.", "rubric": "Properly routes the tool calls to their respective functions."}
    ]
}

def apply_lessons(tracks_dir):
    total = 0
    filepath = os.path.join(tracks_dir, 'ai_engineering.json')
    if os.path.exists(filepath):
        with open(filepath, 'r', encoding='utf-8') as f:
            track_data = json.load(f)
            
        updated = False
        for course_name in track_data:
            if course_name in LESSONS_BATCH27:
                track_data[course_name]['lessons'] = LESSONS_BATCH27[course_name]
                updated = True
                total += len(LESSONS_BATCH27[course_name])
                print(f"Applied {course_name} in ai_engineering.json")
                
        if updated:
            with open(filepath, 'w', encoding='utf-8') as f:
                json.dump(track_data, f, indent=2, ensure_ascii=False)
                
    print(f'Batch 27: Applied {total} lessons')
    os.system('python build_courses.py')

if __name__ == '__main__':
    apply_lessons(os.path.join('curriculum', 'tracks'))
