"""
Batch 22: Integrations, gRPC, Cloud, AI Models
"""
import json, os

LESSONS_BATCH22 = {
    # ─── AGENTIC AI & AUTOMATION ───
    "Database Integration": [
        {"title": "Text-to-SQL", "theory": "## Giving AI Data Access\\nInstead of teaching an AI to read millions of rows of data, you give it the ability to write SQL queries.\\n\\nFlow:\\n1. User asks: 'How many users joined yesterday?'\\n2. AI generates SQL: `SELECT COUNT(*) FROM users WHERE date = yesterday;`\\n3. Your system runs the SQL on the Database.\\n4. Your system gives the result (e.g., '145') back to the AI.\\n5. AI replies: '145 users joined yesterday!'", "instructions": "## Task: SQL Generation Mock\\n1. Simulate the Text-to-SQL flow.\\n2. Create a function that accepts a user question and returns a mock SQL query.", "starterCode": "def ai_text_to_sql(question):\\n    question = question.lower()\\n    if 'active users' in question:\\n        return \"SELECT COUNT(*) FROM users WHERE status = 'active';\"\\n    elif 'total revenue' in question:\\n        return \"___\"\\n    return \"SELECT 1;\"\n\ndef execute_query(sql):\n    if 'revenue' in sql.lower():\n        return \"$45,000\"\n    return \"842\"\n\nquestion = \"What is our total revenue?\"\nprint(f\"User: {question}\")\n\nsql = ai_text_to_sql(question)\nprint(f\"AI Generated SQL: {sql}\")\n\nresult = execute_query(sql)\nprint(f\"Database Result: {result}\")\nprint(f\"AI Final Answer: The total revenue is {result}!\")", "solution": "def ai_text_to_sql(question):\\n    question = question.lower()\\n    if 'active users' in question:\\n        return \"SELECT COUNT(*) FROM users WHERE status = 'active';\"\\n    elif 'total revenue' in question:\\n        return \"SELECT SUM(amount) FROM payments;\"\\n    return \"SELECT 1;\"\n\ndef execute_query(sql):\n    if 'revenue' in sql.lower() or 'payments' in sql.lower():\n        return \"$45,000\"\n    return \"842\"\n\nquestion = \"What is our total revenue?\"\nprint(f\"User: {question}\")\n\nsql = ai_text_to_sql(question)\nprint(f\"AI Generated SQL: {sql}\")\n\nresult = execute_query(sql)\nprint(f\"Database Result: {result}\")\nprint(f\"AI Final Answer: The total revenue is {result}!\")", "hint": "Return a mock SQL query like SELECT SUM(amount) FROM payments;", "rubric": "Code correctly returns a SQL string and completes the flow."}
    ],
    # ─── BACKEND ───
    "gRPC": [
        {"title": "High-Speed APIs", "theory": "## Faster than REST\\nREST uses HTTP/1.1 and JSON. JSON is heavy and slow to parse.\\n\\n**gRPC** (developed by Google) uses HTTP/2 and **Protocol Buffers** (Protobuf). Protobufs are binary, making them extremely fast and compact.\\n\\nWith gRPC, you define your service in a `.proto` file, and it automatically generates the server and client code for you in almost any language (Go, Python, Java, etc).", "instructions": "## Task: Protobuf vs JSON Size\\n1. Compare the string length of a JSON object vs a mock Binary representation.\\n2. Print the difference in size.", "starterCode": "import json\n\ndata = {\"id\": 104, \"name\": \"Alice\", \"active\": True}\n\n# Standard REST JSON string\njson_string = json.___(data)\njson_size = len(json_string)\n\n# Mock gRPC Protobuf binary (usually much smaller, just the raw data packed)\nmock_binary_string = \"104Alice1\"\nbinary_size = len(___)\n\nprint(f\"JSON Size: {json_size} bytes\")\nprint(f\"Protobuf Size: {binary_size} bytes\")\nprint(f\"gRPC is {json_size - binary_size} bytes smaller!\")", "solution": "import json\n\ndata = {\"id\": 104, \"name\": \"Alice\", \"active\": True}\n\n# Standard REST JSON string\njson_string = json.dumps(data)\njson_size = len(json_string)\n\n# Mock gRPC Protobuf binary (usually much smaller, just the raw data packed)\nmock_binary_string = \"104Alice1\"\nbinary_size = len(mock_binary_string)\n\nprint(f\"JSON Size: {json_size} bytes\")\nprint(f\"Protobuf Size: {binary_size} bytes\")\nprint(f\"gRPC is {json_size - binary_size} bytes smaller!\")", "hint": "Use json.dumps(). Check length of mock_binary_string.", "rubric": "Shows JSON is larger (around 40 bytes) compared to the mock binary (9 bytes)."}
    ],
    # ─── CLOUD & DEVOPS ───
    "Service Meshes": [
        {"title": "Managing Microservices", "theory": "## Istio & Linkerd\\nWhen you have 50 microservices talking to each other, how do you handle security, retries, and monitoring? Doing it in the code is messy.\\n\\nA **Service Mesh** injects a 'Sidecar Proxy' next to every single service. When Service A wants to talk to Service B, it actually talks to its own proxy, which securely routes the traffic to B's proxy.\\n\\nThis allows you to enforce mTLS (mutual encryption) without writing a single line of application code.", "instructions": "## Task: Sidecar Simulator\\n1. Simulate a request going through a sidecar proxy.\\n2. The proxy should intercept the request, encrypt it, and pass it to the destination.", "starterCode": "class SidecarProxy:\n    def __init__(self, service_name):\n        self.service_name = service_name\n        \n    def send(self, destination, data):\n        print(f\"[{self.service_name} Proxy] Encrypting data...\")\n        encrypted = f\"**{data}**\"\n        print(f\"[{self.service_name} Proxy] Sending to {destination.service_name} Proxy...\")\n        destination.___(encrypted)\n        \n    def receive(self, data):\n        print(f\"[{self.service_name} Proxy] Decrypting data...\")\n        decrypted = data.replace('*', '')\n        print(f\"[{self.service_name} App] Received: {decrypted}\")\n\napp_a = SidecarProxy(\"Service_A\")\napp_b = SidecarProxy(\"Service_B\")\n\napp_a.___(app_b, \"Hello Microservice!\")", "solution": "class SidecarProxy:\n    def __init__(self, service_name):\n        self.service_name = service_name\n        \n    def send(self, destination, data):\n        print(f\"[{self.service_name} Proxy] Encrypting data...\")\n        encrypted = f\"**{data}**\"\n        print(f\"[{self.service_name} Proxy] Sending to {destination.service_name} Proxy...\")\n        destination.receive(encrypted)\n        \n    def receive(self, data):\n        print(f\"[{self.service_name} Proxy] Decrypting data...\")\n        decrypted = data.replace('*', '')\n        print(f\"[{self.service_name} App] Received: {decrypted}\")\n\napp_a = SidecarProxy(\"Service_A\")\napp_b = SidecarProxy(\"Service_B\")\n\napp_a.send(app_b, \"Hello Microservice!\")", "hint": "destination.receive(encrypted) and app_a.send(app_b, ...)", "rubric": "Data successfully routes A Proxy -> B Proxy -> B App."}
    ],
    "Cloud Operators": [
        {"title": "K8s Operators", "theory": "## Automating Kubernetes\\nAn Operator is a software extension to Kubernetes that makes use of custom resources to manage applications and their components.\\n\\nInstead of a human reading a manual on how to backup a database, you write a K8s Operator that automatically knows how to backup, restore, and scale your specific database.", "instructions": "## Task: Operator Loop\\n1. An operator constantly runs a 'Reconciliation Loop'.\\n2. It checks the 'Desired State' against the 'Current State'.\\n3. Simulate an operator checking if a database has a backup.", "starterCode": "def reconcile_loop(current_state, desired_state):\n    print(\"--- Reconciliation Loop Running ---\")\n    \n    if current_state['needs_backup'] != desired_state['___']:\n        print(\"[Operator Action] Taking database backup to match desired state...\")\n        current_state['___'] = desired_state['___']\n        return \"Action Taken\"\n    \n    return \"No Action Needed\"\n\ndesired = {'needs_backup': False} # We don't want it to NEED a backup, we want it DONE\ncurrent = {'needs_backup': True}\n\nprint(reconcile_loop(current, desired))\n# Loop runs again later\nprint(reconcile_loop(current, desired))", "solution": "def reconcile_loop(current_state, desired_state):\n    print(\"--- Reconciliation Loop Running ---\")\n    \n    if current_state['needs_backup'] != desired_state['needs_backup']:\n        print(\"[Operator Action] Taking database backup to match desired state...\")\n        current_state['needs_backup'] = desired_state['needs_backup']\n        return \"Action Taken\"\n    \n    return \"No Action Needed\"\n\ndesired = {'needs_backup': False} # We don't want it to NEED a backup, we want it DONE\ncurrent = {'needs_backup': True}\n\nprint(reconcile_loop(current, desired))\n# Loop runs again later\nprint(reconcile_loop(current, desired))", "hint": "Key is 'needs_backup'.", "rubric": "First loop takes action, second loop takes no action."}
    ],
    # ─── AI ENGINEERING ───
    "Neural Networks Intro": [
        {"title": "The Perceptron", "theory": "## The Artificial Neuron\\nA Neural Network is made of interconnected Neurons (Perceptrons).\\n\\nA neuron takes Inputs, multiplies them by Weights, sums them up, and adds a Bias. It then passes the result through an Activation Function (like ReLU or Sigmoid).\\n\\n`Output = Activation( (Input1 * Weight1) + (Input2 * Weight2) + Bias )`", "instructions": "## Task: Code a Neuron\\n1. Implement a basic artificial neuron.\\n2. Inputs: [0.5, 0.8]. Weights: [0.2, -0.5]. Bias: 0.1.\\n3. Use a simple Step activation function (Return 1 if sum > 0, else 0).", "starterCode": "def step_activation(value):\n    return 1 if value > 0 else 0\n\ndef run_neuron(inputs, weights, bias):\n    # 1. Multiply inputs by weights and sum them\n    weighted_sum = (inputs[0] * weights[___]) + (inputs[1] * weights[___])\n    \n    # 2. Add bias\n    total = weighted_sum + ___\n    \n    # 3. Apply activation\n    return ___(total)\n\ni = [0.5, 0.8]\nw = [0.2, -0.5]\nb = 0.1\n\noutput = run_neuron(i, w, b)\nprint(\"Neuron Output:\", output)", "solution": "def step_activation(value):\n    return 1 if value > 0 else 0\n\ndef run_neuron(inputs, weights, bias):\n    # 1. Multiply inputs by weights and sum them\n    weighted_sum = (inputs[0] * weights[0]) + (inputs[1] * weights[1])\n    \n    # 2. Add bias\n    total = weighted_sum + bias\n    \n    # 3. Apply activation\n    return step_activation(total)\n\ni = [0.5, 0.8]\nw = [0.2, -0.5]\nb = 0.1\n\noutput = run_neuron(i, w, b)\nprint(\"Neuron Output:\", output)", "hint": "Use indices [0] and [1] for weights. Add bias. Call step_activation.", "rubric": "Calculates correctly. (0.1 - 0.4 + 0.1) = -0.2. Step activation returns 0."}
    ],
    "PyTorch Tensors": [
        {"title": "Multi-dimensional Math", "theory": "## Tensors vs Arrays\\nA Tensor is the core data structure in PyTorch. It's exactly like a NumPy array (a grid of numbers), but it can run on GPUs for massive parallel speedups.\\n\\n- **0D Tensor**: A scalar (single number, e.g., 5)\n- **1D Tensor**: A vector (array of numbers, e.g., [1, 2, 3])\n- **2D Tensor**: A matrix (grid of numbers)\n- **3D Tensor**: e.g., an RGB image.", "instructions": "## Task: Tensor Operations\\n1. Simulate a basic element-wise Tensor addition without importing PyTorch.\\n2. Add `tensor_a` and `tensor_b` together.", "starterCode": "def tensor_add_2d(a, b):\n    result = []\n    # Iterate through rows\n    for i in range(len(a)):\n        row = []\n        # Iterate through columns\n        for j in range(len(a[i])):\n            # Add corresponding elements\n            val = a[___][___] + b[___][___]\n            row.append(val)\n        result.append(row)\n    return result\n\ntensor_a = [[1, 2], [3, 4]]\ntensor_b = [[10, 20], [30, 40]]\n\nadded = tensor_add_2d(tensor_a, tensor_b)\nprint(\"A + B =\")\nfor row in added:\n    print(row)", "solution": "def tensor_add_2d(a, b):\n    result = []\n    # Iterate through rows\n    for i in range(len(a)):\n        row = []\n        # Iterate through columns\n        for j in range(len(a[i])):\n            # Add corresponding elements\n            val = a[i][j] + b[i][j]\n            row.append(val)\n        result.append(row)\n    return result\n\ntensor_a = [[1, 2], [3, 4]]\ntensor_b = [[10, 20], [30, 40]]\n\nadded = tensor_add_2d(tensor_a, tensor_b)\nprint(\"A + B =\")\nfor row in added:\n    print(row)", "hint": "Use indices [i][j] to access the specific cell.", "rubric": "Results in [[11, 22], [33, 44]]."}
    ],
    "Vision Transformers": [
        {"title": "ViT Architecture", "theory": "## Patches instead of Pixels\\nFor a long time, CNNs dominated Computer Vision. Now, **Vision Transformers (ViT)** are taking over.\\n\\nInstead of sliding a filter over an image (CNN), a ViT cuts the image into a grid of 'patches' (like 16x16 pixels). It flattens these patches and treats them exactly like words in a sentence, feeding them into a standard Transformer (like ChatGPT uses).", "instructions": "## Task: Image Patcher\\n1. Imagine a 4x4 image (represented by a 2D array).\\n2. Cut it into 2x2 'patches'.\\n3. For simplicity, just extract the top-left 2x2 patch.", "starterCode": "image = [\n    [1, 1, 2, 2],\n    [1, 1, 2, 2],\n    [3, 3, 4, 4],\n    [3, 3, 4, 4]\n]\n\ndef extract_top_left_patch(img):\n    patch = []\n    # Extract rows 0 and 1\n    for i in range(2):\n        row = []\n        # Extract cols 0 and 1\n        for j in range(2):\n            row.append(img[___][___])\n        patch.append(row)\n    return patch\n\nprint(\"Top Left Patch:\")\nfor r in extract_top_left_patch(image):\n    print(r)", "solution": "image = [\n    [1, 1, 2, 2],\n    [1, 1, 2, 2],\n    [3, 3, 4, 4],\n    [3, 3, 4, 4]\n]\n\ndef extract_top_left_patch(img):\n    patch = []\n    # Extract rows 0 and 1\n    for i in range(2):\n        row = []\n        # Extract cols 0 and 1\n        for j in range(2):\n            row.append(img[i][j])\n        patch.append(row)\n    return patch\n\nprint(\"Top Left Patch:\")\nfor r in extract_top_left_patch(image):\n    print(r)", "hint": "Use indices [i][j].", "rubric": "Correctly extracts the 2x2 patch of 1s."}
    ]
}

def apply_lessons(tracks_dir):
    total = 0
    # Process EVERY json file directly instead of using track_courses keys which might be mismatched
    for filename in os.listdir(tracks_dir):
        if not filename.endswith('.json'):
            continue
            
        filepath = os.path.join(tracks_dir, filename)
        with open(filepath, 'r', encoding='utf-8') as f:
            track_data = json.load(f)
            
        updated = False
        for course_name in track_data:
            if course_name in LESSONS_BATCH22:
                track_data[course_name]['lessons'] = LESSONS_BATCH22[course_name]
                updated = True
                total += len(LESSONS_BATCH22[course_name])
                
        if updated:
            with open(filepath, 'w', encoding='utf-8') as f:
                json.dump(track_data, f, indent=2, ensure_ascii=False)
                
    print(f'Batch 22: Applied {total} lessons')
    os.system('python build_courses.py')

if __name__ == '__main__':
    apply_lessons(os.path.join('curriculum', 'tracks'))
