"""
Batch 5: More exact course names
"""
import json, os

LESSONS_BATCH5 = {
    # ─── GO / CLOUD NATIVE ───
    "Go Syntax": [
        {"title": "Hello Go", "theory": "## Welcome to Go\nGo (Golang) is a statically typed, compiled language designed at Google.\n\n```go\npackage main\n\nimport \"fmt\"\n\nfunc main() {\n    fmt.Println(\"Hello, World!\")\n}\n```\n\n- `package main`: Tells the compiler this is an executable\n- `import \"fmt\"`: Imports the formatting package (I/O)\n- `func main()`: The entry point of the program", "instructions": "## Task: Your First Go Program\n1. Write a Go program that prints a greeting\n2. The package must be `main`\n3. Use `fmt.Println` to output \"Hello from Go!\"", "starterCode": "___ main\n\n___ \"fmt\"\n\n___ main() {\n    fmt.___(\"Hello from Go!\")\n}", "solution": "package main\n\nimport \"fmt\"\n\nfunc main() {\n    fmt.Println(\"Hello from Go!\")\n}", "hint": "package main. import \"fmt\". func main(). fmt.Println.", "rubric": "Code matches Go structure and prints 'Hello from Go!'"},
        {"title": "Variables & Types", "theory": "## Declaring Variables\nGo has explicit types but also supports type inference.\n\n```go\n// Explicit typing\nvar age int = 25\nvar name string = \"Alice\"\n\n// Type inference\nvar score = 100\n\n// Short declaration (inside functions only)\ncity := \"New York\"\npi := 3.14\n```", "instructions": "## Task: Declare Variables\n1. Declare `year` as an int using explicit typing\n2. Declare `language` as a string using type inference (`var`)\n3. Declare `version` as a float using short declaration (`:=`)\n4. Print them all", "starterCode": "package main\n\nimport \"fmt\"\n\nfunc main() {\n    ___ year ___ = 2024\n    ___ language = \"Go\"\n    version ___ 1.22\n    \n    fmt.Printf(\"Year: %d, Language: %s, Version: %.2f\\n\", year, language, version)\n}", "solution": "package main\n\nimport \"fmt\"\n\nfunc main() {\n    var year int = 2024\n    var language = \"Go\"\n    version := 1.22\n    \n    fmt.Printf(\"Year: %d, Language: %s, Version: %.2f\\n\", year, language, version)\n}", "hint": "var name type. var name = value. name := value.", "rubric": "All three variable types declared correctly and printed."},
        {"title": "Functions in Go", "theory": "## Go Functions\nGo functions can return multiple values!\n\n```go\n// Basic function\nfunc add(a int, b int) int {\n    return a + b\n}\n\n// Shorthand parameters\nfunc multiply(a, b int) int {\n    return a * b\n}\n\n// Multiple returns\nfunc divide(a, b float64) (float64, error) {\n    if b == 0 {\n        return 0, fmt.Errorf(\"divide by zero\")\n    }\n    return a / b, nil\n}\n```", "instructions": "## Task: Math Functions\n1. Write `max(a, b int) int` that returns the larger number\n2. Write `swap(x, y string) (string, string)` that returns both strings swapped\n3. Test both in main", "starterCode": "package main\n\nimport \"fmt\"\n\nfunc max(a, b ___) ___ {\n    if a > b {\n        ___ a\n    }\n    ___ b\n}\n\nfunc swap(x, y ___) (___, ___) {\n    ___ y, x\n}\n\nfunc main() {\n    fmt.Println(\"Max:\", max(10, 20))\n    a, b := swap(\"first\", \"second\")\n    fmt.Println(\"Swap:\", a, b)\n}", "solution": "package main\n\nimport \"fmt\"\n\nfunc max(a, b int) int {\n    if a > b {\n        return a\n    }\n    return b\n}\n\nfunc swap(x, y string) (string, string) {\n    return y, x\n}\n\nfunc main() {\n    fmt.Println(\"Max:\", max(10, 20))\n    a, b := swap(\"first\", \"second\")\n    fmt.Println(\"Swap:\", a, b)\n}", "hint": "Specify types for params and returns. Return y, x to swap.", "rubric": "Max returns 20. Swap returns 'second first'."}
    ],
    "Goroutines": [
        {"title": "Goroutines Basics", "theory": "## Lightweight Threads\nGoroutines are functions that run concurrently with other functions.\n\n```go\nfunc say(text string) {\n    fmt.Println(text)\n}\n\nfunc main() {\n    go say(\"World\")  // Runs in background\n    say(\"Hello\")     // Runs immediately\n    time.Sleep(time.Second) // Wait for goroutine to finish\n}\n```\n\nGoroutines are cheap — you can easily run thousands of them.", "instructions": "## Task: Start Goroutines\n1. Write a function `printNumbers(prefix string)` that prints 1 to 3\n2. Call it once normally, and once as a goroutine\n3. Simulate a small delay with `time.Sleep` in the loop", "starterCode": "package main\n\nimport (\n    \"fmt\"\n    \"time\"\n)\n\nfunc printNumbers(prefix string) {\n    for i := 1; i <= 3; i++ {\n        time.Sleep(100 * time.Millisecond)\n        fmt.Printf(\"%s: %d\\n\", prefix, i)\n    }\n}\n\nfunc main() {\n    // Run as goroutine\n    ___ printNumbers(\"Async\")\n    \n    // Run normally (blocks)\n    ___(\"Sync\")\n    \n    // Give goroutine time to finish if Sync finishes first\n    time.Sleep(200 * time.Millisecond)\n}", "solution": "package main\n\nimport (\n    \"fmt\"\n    \"time\"\n)\n\nfunc printNumbers(prefix string) {\n    for i := 1; i <= 3; i++ {\n        time.Sleep(100 * time.Millisecond)\n        fmt.Printf(\"%s: %d\\n\", prefix, i)\n    }\n}\n\nfunc main() {\n    // Run as goroutine\n    go printNumbers(\"Async\")\n    \n    // Run normally (blocks)\n    printNumbers(\"Sync\")\n    \n    // Give goroutine time to finish if Sync finishes first\n    time.Sleep(200 * time.Millisecond)\n}", "hint": "Prefix function call with 'go' to start a goroutine.", "rubric": "Both Sync and Async print 1 to 3, likely interleaved."},
        {"title": "Channels", "theory": "## Communicating Between Goroutines\nChannels are pipes that connect concurrent goroutines.\n\n```go\nch := make(chan int)  // Create channel\n\n// Send to channel (in goroutine)\ngo func() {\n    ch <- 42\n}()\n\n// Receive from channel\nvalue := <-ch\nfmt.Println(value)  // 42\n```\n\n\"Do not communicate by sharing memory; instead, share memory by communicating.\"", "instructions": "## Task: Channel Sender & Receiver\n1. Create a channel of strings\n2. Start a goroutine that sends 3 messages to the channel\n3. Receive and print the 3 messages in main", "starterCode": "package main\n\nimport \"fmt\"\n\nfunc main() {\n    // Create a string channel\n    messages := ___(chan string)\n    \n    go func() {\n        messages ___ \"Ping\"\n        messages ___ \"Pong\"\n        messages ___ \"Done\"\n    }()\n    \n    msg1 := ___messages\n    msg2 := ___messages\n    msg3 := ___messages\n    \n    fmt.Println(msg1, msg2, msg3)\n}", "solution": "package main\n\nimport \"fmt\"\n\nfunc main() {\n    // Create a string channel\n    messages := make(chan string)\n    \n    go func() {\n        messages <- \"Ping\"\n        messages <- \"Pong\"\n        messages <- \"Done\"\n    }()\n    \n    msg1 := <-messages\n    msg2 := <-messages\n    msg3 := <-messages\n    \n    fmt.Println(msg1, msg2, msg3)\n}", "hint": "make(chan type). ch <- val sends. val := <-ch receives.", "rubric": "Channel created. Messages sent with <- and received with <-. Prints Ping Pong Done."}
    ],
    "Docker Containers": [
        {"title": "What is Docker?", "theory": "## Containers\nDocker packages applications with all their dependencies into standardized units called **containers**.\n\nBenefits:\n- \"It works on my machine\" -> \"It works everywhere\"\n- Lightweight compared to virtual machines\n- Fast startup\n- Isolated environments\n\nA **Dockerfile** is the blueprint for creating a container image.", "instructions": "## Task: Docker Commands\n1. Create a dictionary matching Docker commands to their functions\n2. Include: build, run, ps, stop, rmi\n3. Print them out", "starterCode": "commands = {\n    'docker build -t app .': '___',\n    'docker run -p 80:80 app': '___',\n    'docker ps': '___',\n    'docker stop <id>': '___',\n    'docker rmi <image>': '___'\n}\n\nfor cmd, desc in commands.items():\n    print(f'{cmd:30} -> {desc}')", "solution": "commands = {\n    'docker build -t app .': 'Build an image from a Dockerfile',\n    'docker run -p 80:80 app': 'Start a container from an image',\n    'docker ps': 'List running containers',\n    'docker stop <id>': 'Stop a running container',\n    'docker rmi <image>': 'Remove an image'\n}\n\nfor cmd, desc in commands.items():\n    print(f'{cmd:30} -> {desc}')", "hint": "build creates images. run starts containers. ps lists them. rmi removes images.", "rubric": "All 5 Docker commands correctly identified."},
        {"title": "Writing a Dockerfile", "theory": "## Anatomy of a Dockerfile\n\n```dockerfile\n# Base image\nFROM python:3.9-slim\n\n# Working directory inside container\nWORKDIR /app\n\n# Copy files\nCOPY requirements.txt .\n\n# Run commands during build\nRUN pip install -r requirements.txt\n\n# Copy rest of the code\nCOPY . .\n\n# Command to run when container starts\nCMD [\"python\", \"app.py\"]\n```", "instructions": "## Task: Node.js Dockerfile\n1. Write the text of a Dockerfile for a Node.js app\n2. Use `node:18-alpine` as base\n3. Copy package.json, run `npm install`, copy code, run `npm start`", "starterCode": "dockerfile = \"\"\"\n___ node:18-alpine\n\n___ /usr/src/app\n\n___ package*.json ./\n\n___ npm install\n\n___ . .\n\n___ [\"npm\", \"start\"]\n\"\"\"\n\nprint(\"Your Dockerfile:\")\nprint(dockerfile)", "solution": "dockerfile = \"\"\"\nFROM node:18-alpine\n\nWORKDIR /usr/src/app\n\nCOPY package*.json ./\n\nRUN npm install\n\nCOPY . .\n\nCMD [\"npm\", \"start\"]\n\"\"\"\n\nprint(\"Your Dockerfile:\")\nprint(dockerfile)", "hint": "FROM sets base. WORKDIR sets dir. COPY moves files. RUN executes in build. CMD is startup.", "rubric": "Valid Node.js Dockerfile using standard keywords."}
    ],
    # ─── AGENTIC AI & MCP ───
    "Agent Foundations": [
        {"title": "What is an AI Agent?", "theory": "## Agents vs LLMs\nAn LLM just predicts text. An **Agent** is an LLM given a goal, a working memory, and tools to interact with the world.\n\n```python\n# LLM: Just answers a question\nanswer = llm(\"What is the weather?\")\n# Output: \"I cannot access real-time weather data.\"\n\n# Agent: Uses a tool to find the answer\nagent = Agent(tools=[weather_api])\nanswer = agent.run(\"What is the weather?\")\n# Output: \"It's 72F and sunny in your location.\"\n```", "instructions": "## Task: Define an Agent\n1. Create an `Agent` class with `memory` and `tools` lists\n2. Implement an `add_tool(name)` method\n3. Print the agent's state", "starterCode": "class Agent:\n    def __init__(self, name):\n        self.name = name\n        self.___ = []\n        self.___ = []\n        \n    def add_tool(self, tool_name):\n        self.tools.___(tool_name)\n        print(f\"[{self.name}] Tool added: {tool_name}\")\n        \nagent = Agent(\"DataBot\")\nagent.__(\"calculator\")\nagent.__(\"web_search\")\nprint(f\"Agent {agent.name} has {len(agent.tools)} tools.\")", "solution": "class Agent:\n    def __init__(self, name):\n        self.name = name\n        self.memory = []\n        self.tools = []\n        \n    def add_tool(self, tool_name):\n        self.tools.append(tool_name)\n        print(f\"[{self.name}] Tool added: {tool_name}\")\n        \nagent = Agent(\"DataBot\")\nagent.add_tool(\"calculator\")\nagent.add_tool(\"web_search\")\nprint(f\"Agent {agent.name} has {len(agent.tools)} tools.\")", "hint": "memory and tools are lists. .append() adds to lists.", "rubric": "Agent created, tools added, and printed correctly."}
    ],
    "Tool Calling": [
        {"title": "Function Calling", "theory": "## Giving LLMs Tools\nWe describe tools to the LLM using a JSON schema, so it knows what it can call and what arguments to provide.\n\n```json\n{\n  \"name\": \"get_weather\",\n  \"description\": \"Get current weather\",\n  \"parameters\": {\n    \"type\": \"object\",\n    \"properties\": {\n      \"location\": {\"type\": \"string\"}\n    }\n  }\n}\n```", "instructions": "## Task: Define a Tool Schema\n1. Create a dictionary representing a tool schema for a `calculator` tool\n2. It should have `name`, `description`, and `parameters`\n3. Parameters should include `operation` (add, subtract) and `numbers` (list of floats)", "starterCode": "import json\n\ntool_schema = {\n    \"name\": \"calculator\",\n    \"description\": \"Perform basic math operations\",\n    \"parameters\": {\n        \"type\": \"___\",\n        \"properties\": {\n            \"operation\": {\n                \"type\": \"___\",\n                \"description\": \"The math operation (add, subtract, multiply, divide)\"\n            },\n            \"numbers\": {\n                \"type\": \"___\",\n                \"items\": {\"type\": \"number\"}\n            }\n        },\n        \"required\": [\"operation\", \"numbers\"]\n    }\n}\n\nprint(json.dumps(tool_schema, indent=2))", "solution": "import json\n\ntool_schema = {\n    \"name\": \"calculator\",\n    \"description\": \"Perform basic math operations\",\n    \"parameters\": {\n        \"type\": \"object\",\n        \"properties\": {\n            \"operation\": {\n                \"type\": \"string\",\n                \"description\": \"The math operation (add, subtract, multiply, divide)\"\n            },\n            \"numbers\": {\n                \"type\": \"array\",\n                \"items\": {\"type\": \"number\"}\n            }\n        },\n        \"required\": [\"operation\", \"numbers\"]\n    }\n}\n\nprint(json.dumps(tool_schema, indent=2))", "hint": "parameters is an 'object'. operation is a 'string'. numbers is an 'array'.", "rubric": "Valid JSON schema printed with object, string, and array types."}
    ],
    "Prompt Engineering": [
        {"title": "Few-Shot Prompting", "theory": "## Teaching by Example\nSometimes the best way to get an LLM to follow a specific format is to show it examples (few-shot prompting).\n\n```\nZero-shot: Translate this to French: Hello\n\nFew-shot: \nEnglish: Apple -> French: Pomme\nEnglish: Dog -> French: Chien\nEnglish: Hello -> French: \n```", "instructions": "## Task: Few-Shot Sentiment Prompt\n1. Create a prompt template that classifies text as Positive or Negative\n2. Provide 2 examples in the prompt\n3. Fill it with a new text", "starterCode": "def build_few_shot_prompt(text):\n    prompt = \"\"\"\nClassify the sentiment of the text.\n\nText: \"I love this product!\"\nSentiment: ___\n\nText: \"Terrible service, very disappointed.\"\nSentiment: ___\n\nText: \"{}\"\nSentiment: \"\"\"\n    return prompt.format(text)\n\nprompt = build_few_shot_prompt(\"The battery life is amazing.\")\nprint(prompt)", "solution": "def build_few_shot_prompt(text):\n    prompt = \"\"\"\nClassify the sentiment of the text.\n\nText: \"I love this product!\"\nSentiment: Positive\n\nText: \"Terrible service, very disappointed.\"\nSentiment: Negative\n\nText: \"{}\"\nSentiment: \"\"\"\n    return prompt.format(text)\n\nprompt = build_few_shot_prompt(\"The battery life is amazing.\")\nprint(prompt)", "hint": "Provide Positive and Negative as the example answers.", "rubric": "Prompt correctly incorporates examples and formats the new text."}
    ]
}

def apply_lessons(tracks_dir):
    from rebuild_curriculum import track_courses
    total = 0
    for track_name, levels in track_courses.items():
        safe_name = track_name.lower().replace(" ", "_").replace("&", "").replace("__", "_") + ".json"
        filepath = os.path.join(tracks_dir, safe_name)
        if not os.path.exists(filepath): continue
        with open(filepath, 'r', encoding='utf-8') as f:
            track_data = json.load(f)
        updated = False
        for course_name in track_data:
            if course_name in LESSONS_BATCH5:
                track_data[course_name]['lessons'] = LESSONS_BATCH5[course_name]
                updated = True
                total += len(LESSONS_BATCH5[course_name])
        if updated:
            with open(filepath, 'w', encoding='utf-8') as f:
                json.dump(track_data, f, indent=2, ensure_ascii=False)
    print(f'Batch 5: Applied {total} lessons')
    os.system('python build_courses.py')

if __name__ == '__main__':
    apply_lessons(os.path.join('curriculum', 'tracks'))
