"""
Batch 4: Cloud Native & Go, System Design, DevOps, Data Engineering
"""
import json, os

LESSONS_BATCH4 = {
    # ─── CLOUD NATIVE & GO ───
    "Go Basics": [
        {"title": "Hello Go", "theory": "## Welcome to Go\nGo (Golang) is a statically typed, compiled language designed at Google.\n\n```go\npackage main\n\nimport \"fmt\"\n\nfunc main() {\n    fmt.Println(\"Hello, World!\")\n}\n```\n\n- `package main`: Tells the compiler this is an executable\n- `import \"fmt\"`: Imports the formatting package (I/O)\n- `func main()`: The entry point of the program", "instructions": "## Task: Your First Go Program\n1. Write a Go program that prints a greeting\n2. The package must be `main`\n3. Use `fmt.Println` to output \"Hello from Go!\"", "starterCode": "___ main\n\n___ \"fmt\"\n\n___ main() {\n    fmt.___(\"Hello from Go!\")\n}", "solution": "package main\n\nimport \"fmt\"\n\nfunc main() {\n    fmt.Println(\"Hello from Go!\")\n}", "hint": "package main. import \"fmt\". func main(). fmt.Println.", "rubric": "Code matches Go structure and prints 'Hello from Go!'"},
        {"title": "Variables & Types", "theory": "## Declaring Variables\nGo has explicit types but also supports type inference.\n\n```go\n// Explicit typing\nvar age int = 25\nvar name string = \"Alice\"\n\n// Type inference\nvar score = 100\n\n// Short declaration (inside functions only)\ncity := \"New York\"\npi := 3.14\n```", "instructions": "## Task: Declare Variables\n1. Declare `year` as an int using explicit typing\n2. Declare `language` as a string using type inference (`var`)\n3. Declare `version` as a float using short declaration (`:=`)\n4. Print them all", "starterCode": "package main\n\nimport \"fmt\"\n\nfunc main() {\n    ___ year ___ = 2024\n    ___ language = \"Go\"\n    version ___ 1.22\n    \n    fmt.Printf(\"Year: %d, Language: %s, Version: %.2f\\n\", year, language, version)\n}", "solution": "package main\n\nimport \"fmt\"\n\nfunc main() {\n    var year int = 2024\n    var language = \"Go\"\n    version := 1.22\n    \n    fmt.Printf(\"Year: %d, Language: %s, Version: %.2f\\n\", year, language, version)\n}", "hint": "var name type. var name = value. name := value.", "rubric": "All three variable types declared correctly and printed."},
        {"title": "Functions in Go", "theory": "## Go Functions\nGo functions can return multiple values!\n\n```go\n// Basic function\nfunc add(a int, b int) int {\n    return a + b\n}\n\n// Shorthand parameters\nfunc multiply(a, b int) int {\n    return a * b\n}\n\n// Multiple returns\nfunc divide(a, b float64) (float64, error) {\n    if b == 0 {\n        return 0, fmt.Errorf(\"divide by zero\")\n    }\n    return a / b, nil\n}\n```", "instructions": "## Task: Math Functions\n1. Write `max(a, b int) int` that returns the larger number\n2. Write `swap(x, y string) (string, string)` that returns both strings swapped\n3. Test both in main", "starterCode": "package main\n\nimport \"fmt\"\n\nfunc max(a, b ___) ___ {\n    if a > b {\n        ___ a\n    }\n    ___ b\n}\n\nfunc swap(x, y ___) (___, ___) {\n    ___ y, x\n}\n\nfunc main() {\n    fmt.Println(\"Max:\", max(10, 20))\n    a, b := swap(\"first\", \"second\")\n    fmt.Println(\"Swap:\", a, b)\n}", "solution": "package main\n\nimport \"fmt\"\n\nfunc max(a, b int) int {\n    if a > b {\n        return a\n    }\n    return b\n}\n\nfunc swap(x, y string) (string, string) {\n    return y, x\n}\n\nfunc main() {\n    fmt.Println(\"Max:\", max(10, 20))\n    a, b := swap(\"first\", \"second\")\n    fmt.Println(\"Swap:\", a, b)\n}", "hint": "Specify types for params and returns. Return y, x to swap.", "rubric": "Max returns 20. Swap returns 'second first'."},
        {"title": "Structs & Methods", "theory": "## Object-Oriented Go\nGo doesn't have classes, it has `structs` (data) and `methods` (functions attached to structs).\n\n```go\ntype Person struct {\n    Name string\n    Age  int\n}\n\n// Method with a receiver\nfunc (p Person) Greet() string {\n    return \"Hi, I'm \" + p.Name\n}\n\n// Pointer receiver (to modify data)\nfunc (p *Person) HaveBirthday() {\n    p.Age++\n}\n```", "instructions": "## Task: Build a Rectangle\n1. Define a `Rectangle` struct with `Width` and `Height` (float64)\n2. Create an `Area()` method (value receiver)\n3. Create a `Scale(factor float64)` method (pointer receiver) to resize it", "starterCode": "package main\n\nimport \"fmt\"\n\ntype Rectangle ___ {\n    Width  ___\n    Height ___\n}\n\nfunc (r ___) Area() float64 {\n    return r.Width * r.Height\n}\n\nfunc (r ___) Scale(factor float64) {\n    r.Width *= factor\n    r.Height *= factor\n}\n\nfunc main() {\n    rect := Rectangle{Width: 10, Height: 5}\n    fmt.Println(\"Area:\", rect.Area())\n    rect.Scale(2)\n    fmt.Println(\"New Area:\", rect.Area())\n}", "solution": "package main\n\nimport \"fmt\"\n\ntype Rectangle struct {\n    Width  float64\n    Height float64\n}\n\nfunc (r Rectangle) Area() float64 {\n    return r.Width * r.Height\n}\n\nfunc (r *Rectangle) Scale(factor float64) {\n    r.Width *= factor\n    r.Height *= factor\n}\n\nfunc main() {\n    rect := Rectangle{Width: 10, Height: 5}\n    fmt.Println(\"Area:\", rect.Area())\n    rect.Scale(2)\n    fmt.Println(\"New Area:\", rect.Area())\n}", "hint": "type Rectangle struct. Value receiver: (r Rectangle). Pointer receiver: (r *Rectangle).", "rubric": "Struct defined. Area returns 50. Scale doubles dimensions so new area is 200."},
        {"title": "Error Handling", "theory": "## Errors as Values\nGo doesn't use try/catch exceptions. Errors are returned as normal values.\n\n```go\nfile, err := os.Open(\"file.txt\")\nif err != nil {\n    fmt.Println(\"Error opening file:\", err)\n    return\n}\n// Proceed with file...\n```\n\nAlways check if `err != nil`!", "instructions": "## Task: Safe Division\n1. Write a `divide(a, b float64)` function that returns `(float64, error)`\n2. If b is 0, return an error using `fmt.Errorf()`\n3. Check the error in main and print the result or error message", "starterCode": "package main\n\nimport \"fmt\"\n\nfunc divide(a, b float64) (___, ___) {\n    if b == 0 {\n        return 0, fmt.___(\"cannot divide by zero\")\n    }\n    return a / b, ___\n}\n\nfunc main() {\n    res, err := divide(10, 0)\n    if err ___ ___ {\n        fmt.Println(\"Error:\", err)\n    } else {\n        fmt.Println(\"Result:\", res)\n    }\n    \n    res2, err2 := divide(10, 2)\n    if err2 != nil {\n        fmt.Println(\"Error:\", err2)\n    } else {\n        fmt.Println(\"Result:\", res2)\n    }\n}", "solution": "package main\n\nimport \"fmt\"\n\nfunc divide(a, b float64) (float64, error) {\n    if b == 0 {\n        return 0, fmt.Errorf(\"cannot divide by zero\")\n    }\n    return a / b, nil\n}\n\nfunc main() {\n    res, err := divide(10, 0)\n    if err != nil {\n        fmt.Println(\"Error:\", err)\n    } else {\n        fmt.Println(\"Result:\", res)\n    }\n    \n    res2, err2 := divide(10, 2)\n    if err2 != nil {\n        fmt.Println(\"Error:\", err2)\n    } else {\n        fmt.Println(\"Result:\", res2)\n    }\n}", "hint": "Returns (float64, error). fmt.Errorf creates errors. nil means no error. err != nil.", "rubric": "divide handles 0 correctly. Main checks err != nil and prints appropriate message."}
    ],
    "Concurrency in Go": [
        {"title": "Goroutines", "theory": "## Lightweight Threads\nGoroutines are functions that run concurrently with other functions.\n\n```go\nfunc say(text string) {\n    fmt.Println(text)\n}\n\nfunc main() {\n    go say(\"World\")  // Runs in background\n    say(\"Hello\")     // Runs immediately\n    time.Sleep(time.Second) // Wait for goroutine to finish\n}\n```\n\nGoroutines are cheap — you can easily run thousands of them.", "instructions": "## Task: Start Goroutines\n1. Write a function `printNumbers(prefix string)` that prints 1 to 3\n2. Call it once normally, and once as a goroutine\n3. Simulate a small delay with `time.Sleep` in the loop", "starterCode": "package main\n\nimport (\n    \"fmt\"\n    \"time\"\n)\n\nfunc printNumbers(prefix string) {\n    for i := 1; i <= 3; i++ {\n        time.Sleep(100 * time.Millisecond)\n        fmt.Printf(\"%s: %d\\n\", prefix, i)\n    }\n}\n\nfunc main() {\n    // Run as goroutine\n    ___ printNumbers(\"Async\")\n    \n    // Run normally (blocks)\n    ___(\"Sync\")\n    \n    // Give goroutine time to finish if Sync finishes first\n    time.Sleep(200 * time.Millisecond)\n}", "solution": "package main\n\nimport (\n    \"fmt\"\n    \"time\"\n)\n\nfunc printNumbers(prefix string) {\n    for i := 1; i <= 3; i++ {\n        time.Sleep(100 * time.Millisecond)\n        fmt.Printf(\"%s: %d\\n\", prefix, i)\n    }\n}\n\nfunc main() {\n    // Run as goroutine\n    go printNumbers(\"Async\")\n    \n    // Run normally (blocks)\n    printNumbers(\"Sync\")\n    \n    // Give goroutine time to finish if Sync finishes first\n    time.Sleep(200 * time.Millisecond)\n}", "hint": "Prefix function call with 'go' to start a goroutine.", "rubric": "Both Sync and Async print 1 to 3, likely interleaved."},
        {"title": "Channels", "theory": "## Communicating Between Goroutines\nChannels are pipes that connect concurrent goroutines.\n\n```go\nch := make(chan int)  // Create channel\n\n// Send to channel (in goroutine)\ngo func() {\n    ch <- 42\n}()\n\n// Receive from channel\nvalue := <-ch\nfmt.Println(value)  // 42\n```\n\n\"Do not communicate by sharing memory; instead, share memory by communicating.\"", "instructions": "## Task: Channel Sender & Receiver\n1. Create a channel of strings\n2. Start a goroutine that sends 3 messages to the channel\n3. Receive and print the 3 messages in main", "starterCode": "package main\n\nimport \"fmt\"\n\nfunc main() {\n    // Create a string channel\n    messages := ___(chan string)\n    \n    go func() {\n        messages ___ \"Ping\"\n        messages ___ \"Pong\"\n        messages ___ \"Done\"\n    }()\n    \n    msg1 := ___messages\n    msg2 := ___messages\n    msg3 := ___messages\n    \n    fmt.Println(msg1, msg2, msg3)\n}", "solution": "package main\n\nimport \"fmt\"\n\nfunc main() {\n    // Create a string channel\n    messages := make(chan string)\n    \n    go func() {\n        messages <- \"Ping\"\n        messages <- \"Pong\"\n        messages <- \"Done\"\n    }()\n    \n    msg1 := <-messages\n    msg2 := <-messages\n    msg3 := <-messages\n    \n    fmt.Println(msg1, msg2, msg3)\n}", "hint": "make(chan type). ch <- val sends. val := <-ch receives.", "rubric": "Channel created. Messages sent with <- and received with <-. Prints Ping Pong Done."}
    ],
    # ─── CLOUD & DEVOPS ───
    "Docker Basics": [
        {"title": "What is Docker?", "theory": "## Containers\nDocker packages applications with all their dependencies into standardized units called **containers**.\n\nBenefits:\n- \"It works on my machine\" -> \"It works everywhere\"\n- Lightweight compared to virtual machines\n- Fast startup\n- Isolated environments\n\nA **Dockerfile** is the blueprint for creating a container image.", "instructions": "## Task: Docker Commands\n1. Create a dictionary matching Docker commands to their functions\n2. Include: build, run, ps, stop, rmi\n3. Print them out", "starterCode": "commands = {\n    'docker build -t app .': '___',\n    'docker run -p 80:80 app': '___',\n    'docker ps': '___',\n    'docker stop <id>': '___',\n    'docker rmi <image>': '___'\n}\n\nfor cmd, desc in commands.items():\n    print(f'{cmd:30} -> {desc}')", "solution": "commands = {\n    'docker build -t app .': 'Build an image from a Dockerfile',\n    'docker run -p 80:80 app': 'Start a container from an image',\n    'docker ps': 'List running containers',\n    'docker stop <id>': 'Stop a running container',\n    'docker rmi <image>': 'Remove an image'\n}\n\nfor cmd, desc in commands.items():\n    print(f'{cmd:30} -> {desc}')", "hint": "build creates images. run starts containers. ps lists them. rmi removes images.", "rubric": "All 5 Docker commands correctly identified."},
        {"title": "Writing a Dockerfile", "theory": "## Anatomy of a Dockerfile\n\n```dockerfile\n# Base image\nFROM python:3.9-slim\n\n# Working directory inside container\nWORKDIR /app\n\n# Copy files\nCOPY requirements.txt .\n\n# Run commands during build\nRUN pip install -r requirements.txt\n\n# Copy rest of the code\nCOPY . .\n\n# Command to run when container starts\nCMD [\"python\", \"app.py\"]\n```", "instructions": "## Task: Node.js Dockerfile\n1. Write the text of a Dockerfile for a Node.js app\n2. Use `node:18-alpine` as base\n3. Copy package.json, run `npm install`, copy code, run `npm start`", "starterCode": "dockerfile = \"\"\"\n___ node:18-alpine\n\n___ /usr/src/app\n\n___ package*.json ./\n\n___ npm install\n\n___ . .\n\n___ [\"npm\", \"start\"]\n\"\"\"\n\nprint(\"Your Dockerfile:\")\nprint(dockerfile)", "solution": "dockerfile = \"\"\"\nFROM node:18-alpine\n\nWORKDIR /usr/src/app\n\nCOPY package*.json ./\n\nRUN npm install\n\nCOPY . .\n\nCMD [\"npm\", \"start\"]\n\"\"\"\n\nprint(\"Your Dockerfile:\")\nprint(dockerfile)", "hint": "FROM sets base. WORKDIR sets dir. COPY moves files. RUN executes in build. CMD is startup.", "rubric": "Valid Node.js Dockerfile using standard keywords."}
    ],
    "System Design & Architecture": [
        {"title": "What is System Design?", "theory": "## Architecture at Scale\nSystem design is how we build complex, scalable, and reliable software systems.\n\nKey Concepts:\n- **Scalability**: Handling growth (more users/data)\n- **Reliability**: Avoiding failures (high availability)\n- **Latency**: How fast the system responds\n- **Throughput**: How much data it handles per second", "instructions": "## Task: Vertical vs Horizontal Scaling\n1. Define `vertical_scaling` (scaling up) - Adding more power (CPU/RAM) to one machine\n2. Define `horizontal_scaling` (scaling out) - Adding more machines to the pool\n3. Create a dictionary matching scenarios to the best approach", "starterCode": "scaling_types = {\n    'vertical': 'Adding more CPU/RAM to a single server',\n    'horizontal': 'Adding more servers to handle the load'\n}\n\nscenarios = {\n    'A sudden massive spike in web traffic': '___',\n    'A database needs more RAM for a heavy query': '___',\n    'Designing a system for infinite growth': '___',\n    'A quick, temporary fix for a slow server': '___'\n}\n\nfor scenario, scale_type in scenarios.items():\n    print(f'{scenario}: {scale_type}')", "solution": "scaling_types = {\n    'vertical': 'Adding more CPU/RAM to a single server',\n    'horizontal': 'Adding more servers to handle the load'\n}\n\nscenarios = {\n    'A sudden massive spike in web traffic': 'horizontal',\n    'A database needs more RAM for a heavy query': 'vertical',\n    'Designing a system for infinite growth': 'horizontal',\n    'A quick, temporary fix for a slow server': 'vertical'\n}\n\nfor scenario, scale_type in scenarios.items():\n    print(f'{scenario}: {scale_type}')", "hint": "Spikes/infinite growth = horizontal (add machines). Specific heavy workloads/quick fixes = vertical (add RAM).", "rubric": "Scenarios mapped correctly to horizontal/vertical scaling."},
        {"title": "Load Balancing", "theory": "## Distributing Traffic\nA Load Balancer (LB) sits in front of your servers and routes traffic across them.\n\nRouting algorithms:\n- **Round Robin**: Sequential (A, B, C, A, B, C)\n- **Least Connections**: Send to the server with fewest active users\n- **IP Hash**: Same user IP always goes to the same server", "instructions": "## Task: Load Balancer Simulator\n1. Implement a Round Robin load balancer\n2. It should rotate through a list of 3 servers\n3. Test it with 10 incoming requests", "starterCode": "class RoundRobinLB:\n    def __init__(self, servers):\n        self.servers = servers\n        self.current = 0\n        \n    def route_request(self, request_id):\n        # Get current server\n        server = self.servers[self.___]\n        # Update index for next time (wrap around)\n        self.current = (self.current + ___) % len(self.___)\n        return server\n\nservers = ['ServerA', 'ServerB', 'ServerC']\nlb = RoundRobinLB(servers)\n\nfor i in range(1, 11):\n    target = lb.route_request(f'Req-{i}')\n    print(f'Req-{i} routed to {target}')", "solution": "class RoundRobinLB:\n    def __init__(self, servers):\n        self.servers = servers\n        self.current = 0\n        \n    def route_request(self, request_id):\n        # Get current server\n        server = self.servers[self.current]\n        # Update index for next time (wrap around)\n        self.current = (self.current + 1) % len(self.servers)\n        return server\n\nservers = ['ServerA', 'ServerB', 'ServerC']\nlb = RoundRobinLB(servers)\n\nfor i in range(1, 11):\n    target = lb.route_request(f'Req-{i}')\n    print(f'Req-{i} routed to {target}')", "hint": "self.current holds the index. Add 1 and modulo by len(servers) to wrap around.", "rubric": "Requests alternate A, B, C, A, B, C..."}
    ],
    # ─── DATA ENGINEERING ───
    "ETL Pipelines": [
        {"title": "What is ETL?", "theory": "## Extract, Transform, Load\nETL is the core process of Data Engineering.\n\n1. **Extract**: Pull data from sources (APIs, Databases, Logs)\n2. **Transform**: Clean, format, aggregate, and enrich the data\n3. **Load**: Save the data into a Data Warehouse for analytics\n\n```python\ndata = extract_from_api()\nclean_data = transform_remove_nulls(data)\nload_to_database(clean_data)\n```", "instructions": "## Task: Simple ETL Pipeline\n1. Extract: Parse a messy CSV string\n2. Transform: Uppercase names, convert price to float, remove empty rows\n3. Load: Save to a clean dictionary list", "starterCode": "messy_csv = \"\"\"\nAlice, 25.50\nBob, 10.00\n, \nCharlie, 45.25\n\"\"\"\n\ndef extract(data_string):\n    # Split by lines, ignore empty lines\n    return [line.split(',') for line in data_string.strip().split('\\n') if line.strip()]\n\ndef transform(raw_data):\n    clean_data = []\n    for row in raw_data:\n        name = row[0].strip()\n        price_str = row[1].strip()\n        if name and price_str:\n            clean_data.append({\n                'name': name.___(),\n                'price': ___(price_str)\n            })\n    return clean_data\n\ndef load(data):\n    print(\"Loading to Warehouse:\")\n    for item in data:\n        print(f\"User: {item['name']}, Spent: ${item['price']:.2f}\")\n\nraw = extract(messy_csv)\nclean = transform(raw)\nload(clean)", "solution": "messy_csv = \"\"\"\nAlice, 25.50\nBob, 10.00\n, \nCharlie, 45.25\n\"\"\"\n\ndef extract(data_string):\n    # Split by lines, ignore empty lines\n    return [line.split(',') for line in data_string.strip().split('\\n') if line.strip()]\n\ndef transform(raw_data):\n    clean_data = []\n    for row in raw_data:\n        name = row[0].strip()\n        price_str = row[1].strip()\n        if name and price_str:\n            clean_data.append({\n                'name': name.upper(),\n                'price': float(price_str)\n            })\n    return clean_data\n\ndef load(data):\n    print(\"Loading to Warehouse:\")\n    for item in data:\n        print(f\"User: {item['name']}, Spent: ${item['price']:.2f}\")\n\nraw = extract(messy_csv)\nclean = transform(raw)\nload(clean)", "hint": ".upper() for uppercase. float() for decimals.", "rubric": "ETL pipeline extracts valid rows, converts to uppercase/floats, and prints clean output."}
    ],
    # ─── MOBILE DEVELOPMENT ───
    "React Native Intro": [
        {"title": "What is React Native?", "theory": "## Build Mobile Apps with JS\nReact Native lets you build iOS and Android apps using React.\n\nInstead of HTML like `<div>` and `<span>`, you use native components:\n- `<View>` instead of `<div>`\n- `<Text>` instead of `<p>` or `<span>`\n- `<TextInput>` instead of `<input>`\n- `<TouchableOpacity>` for buttons", "instructions": "## Task: Map Web to Native\n1. Create a dictionary that maps HTML web tags to React Native components\n2. Map: div, span, input, button, img", "starterCode": "rn_mapping = {\n    'div': '___',\n    'span': '___',\n    'input': '___',\n    'button': '___',\n    'img': '___'\n}\n\nfor web, native in rn_mapping.items():\n    print(f'Web <{web}> -> React Native <{native}>')", "solution": "rn_mapping = {\n    'div': 'View',\n    'span': 'Text',\n    'input': 'TextInput',\n    'button': 'TouchableOpacity',\n    'img': 'Image'\n}\n\nfor web, native in rn_mapping.items():\n    print(f'Web <{web}> -> React Native <{native}>')", "hint": "View, Text, TextInput, TouchableOpacity, Image.", "rubric": "All 5 HTML tags mapped correctly to React Native equivalents."}
    ]
}

def apply_lessons(tracks_dir):
    from rebuild_curriculum import track_courses
    total = 0
    for track_name, levels in track_courses.items():
        safe_name = track_name.lower().replace(" ", "_").replace("&", "").replace("__", "_") + ".json"
        filepath = os.path.join(tracks_dir, safe_name)
        if not os.path.exists(filepath): continue
        with open(filepath, 'r', encoding='utf-8') as f:
            track_data = json.load(f)
        updated = False
        for course_name in track_data:
            if course_name in LESSONS_BATCH4:
                track_data[course_name]['lessons'] = LESSONS_BATCH4[course_name]
                updated = True
                total += len(LESSONS_BATCH4[course_name])
        if updated:
            with open(filepath, 'w', encoding='utf-8') as f:
                json.dump(track_data, f, indent=2, ensure_ascii=False)
    print(f'Batch 4: Applied {total} lessons')
    os.system('python build_courses.py')

if __name__ == '__main__':
    apply_lessons(os.path.join('curriculum', 'tracks'))
