"""
Batch 24: Data Eng, Data Science, DSA, Frontend
"""
import json, os

LESSONS_BATCH24 = {
    # ─── DATA ENGINEERING ───
    "Data Warehouses": [
        {"title": "OLTP vs OLAP", "theory": "## Where does data live?\\n- **OLTP (Online Transaction Processing)**: Databases like PostgreSQL. Built for fast, individual transactions (e.g., creating a user, buying an item).\\n- **OLAP (Online Analytical Processing)**: Data Warehouses like Snowflake or BigQuery. Built for analyzing massive amounts of data at once (e.g., calculating total sales for every day last year).\\n\\nData is moved from OLTP databases into an OLAP warehouse using ETL (Extract, Transform, Load) pipelines.", "instructions": "## Task: Database Router\\n1. Simulate a router that sends a query to either the OLTP database or the OLAP warehouse.\\n2. If the query asks for a 'single user' or 'insert', send it to OLTP.\\n3. If it asks for 'monthly report' or 'average', send it to OLAP.", "starterCode": "def route_query(query):\\n    query = query.lower()\\n    \\n    if 'insert' in query or 'single user' in query:\\n        return \"___\"\\n    elif 'monthly report' in query or 'average' in query:\\n        return \"___\"\\n    return \"Unknown\"\\n\\nqueries = [\\n    \"INSERT INTO users VALUES ('Alice')\",\\n    \"SELECT average(revenue) FROM sales\",\\n    \"Get single user profile for ID 5\",\\n    \"Generate monthly report for 2023\"\\n]\\n\\nfor q in queries:\\n    print(f\"Query: {q:35} -> Routing to: {route_query(q)}\")", "solution": "def route_query(query):\\n    query = query.lower()\\n    \\n    if 'insert' in query or 'single user' in query:\\n        return \"OLTP\"\\n    elif 'monthly report' in query or 'average' in query:\\n        return \"OLAP\"\\n    return \"Unknown\"\\n\\nqueries = [\\n    \"INSERT INTO users VALUES ('Alice')\",\\n    \"SELECT average(revenue) FROM sales\",\\n    \"Get single user profile for ID 5\",\\n    \"Generate monthly report for 2023\"\\n]\\n\\nfor q in queries:\\n    print(f\"Query: {q:35} -> Routing to: {route_query(q)}\")", "hint": "OLTP for fast/single transactions. OLAP for big analytics.", "rubric": "Queries successfully routed to OLTP, OLAP, OLTP, OLAP respectively."}
    ],
    "Feature Stores": [
        {"title": "Reusing ML Features", "theory": "## Don't Repeat Yourself\\nIn Machine Learning, a 'Feature' is an input variable (e.g., 'User's average spend over 30 days').\\n\\nInstead of every Data Scientist writing their own SQL to calculate this feature from raw data, companies use a **Feature Store** (like Feast). It's a central hub where features are calculated once and shared across all models.", "instructions": "## Task: Feature Store Mock\\n1. Simulate a Feature Store.\\n2. When a model asks for 'avg_spend_30d', the feature store checks if it has cached the value. If not, it calculates it and caches it.", "starterCode": "class FeatureStore:\\n    def __init__(self):\\n        self.cache = {}\\n        \\n    def get_feature(self, feature_name, user_id):\\n        cache_key = f\"{feature_name}_{user_id}\"\\n        \\n        if cache_key in self.___:\\n            print(\"[CACHE HIT] Returning saved feature.\")\\n            return self.___[cache_key]\\n            \\n        print(\"[CACHE MISS] Calculating heavy SQL query...\")\\n        # Simulate calculation\\n        val = 145.50 if user_id == 1 else 0.0\\n        \\n        # Save to cache\\n        self.___[___] = val\\n        return val\\n\\nstore = FeatureStore()\\nprint(\"First call:\", store.get_feature('avg_spend_30d', 1))\\nprint(\"Second call:\", store.get_feature('avg_spend_30d', 1))", "solution": "class FeatureStore:\\n    def __init__(self):\\n        self.cache = {}\\n        \\n    def get_feature(self, feature_name, user_id):\\n        cache_key = f\"{feature_name}_{user_id}\"\\n        \\n        if cache_key in self.cache:\\n            print(\"[CACHE HIT] Returning saved feature.\")\\n            return self.cache[cache_key]\\n            \\n        print(\"[CACHE MISS] Calculating heavy SQL query...\")\\n        # Simulate calculation\\n        val = 145.50 if user_id == 1 else 0.0\\n        \\n        # Save to cache\\n        self.cache[cache_key] = val\\n        return val\\n\\nstore = FeatureStore()\\nprint(\"First call:\", store.get_feature('avg_spend_30d', 1))\\nprint(\"Second call:\", store.get_feature('avg_spend_30d', 1))", "hint": "Check self.cache. Save val to self.cache[cache_key].", "rubric": "First call is a miss, second call is a hit."}
    ],
    # ─── DATA SCIENCE ───
    "Matplotlib": [
        {"title": "Data Visualization", "theory": "## A Picture is Worth 1000 Rows\\nMatplotlib is the standard library for creating charts in Python.\\n\\n```python\\nimport matplotlib.pyplot as plt\\n\\nplt.plot([1, 2, 3], [10, 20, 30])\\nplt.title(\"My Chart\")\\nplt.show()\\n```", "instructions": "## Task: Plotting Simulator\\n1. We can't display actual images in this text console, but we can simulate the commands!\\n2. Write the 3 standard Matplotlib commands to plot data, set a title, and display the graph.", "starterCode": "class MockPyPlot:\\n    def plot(self, x, y): print(f\"Plotted line from {x} to {y}\")\\n    def title(self, text): print(f\"Set title: {text}\")\\n    def show(self): print(\"Displaying graph to user!\")\\n\\nplt = MockPyPlot()\\n\\nx_data = [1, 2, 3, 4]\\ny_data = [10, 15, 25, 30]\\n\\n# 1. Plot the data\\nplt.___(x_data, y_data)\\n\\n# 2. Add a title \"Growth\"\\nplt.___(\"Growth\")\\n\\n# 3. Show the graph\\nplt.___()", "solution": "class MockPyPlot:\\n    def plot(self, x, y): print(f\"Plotted line from {x} to {y}\")\\n    def title(self, text): print(f\"Set title: {text}\")\\n    def show(self): print(\"Displaying graph to user!\")\\n\\nplt = MockPyPlot()\\n\\nx_data = [1, 2, 3, 4]\\ny_data = [10, 15, 25, 30]\\n\\n# 1. Plot the data\\nplt.plot(x_data, y_data)\\n\\n# 2. Add a title \"Growth\"\\nplt.title(\"Growth\")\\n\\n# 3. Show the graph\\nplt.show()", "hint": ".plot(), .title(), .show()", "rubric": "Successfully calls the mock plotting functions in order."}
    ],
    "Statistical Analysis": [
        {"title": "Mean, Median, Mode", "theory": "## Understanding Distributions\\n- **Mean**: The average. Very sensitive to outliers (e.g., if Elon Musk walks into a bar, the *mean* wealth of everyone in the bar becomes a billion dollars).\\n- **Median**: The middle number. Much more robust to outliers.\\n- **Mode**: The most frequent number.", "instructions": "## Task: Outlier Impact\\n1. Calculate the Mean and the Median of a dataset with an extreme outlier.\\n2. Observe how the outlier pulls the mean up, but leaves the median intact.", "starterCode": "def calculate_mean(data):\\n    return sum(___) / len(___)\\n\\ndef calculate_median(data):\\n    sorted_data = sorted(___)\\n    mid = len(sorted_data) // 2\\n    return sorted_data[___]\\n\\n# Salaries at a coffee shop (in thousands). The last one is the CEO!\\nsalaries = [30, 32, 35, 40, 45, 900]\\n\\nmean_val = calculate_mean(salaries)\\nmedian_val = calculate_median(salaries)\\n\\nprint(f\"Mean Salary: ${mean_val:.1f}k\")\\nprint(f\"Median Salary: ${median_val:.1f}k\")\\nprint(\"Notice how the CEO salary distorts the Mean!\")", "solution": "def calculate_mean(data):\\n    return sum(data) / len(data)\\n\\ndef calculate_median(data):\\n    sorted_data = sorted(data)\\n    mid = len(sorted_data) // 2\\n    return sorted_data[mid]\\n\\n# Salaries at a coffee shop (in thousands). The last one is the CEO!\\nsalaries = [30, 32, 35, 40, 45, 900]\\n\\nmean_val = calculate_mean(salaries)\\nmedian_val = calculate_median(salaries)\\n\\nprint(f\"Mean Salary: ${mean_val:.1f}k\")\\nprint(f\"Median Salary: ${median_val:.1f}k\")\\nprint(\"Notice how the CEO salary distorts the Mean!\")", "hint": "sum(data) / len(data). sorted_data[mid].", "rubric": "Calculates Mean as 180.3k and Median as 40.0k."}
    ],
    # ─── DATA STRUCTURES & ALGORITHMS ───
    "Sorting Algorithms": [
        {"title": "Bubble Sort", "theory": "## O(N^2) Complexity\\nBubble Sort is a simple but very slow algorithm. It repeatedly steps through the list, compares adjacent elements, and swaps them if they are in the wrong order. It continues until the list is sorted.", "instructions": "## Task: Swap Elements\\n1. Implement the core mechanic of Bubble Sort: swapping adjacent elements.\\n2. Iterate through a list. If element `i` is greater than `i+1`, swap them.\\n3. This is just one pass (not the full sort), which moves the largest element to the end.", "starterCode": "def bubble_sort_single_pass(arr):\\n    # Iterate up to the second-to-last element\\n    for i in range(len(arr) - 1):\\n        if arr[i] > arr[i + 1]:\\n            # Swap them using Python's tuple unpacking\\n            arr[i], arr[___] = arr[___], arr[i]\\n    return arr\\n\\nmy_list = [5, 3, 8, 2, 1]\\nprint(\"Original:\", my_list)\\n\\n# One pass\\nresult = bubble_sort_single_pass(my_list)\\nprint(\"After 1 Pass:\", result)\\nprint(\"(Notice how the largest number, 8, 'bubbled' to the end!)\")", "solution": "def bubble_sort_single_pass(arr):\\n    # Iterate up to the second-to-last element\\n    for i in range(len(arr) - 1):\\n        if arr[i] > arr[i + 1]:\\n            # Swap them using Python's tuple unpacking\\n            arr[i], arr[i + 1] = arr[i + 1], arr[i]\\n    return arr\\n\\nmy_list = [5, 3, 8, 2, 1]\\nprint(\"Original:\", my_list)\\n\\n# One pass\\nresult = bubble_sort_single_pass(my_list)\\nprint(\"After 1 Pass:\", result)\\nprint(\"(Notice how the largest number, 8, 'bubbled' to the end!)\")", "hint": "arr[i], arr[i + 1] = arr[i + 1], arr[i]", "rubric": "Successfully swaps elements. Result is [3, 5, 2, 1, 8]."}
    ],
    "Tries": [
        {"title": "Prefix Trees", "theory": "## Autocomplete Engine\\nA Trie (pronounced 'try') is a tree-like data structure used for efficient string searching. It's the engine behind 'Autocomplete' when you type in a search bar.\\n\\nInstead of storing whole words, it stores individual characters in nodes. Words sharing a prefix (like 'car' and 'cat') share the same branch ('c' -> 'a').", "instructions": "## Task: Insert a Word\\n1. Build a basic Trie structure using nested dictionaries.\\n2. Insert the word 'cat' into the Trie.", "starterCode": "class SimpleTrie:\\n    def __init__(self):\\n        self.root = {}\\n        \\n    def insert(self, word):\\n        current_node = self.root\\n        for char in word:\\n            if char not in current_node:\\n                # Create a new empty dict for this character\\n                current_node[char] = {}\\n            # Move down the tree\\n            current_node = current_node[___]\\n        # Mark the end of the word\\n        current_node['*'] = True\\n\\ntrie = SimpleTrie()\\ntrie.insert(\"cat\")\\ntrie.insert(\"car\")\\n\\n# Should output a nested dict structure sharing 'c' and 'a'\\nprint(\"Trie Structure:\")\\nimport json\\nprint(json.dumps(trie.root, indent=2))", "solution": "class SimpleTrie:\\n    def __init__(self):\\n        self.root = {}\\n        \\n    def insert(self, word):\\n        current_node = self.root\\n        for char in word:\\n            if char not in current_node:\\n                # Create a new empty dict for this character\\n                current_node[char] = {}\\n            # Move down the tree\\n            current_node = current_node[char]\\n        # Mark the end of the word\\n        current_node['*'] = True\\n\\ntrie = SimpleTrie()\\ntrie.insert(\"cat\")\\ntrie.insert(\"car\")\\n\\n# Should output a nested dict structure sharing 'c' and 'a'\\nprint(\"Trie Structure:\")\\nimport json\\nprint(json.dumps(trie.root, indent=2))", "hint": "Move down by setting current_node = current_node[char].", "rubric": "Trie correctly builds a nested dict sharing 'c' and 'a', branching at 't' and 'r'."}
    ],
    "Graph Traversal": [
        {"title": "BFS vs DFS", "theory": "## Searching a Network\\nHow do you find the shortest path in a maze? Or the degrees of separation between two people on LinkedIn?\\n\\n- **BFS (Breadth-First Search)**: Searches layer by layer (neighbors first). Guarantees the shortest path. Uses a Queue.\\n- **DFS (Depth-First Search)**: Explores as far as possible down one branch before backtracking. Uses a Stack (or recursion).", "instructions": "## Task: BFS Queue\\n1. Simulate a Breadth-First Search using a Queue (list).\\n2. Start at Node 'A'. Visit its neighbors before moving deeper.", "starterCode": "graph = {\\n    'A': ['B', 'C'],\\n    'B': ['D', 'E'],\\n    'C': ['F'],\\n    'D': [], 'E': [], 'F': []\\n}\\n\\ndef bfs(graph, start):\\n    queue = [start]\\n    visited = set()\\n    \\n    while queue:\\n        # Pop the first element (FIFO)\\n        node = queue.pop(___)\\n        \\n        if node not in visited:\\n            print(f\"Visiting: {node}\")\\n            visited.add(___)\\n            \\n            # Add neighbors to the queue\\n            for neighbor in graph[node]:\\n                queue.append(___)\\n\\nprint(\"BFS Traversal Order:\")\\nbfs(graph, 'A')", "solution": "graph = {\\n    'A': ['B', 'C'],\\n    'B': ['D', 'E'],\\n    'C': ['F'],\\n    'D': [], 'E': [], 'F': []\\n}\\n\\ndef bfs(graph, start):\\n    queue = [start]\\n    visited = set()\\n    \\n    while queue:\\n        # Pop the first element (FIFO)\\n        node = queue.pop(0)\\n        \\n        if node not in visited:\\n            print(f\"Visiting: {node}\")\\n            visited.add(node)\\n            \\n            # Add neighbors to the queue\\n            for neighbor in graph[node]:\\n                queue.append(neighbor)\\n\\nprint(\"BFS Traversal Order:\")\\nbfs(graph, 'A')", "hint": "queue.pop(0) for FIFO. visited.add(node). queue.append(neighbor).", "rubric": "Visits in layer order: A, B, C, D, E, F."}
    ],
    # ─── FRONTEND ───
    "CSS Grid & Flexbox": [
        {"title": "Modern Layouts", "theory": "## CSS Flexbox\\nFlexbox is designed for 1-dimensional layouts (a row OR a column). It makes aligning items incredibly easy.\\n\\n```css\\n.container {\\n  display: flex;\\n  justify-content: center; /* Horizontally centers */\\n  align-items: center;     /* Vertically centers */\\n}\\n```\\n## CSS Grid\\nGrid is designed for 2-dimensional layouts (rows AND columns, like a checkerboard).", "instructions": "## Task: Flexbox Align\\n1. You have a simulated container with elements.\\n2. Match the flexbox property to what it does.", "starterCode": "flex_props = {\\n    'Space out elements evenly across the main axis': 'justify-content: ___',\\n    'Center elements on the cross axis (vertical if flex-direction is row)': 'align-items: ___',\\n    'Stack elements vertically instead of horizontally': 'flex-direction: ___'\\n}\\n\\nfor desc, prop in flex_props.items():\\n    print(f\"{prop:30} -> {desc}\")", "solution": "flex_props = {\\n    'Space out elements evenly across the main axis': 'justify-content: space-between',\\n    'Center elements on the cross axis (vertical if flex-direction is row)': 'align-items: center',\\n    'Stack elements vertically instead of horizontally': 'flex-direction: column'\\n}\\n\\nfor desc, prop in flex_props.items():\\n    print(f\"{prop:30} -> {desc}\")", "hint": "space-between, center, column.", "rubric": "Properties correctly matched."}
    ]
}

def apply_lessons(tracks_dir):
    total = 0
    # Process EVERY json file directly
    for filename in os.listdir(tracks_dir):
        if not filename.endswith('.json'):
            continue
            
        filepath = os.path.join(tracks_dir, filename)
        with open(filepath, 'r', encoding='utf-8') as f:
            track_data = json.load(f)
            
        updated = False
        for course_name in track_data:
            if course_name in LESSONS_BATCH24:
                track_data[course_name]['lessons'] = LESSONS_BATCH24[course_name]
                updated = True
                total += len(LESSONS_BATCH24[course_name])
                print(f"Applied {course_name} in {filename}")
                
        if updated:
            with open(filepath, 'w', encoding='utf-8') as f:
                json.dump(track_data, f, indent=2, ensure_ascii=False)
                
    print(f'Batch 24: Applied {total} lessons')
    os.system('python build_courses.py')

if __name__ == '__main__':
    apply_lessons(os.path.join('curriculum', 'tracks'))
