import json
import os

TRACKS_THEORY = {
    "cloud_devops.json": {
        "Introduction to AWS": "## The Pioneer of Cloud Computing\nBefore Amazon Web Services (AWS) launched in 2006, if a company wanted to build a web application, they had to buy physical servers, rent space in a data center, plug in the network cables, and install the operating system themselves. This took months and hundreds of thousands of dollars.\n\nAWS revolutionized this by renting out their massive global infrastructure over the internet. Instead of buying a server, you rent a 'Virtual Machine' by the hour. If your app goes viral, you can rent 100 more servers in a few seconds. If traffic dies down, you terminate them and stop paying immediately. \n\nThis model is called **Infrastructure as a Service (IaaS)**. AWS is the dominant player in this space, providing not just servers, but databases, AI models, and networking tools on demand. Mastering AWS is the cornerstone of modern DevOps.",
        "Core Services": "## The Big Three\nAWS has over 200 different services, which can be incredibly overwhelming for beginners. However, 90% of basic web applications rely on just three core foundational services: Compute, Storage, and Databases.\n\n1. **EC2 (Elastic Compute Cloud):** This is your compute power. It's simply a virtual computer running Linux or Windows in the cloud. You can install a web server on it and run your code.\n2. **S3 (Simple Storage Service):** This is for storing files like images, videos, and backups. It's essentially an infinite hard drive in the cloud. You cannot run code on S3; it only stores static objects.\n3. **RDS (Relational Database Service):** This provides managed databases (like PostgreSQL or MySQL). Instead of you installing and managing the database software on an EC2 instance yourself, AWS handles the backups, updates, and maintenance for you.",
        "EC2 Instances": "## Renting Computers by the Hour\nAn **EC2 Instance** is a virtual server in Amazon's cloud. When you launch one, you choose the Operating System (usually Amazon Linux or Ubuntu), the CPU power, and the amount of RAM.\n\nThink of EC2 like renting a car. You can rent a small, cheap economy car (a `t3.micro` instance) for basic web browsing. If you need to haul heavy materials, you rent a massive pickup truck (a memory-optimized `r5.4xlarge` instance) and pay significantly more per hour.\n\nEC2 instances are 'ephemeral', meaning if the underlying physical hardware fails, your instance will go down. Because of this, DevOps engineers never store critical permanent data directly on the EC2 instance's main drive; they store it in a database (RDS) or object storage (S3) so the compute layer remains completely stateless and disposable.",
        "S3 Buckets": "## Infinite Object Storage\nAmazon S3 (Simple Storage Service) is one of the oldest and most widely used AWS services. It is designed to store and retrieve any amount of data from anywhere on the internet. \n\nIn S3, you don't use 'folders' and 'directories' like on your laptop. S3 is an **Object Storage** system. Files are called 'Objects', and they are stored in flat containers called **Buckets**. Every bucket must have a globally unique name across all of AWS (like a website domain name).\n\nS3 is incredibly durable (designed for 99.999999999% durability). It is commonly used for storing user-uploaded profile pictures, hosting static HTML/CSS/JS files for frontend websites, storing massive datasets for machine learning, and keeping automated database backups safe.",
        "The Linux Command Line": "## The Language of Servers\nWhile you might use a mouse and a graphical user interface (GUI) on your personal laptop, servers run almost exclusively on Linux without any graphical interface. You interact with them solely through text commands.\n\nThe command line (or shell) allows you to navigate the file system (`cd`), list files (`ls`), create directories (`mkdir`), and edit text (`nano` or `vim`). It is extremely lightweight and fast.\n\nMastering the Linux command line is absolutely non-negotiable for a DevOps engineer. Whether you are SSHing into a crashed EC2 instance to read error logs or writing a bash script to automate a deployment, the terminal is your primary working environment.",
        "File Permissions": "## Who Can Do What?\nIn Linux, security is baked deeply into the file system. Every file and directory has a strict set of permissions dictating who is allowed to **Read (r)**, **Write (w)**, or **Execute (x)** it.\n\nPermissions are divided into three groups:\n1. **User (Owner):** The person who created the file.\n2. **Group:** A specific group of users (e.g., 'developers' or 'admins').\n3. **Others:** Everyone else on the system.\n\nYou will often see permissions represented as a three-digit number, like `755` or `644`. This is octal notation. `7` means full permissions (Read+Write+Execute). `6` means Read+Write. `4` means Read-Only. If a web server needs to read an HTML file but shouldn't be allowed to edit it, you must configure the Linux file permissions correctly, or the website will return a '403 Forbidden' error.",
        "Infrastructure as Code": "## Stop Clicking, Start Coding\nHistorically, if a company needed a new server and database, a system administrator would log into the AWS web console and manually click through dozens of menus to configure the network, security groups, and instances. This manual process is slow, error-prone, and impossible to replicate perfectly.\n\n**Infrastructure as Code (IaC)** solves this. Instead of clicking buttons, you write code (using tools like Terraform or AWS CloudFormation) that describes exactly what your infrastructure should look like. \n\nFor example, you write a text file stating: *'I need one database and two web servers connected to a load balancer.'* You run the IaC tool, and it automatically makes the API calls to AWS to create everything. If you need to replicate this environment in Europe, you just run the same code again. IaC makes infrastructure versionable, testable, and automated.",
        "What is CI/CD?": "## Continuous Integration & Continuous Deployment\n**CI/CD** is the beating heart of modern software delivery. It is the automated pipeline that takes a developer's code from their laptop and pushes it safely into production.\n\n**Continuous Integration (CI):** When a developer commits code to GitHub, the CI pipeline automatically wakes up, builds the code, and runs all the unit tests. If the tests fail, the code is rejected. This ensures the main codebase is never broken.\n\n**Continuous Deployment (CD):** Once the CI phase passes, the CD pipeline automatically takes the compiled code and deplhires it to the servers (staging or production) without human intervention. This allows companies like Amazon or Netflix to release new features hundreds of times a day safely, rather than doing massive, risky deployments once a month.",
        "GitHub Actions": "## Automating Workflows\nGitHub Actions is a powerful CI/CD platform built directly into GitHub. It allows you to automate your software workflows based on triggers like pushing code or creating a pull request.\n\nYou define a workflow in a YAML file located in the `.github/workflows/` directory. Inside this file, you define **Jobs** (e.g., 'Build' and 'Test') and **Steps** (the individual commands to run, like `npm install` and `npm test`). \n\nWhen a developer pushes code, GitHub spins up a fresh virtual machine (a runner), downloads the code, and executes the steps exactly as you defined them. If a step fails, the action turns red, and the developer is notified. GitHub Actions has largely replaced older tools like Jenkins because it requires no servers to maintain and lives right next to your code.",
        "Logging Levels": "## Filtering the Noise\nWhen an application runs, it generates logs. However, not all logs are equally important. If an app logs every single user click *and* every critical database failure into the same text file, finding the failure is like finding a needle in a haystack.\n\nTo solve this, developers use **Logging Levels**. \n- **DEBUG:** Extremely detailed information used only when actively hunting a bug. (e.g., 'Variable X equals 4').\n- **INFO:** Routine operational messages. (e.g., 'User logged in', 'Server started on port 80').\n- **WARN:** Something unexpected happened, but the app recovered. (e.g., 'API rate limit approaching').\n- **ERROR:** A serious issue that prevented a task from succeeding. (e.g., 'Database connection timeout').\n\nIn a production environment, DevOps engineers typically configure the system to only save `INFO`, `WARN`, and `ERROR` logs to save storage space and reduce noise.",
        "What is Serverless?": "## Focusing Only on Code\nThe term **Serverless** is slightly misleading. There are still physical servers involved, but *you* don't have to manage, provision, or patch them. The cloud provider handles all the underlying infrastructure.\n\nThink of a traditional EC2 instance as renting a house: you have to clean it, secure it, and pay for it 24/7 even if you aren't home. Serverless (like AWS Lambda) is like staying in a hotel: you just show up, use the room, and only pay for the exact minutes you are inside.\n\nWith Serverless, you upload a zip file of your Python or Node.js code. When a request comes in, AWS instantly spins up an environment, runs your code, returns the result, and destroys the environment. If 10,000 requests come in at once, AWS runs 10,000 copies simultaneously. You are billed purely for the compute time used, down to the millisecond.",
        "Virtual Firewalls": "## Security Groups and NACLs\nIn the cloud, you can't install a physical firewall box on the network cable. Instead, AWS provides software-defined **Virtual Firewalls** to protect your resources.\n\nThe most common type is a **Security Group**. A Security Group acts as a virtual bouncer for your EC2 instances. You define strict rules: *'Allow incoming HTTP traffic on port 80 from anywhere, but only allow SSH traffic on port 22 from my specific office IP address.'* \n\nBy default, Security Groups deny all incoming traffic. If you spin up a web server and forget to open port 80 in the Security Group, your website will be completely unreachable from the internet, regardless of how perfectly the code is running.",
        "Cloud Billing": "## The Hidden Challenge of DevOps\nOne of the most dangerous aspects of cloud computing is the billing model. Because you can provision infinite resources with the click of a button, a tiny mistake can cost thousands of dollars.\n\nImagine writing a Serverless Lambda function that accidentally triggers itself in an infinite loop. AWS will happily execute that function millions of times an hour and send you a massive bill at the end of the month. \n\nDevOps engineers must be acutely aware of cloud economics. They configure **Billing Alarms** to trigger an email if spending exceeds a specific threshold. They also use tools to identify 'zombie' resources—like unattached storage drives or idle test servers—and automatically terminate them to optimize costs.",
        "The Shebang": "## Defining the Interpreter\nWhen you write a script in Linux, the operating system needs to know what program (interpreter) should be used to read and execute the code. Is it a Bash script? Python? Node.js?\n\nThis is solved using a **Shebang** ( `#!` ) on the very first line of the file.\n\nFor example, if you write a bash script, the first line must be `#!/bin/bash`. If it's a Python script, it should be `#!/usr/bin/env python3`. When you execute the file from the terminal (e.g., `./myscript`), Linux reads that first line, finds the specified interpreter, and passes the rest of the file to it. Without a shebang, the OS might try to execute your Python code as basic bash commands, resulting in syntax errors.",
        "Variables and Arguments": "## Making Scripts Dynamic\nHardcoding values in a script is a bad practice. If a script backs up a database, you shouldn't hardcode the database password directly in the file. Instead, you use **Variables** and **Arguments**.\n\n**Arguments** are passed to the script when you run it from the command line. In bash, they are accessed using `$1`, `$2`, etc. For example, running `./backup.sh prod_db` makes `prod_db` available as `$1` inside the script.\n\n**Environment Variables** are values stored in the operating system itself. A DevOps engineer can securely store an API key as an environment variable (e.g., `export API_KEY=123`). The script can then read that variable securely without it ever being written in the source code. This is crucial for keeping secrets out of GitHub.",
        "Providers and Resources": "## The Core of Terraform\nTerraform is the industry-standard tool for Infrastructure as Code. It uses two main concepts: **Providers** and **Resources**.\n\nA **Provider** is a plugin that tells Terraform how to talk to a specific cloud (like AWS, Google Cloud, or Azure). You must define the provider at the top of your code so Terraform knows where to authenticate.\n\nA **Resource** is the actual piece of infrastructure you want to create (e.g., a server, a database, a network rule). \n\n```hcl\n# Provider configuration\nprovider \"aws\" {\n  region = \"us-east-1\"\n}\n\n# Resource definition\nresource \"aws_instance\" \"my_server\" {\n  ami           = \"ami-123456\"\n  instance_type = \"t2.micro\"\n}\n```\nTerraform reads this, talks to the AWS API (via the provider), and creates the exact server you described.",
        "State Files": "## Terraform's Memory\nWhen you run Terraform to create a server, how does it know later on if that server already exists or if it needs to create a new one? It uses a **State File**.\n\nThe state file (`terraform.tfstate`) is a JSON document that maps your Terraform code to the actual real-world resources in the cloud. It is Terraform's 'memory'. \n\nIf you change your code to upgrade the server's RAM and run Terraform again, Terraform compares your new code against the state file. It realizes the server already exists but the RAM doesn't match. It then calculates the exact API calls needed to upgrade the RAM without destroying the server. Because the state file is so critical (and often contains sensitive passwords), DevOps teams store it centrally and securely in an S3 bucket, never on a local laptop.",
        "Workflow Triggers": "## Starting the Pipeline\nIn CI/CD systems like GitHub Actions, a **Trigger** defines *when* a workflow should automatically run. You rarely trigger pipelines manually.\n\nThe most common trigger is `push`. You can configure a workflow to run every time code is pushed to the `main` branch. \n\nOther powerful triggers include:\n- `pull_request`: Runs tests when someone tries to merge code, ensuring broken code is blocked before it reaches the main branch.\n- `schedule`: Runs the workflow on a cron timer (e.g., run a security scan every night at midnight).\n- `workflow_dispatch`: Adds a button to the GitHub UI allowing you to trigger it manually if needed.",
        "Jobs and Steps": "## Structuring the Pipeline\nA GitHub Actions workflow is broken down into **Jobs**, and each job is broken down into **Steps**.\n\nA **Job** runs on a specific virtual machine. By default, multiple jobs run in parallel to save time. For example, you might have a 'Linting Job' and a 'Unit Test Job' running simultaneously. \n\nA **Step** is a single sequential task within a job. Steps run one after the other. A step can either run a raw shell command (like `npm install`) or use a pre-built Action (like checking out the code or logging into AWS). If any step fails, the entire Job fails and the pipeline halts immediately to prevent broken code from being deployed.",
        "Metrics Exporters": "## Gathering the Data\nIn system observability, you need to know how much CPU your servers are using, how many HTTP requests are failing, and how much RAM is left. Applications don't automatically send this data to a dashboard; they need an **Exporter**.\n\nAn exporter is a small sidecar program that sits next to your application. It hooks into the operating system or the app itself, gathers real-time metrics, and translates them into a standardized format. \n\nFor example, the Prometheus `Node Exporter` reads Linux system stats (CPU, disk space) and exposes them on a web URL (e.g., `http://server-ip:9100/metrics`). A central monitoring server (like Prometheus) then scrapes this URL every 15 seconds, collects the numbers, and stores them in a time-series database so they can be graphed.",
        "PromQL Basics": "## Querying the Metrics\nPrometheus is the industry standard for storing system metrics. To graph that data, you use **PromQL (Prometheus Query Language)**.\n\nUnlike SQL which searches for rows in a database, PromQL queries time-series data (values that change over time). \n\nFor example, the metric `http_requests_total` is a counter that only ever goes up. If you just query that, you see a massive number. PromQL allows you to apply functions. Querying `rate(http_requests_total[5m])` calculates how fast the counter is increasing, giving you the average requests per second over the last 5 minutes. Mastering PromQL allows DevOps engineers to build powerful dashboards in Grafana that instantly highlight anomalies and traffic spikes.",
        "SLAs, SLOs, and SLIs": "## Measuring Reliability\nHow do you define if a system is 'healthy'? DevOps and Site Reliability Engineering (SRE) rely on three acronyms:\n\n1. **SLI (Service Level Indicator):** The actual, real-time measurement of performance. Example: *99.5% of HTTP requests returned a 200 OK status in the last hour.*\n2. **SLO (Service Level Objective):** The internal goal the engineering team aims for. Example: *We want 99.9% of all requests to be successful.* If the SLI drops below the SLO, the team stops building new features and focuses purely on fixing bugs.\n3. **SLA (Service Level Agreement):** The legal contract with the customer. Example: *If uptime drops below 99.0%, we will refund the customer 10% of their bill.* SLAs are always lower than SLOs to give the engineering team a safety buffer.",
        "Error Budgets": "## Balancing Speed and Stability\nIn software engineering, there is a constant tension between developers (who want to push new features fast) and operations (who want the system to be perfectly stable and never change). **Error Budgets** solve this argument mathematically.\n\nIf your Service Level Objective (SLO) for uptime is 99.9% a month, that means you are *allowed* to be down for 43 minutes a month. That 43 minutes is your **Error Budget**.\n\nIf developers push a buggy update and the site goes down for 10 minutes, the budget drops to 33 minutes. If they burn through the entire 43 minutes in a week, a hard rule is enforced: **No more feature deployments are allowed for the rest of the month.** All engineers must pivot to writing tests and fixing stability. This aligns incentives, encouraging developers to care about reliability because poor code will freeze their feature releases."
    },
    "cloud_native_go.json": {
        "Hello Go": "## A Modern Language for the Cloud\nGo (or Golang) was created at Google in 2009 by the original inventors of C and Unix. They were frustrated by how slow massive C++ codebases took to compile, and how difficult it was to write concurrent (multi-threaded) code in languages like Java or Python.\n\nGo was designed to be incredibly fast to compile, highly performant (it compiles directly to machine code, no JVM required), and exceptionally good at handling thousands of simultaneous connections. It has strict formatting (there is only one way to format Go code, enforced by `gofmt`) and a tiny, minimalist syntax.\n\nBecause of its speed, low memory footprint, and native concurrency, Go became the language of the cloud. Kubernetes, Docker, Terraform, and Prometheus are all written entirely in Go.",
        "Variables & Types": "## Strong and Static\nGo is a statically typed language, meaning the type of a variable (integer, string, boolean) is checked at compile time, catching errors before the code even runs.\n\nHowever, Go offers a 'short variable declaration' syntax (`:=`) that makes it feel as lightweight as a dynamic language like Python. \n\n```go\n// Explicit typing\nvar name string = \"Alice\"\nvar age int = 25\n\n// Short declaration (Go infers the type)\ncountry := \"Canada\"\nscore := 99.5\n```\nGo is extremely strict about unused variables. If you declare a variable but never use it, the Go compiler will flat-out refuse to compile the program. This keeps Go codebases clean and free of dead code.",
        "Functions in Go": "## Multiple Returns\nFunctions in Go look similar to other C-family languages, but they have one massive advantage: they can return multiple values simultaneously.\n\nIn Go, exceptions (like `try/catch` blocks) do not exist. Instead, functions typically return two values: the actual result, and an `error` object.\n\n```go\nfunc divide(a int, b int) (int, error) {\n    if b == 0 {\n        return 0, errors.New(\"cannot divide by zero\")\n    }\n    return a / b, nil\n}\n\nresult, err := divide(10, 2)\nif err != nil {\n    fmt.Println(\"Error:\", err)\n}\n```\nThis forces developers to explicitly handle errors immediately after they happen, leading to highly robust and crash-resistant cloud applications.",
        "Object-Oriented Go?": "## Structs over Classes\nGo is not a traditional Object-Oriented language. It has no `class` keyword, no inheritance, and no constructors.\n\nInstead, Go uses **Structs** to define custom data types (grouping variables together). To attach 'methods' to a struct, you use a special function definition called a receiver.\n\n```go\ntype User struct {\n    Name string\n    Age  int\n}\n\n// Method attached to the User struct\nfunc (u User) SayHello() {\n    fmt.Println(\"Hi, I am\", u.Name)\n}\n```\nInstead of inheritance, Go relies heavily on **Interfaces** to define behavior. This minimalist approach removes the deep, confusing class hierarchies found in Java, making Go code much easier to read and maintain.",
        "Goroutines Basics": "## Ultra-Lightweight Threads\nThe crown jewel of Go is its concurrency model: **Goroutines**.\n\nIn languages like Java or Python, creating an operating system thread is 'heavy'—it takes 1-2 megabytes of RAM. You can only run a few thousand threads before crashing the server. \n\nA Goroutine is a virtual thread managed by the Go runtime, not the OS. It starts with just 2 kilobytes of RAM. You can easily spawn 100,000 goroutines on a basic laptop.\n\nTo run a function concurrently in the background, you literally just add the word `go` in front of it:\n```go\ngo sendEmail(user)\ngo processImage(image)\n```\nThe Go scheduler automatically maps these hundreds of thousands of goroutines onto your physical CPU cores, making highly concurrent web servers trivial to write.",
        "Channels": "## Communication Between Goroutines\nWhen you have thousands of goroutines running simultaneously, they eventually need to share data. Traditional languages use shared memory and 'Locks' (Mutexes) to prevent data corruption, which is notoriously difficult to program correctly without causing deadlocks.\n\nGo encourages a different philosophy: *\"Do not communicate by sharing memory; instead, share memory by communicating.\"*\n\nGo uses **Channels**—think of them as safe, typed conveyor belts between goroutines. One goroutine can send data into the channel, and another goroutine can read data out of it. The channel handles all the locking and synchronization under the hood, making concurrent programming safe and intuitive.\n```go\nmessages := make(chan string)\ngo func() { messages <- \"ping\" }()  // Send into channel\nmsg := <-messages                   // Receive from channel\n```",
        "net/http": "## The Standard Library Web Server\nIn Python, you need a framework like Django or FastAPI, plus an application server like Gunicorn, to run a production web server. In Node.js, you need Express.\n\nGo's standard library includes the `net/http` package, which is so robust and performant that you can use it directly in production without any third-party frameworks.\n\n```go\nhttp.HandleFunc(\"/hello\", func(w http.ResponseWriter, r *http.Request) {\n    fmt.Fprintf(w, \"Hello, World!\")\n})\nhttp.ListenAndServe(\":8080\", nil)\n```\nThis tiny snippet starts a high-performance web server. Because every incoming HTTP request automatically runs in its own lightweight Goroutine, this server can handle tens of thousands of simultaneous connections right out of the box.",
        "What is Docker?": "## The Shipping Container for Code\nBefore Docker, deploying software was a nightmare. Code that worked perfectly on a developer's Mac would crash on the Linux production server because of different OS versions, missing dependencies, or conflicting Python libraries. This was the classic *\"It works on my machine\"* problem.\n\nDocker solved this by introducing **Containers**. A container packages the code, the runtime, the system tools, and the exact libraries into a single, standardized box. \n\nThink of the global shipping industry. Before standard shipping containers, loading a boat with cars, barrels, and sacks of grain was slow and custom. Standard steel containers meant ships, cranes, and trucks only had to handle one shape. Docker does this for software. If your app runs in a Docker container on your laptop, it is mathematically guaranteed to run exactly the same way on AWS, Google Cloud, or your coworker's machine.",
        "Writing a Dockerfile": "## The Blueprint\nTo create a Docker container, you write a text file called a **Dockerfile**. It acts as a step-by-step recipe for building your application's environment.\n\n```dockerfile\n# 1. Start from a lightweight Linux image with Go installed\nFROM golang:1.21-alpine\n\n# 2. Set the working directory inside the container\nWORKDIR /app\n\n# 3. Copy your code into the container\nCOPY . .\n\n# 4. Compile the Go application\nRUN go build -o myapi\n\n# 5. Define what runs when the container starts\nCMD [\"./myapi\"]\n```\nWhen you run `docker build`, Docker reads this file, executes the steps, and takes a snapshot. This snapshot is called an **Image**. You can then push this image to a registry (like Docker Hub) and pull it onto any server in the world to run it instantly.",
        "Orchestrating Containers": "## The Need for Kubernetes\nDocker is perfect for running 1 or 2 containers on a single server. But what if you are a massive bank with 5,000 containers spread across 500 different servers?\n\nIf a server catches fire, who notices and restarts those 100 containers on a healthy server? How do you route internet traffic to them? How do you upgrade them without downtime? Doing this manually is impossible.\n\nThis is where **Kubernetes (K8s)** comes in. Kubernetes is a Container Orchestrator. You give Kubernetes a cluster of servers, and you declare your desired state: *\"I want 5 copies of the Login API running at all times.\"* Kubernetes automatically schedules the containers onto the servers, monitors their health, restarts them if they crash, and manages the network load balancing between them. It acts as the intelligent operating system for your entire data center.",
        "High-Speed APIs": "## gRPC vs REST\nMost web APIs use REST, sending data back and forth as JSON strings over HTTP/1.1. While JSON is easy for humans to read, it is slow to parse and takes up a lot of bandwidth, which becomes a bottleneck when hundreds of microservices are talking to each other internally.\n\n**gRPC** (developed by Google) is a high-speed alternative designed for internal microservice communication. Instead of JSON, it uses **Protocol Buffers (Protobuf)**, which serializes data into a highly compressed, binary format. \n\nFurthermore, gRPC runs on HTTP/2, allowing multiple requests to be multiplexed over a single connection simultaneously. An internal gRPC API written in Go can be 10x faster and use a fraction of the CPU compared to a standard JSON REST API.",
        "Managing Microservices": "## The Service Mesh\nAs a company transitions from one monolithic application to 100 tiny microservices, new problems arise. How do these services securely authenticate with each other? How do you trace a request that bounces through 5 different services to find out which one is slow? How do you implement retry logic if a network hiccup occurs?\n\nWriting this complex networking and security logic directly into every microservice is a massive anti-pattern. \n\nInstead, Cloud Native architectures use a **Service Mesh** (like Istio or Linkerd). A Service Mesh injects a tiny network proxy (a sidecar) next to every single container. The microservice doesn't talk to the network directly; it talks to the proxy. The proxies handle all the mutual TLS encryption, retries, load balancing, and tracing completely transparently, allowing the developers to focus purely on business logic.",
        "K8s Operators": "## Automating Human Tasks\nKubernetes is great at managing stateless web servers. But databases are difficult. If a database goes down, you can't just restart it randomly; you have to run backups, elect a new master node, and sync data. Historically, this required a human database administrator.\n\nThe **Operator Pattern** solves this. An Operator is a custom piece of software (usually written in Go) that runs inside Kubernetes. It acts as a robot administrator that understands the specific operational rules of a complex application.\n\nFor example, if you install a PostgreSQL Operator, you can tell Kubernetes *\"Give me a 3-node Postgres cluster.\"* The Operator takes over, automatically provisioning the disks, starting the nodes, configuring replication, and watching for failures 24/7, effectively automating the human administrator's job.",
        "Go Mod Init": "## Dependency Management\nIn the early days, Go didn't have a built-in package manager like NPM for Node or Pip for Python. Code was pulled directly from the `GOPATH`, which caused massive headaches with versioning.\n\nGo Modules solved this. To start a new project, you run `go mod init github.com/yourname/project`. This creates a `go.mod` file, similar to a `package.json`. \n\nWhen you import a third-party library in your code and run `go build`, Go automatically downloads the library and records the exact cryptographic version hash in a `go.sum` file. This guarantees that if another developer clones your repository a year later, they will download the exact same versions of the dependencies, ensuring repeatable and deterministic builds.",
        "Importing Packages": "## Public by Capitalization\nIn Java or Python, you use keywords like `public`, `private`, or an underscore `_` to dictate which functions or variables can be accessed from outside a file.\n\nGo handles visibility with a brilliant, minimalist rule based on capitalization: **If a variable, function, or struct name starts with a Capital Letter, it is exported (Public). If it starts with a lowercase letter, it is unexported (Private to that package).**\n\n```go\npackage mathutils\n\n// Public - can be used in other packages\nfunc CalculateTax() { ... }\n\n// Private - only visible inside mathutils package\nfunc helperCalculation() { ... }\n```\nThis rule forces code to be instantly readable. By simply looking at the first letter of a function name anywhere in a massive codebase, you immediately know its visibility scope.",
        "Channel Basics": "## Unbuffered vs Buffered\nWhen a goroutine sends data into an **Unbuffered Channel** (`make(chan int)`), it immediately blocks and freezes until another goroutine pulls the data out of the channel. This guarantees perfect synchronization between the two threads.\n\nA **Buffered Channel** (`make(chan int, 5)`) has internal capacity. A goroutine can send up to 5 items into the channel without freezing. It only blocks when it tries to send a 6th item and the buffer is full.\n\nBuffered channels are frequently used for rate limiting and worker pools. For example, if you have 100 image processing jobs but only want to process 5 at a time to avoid crashing the server, you push the jobs into a channel buffered to 5. The worker goroutines pull jobs out, ensuring the system never exceeds its capacity.",
        "The Select Statement": "## Handling Multiple Channels\nOften, a goroutine needs to listen to multiple channels at the same time. For example, a web server might be waiting for a database query to return on `dbChannel`, but also waiting on a `timeoutChannel` in case the query takes too long.\n\nIn Go, you use the `select` statement. It looks like a `switch` statement, but it specifically waits on channel operations.\n\n```go\nselect {\ncase result := <-dbChannel:\n    fmt.Println(\"Database returned:\", result)\ncase <-time.After(2 * time.Second): // Creates a timeout channel\n    fmt.Println(\"Timeout! Database is too slow.\")\n}\n```\nThe `select` block will pause the goroutine until *one* of the cases is ready to proceed. If the database takes longer than 2 seconds, the timeout case fires, allowing the server to return an error to the user rather than freezing indefinitely.",
        "The Package Manager": "## Helm: The Package Manager for Kubernetes\nWriting raw Kubernetes YAML files by hand is tedious. A complex application might require 10 different YAML files for deployments, services, secrets, and volumes. \n\n**Helm** is the package manager for Kubernetes (think `apt` or `brew`, but for cloud infrastructure). Helm packages multiple YAML templates into a single bundle called a **Chart**.\n\nIf you want to install a complex monitoring stack like Prometheus, instead of writing thousands of lines of YAML yourself, you simply run `helm install prometheus prometheus-community/prometheus`. Helm pulls the chart from the internet, fills in the required configuration variables, and deploys all the necessary Kubernetes resources automatically.",
        "Values injected in Templates": "## Helm Templates and Values\nThe true power of Helm Charts is that the YAML files are templated. \n\nIf you have a testing environment and a production environment, you don't want to copy and paste your Kubernetes YAML files. Instead, you write one Helm Chart using placeholders. \n\n```yaml\n# deployment.yaml\nreplicas: {{ .Values.replicaCount }}\n```\nYou then provide a separate `values.yaml` file for each environment. For staging, your values file sets `replicaCount: 1`. For production, the values file sets `replicaCount: 5`. When Helm installs the chart, it injects the values into the template, generating the correct final YAML on the fly. This keeps configuration DRY (Don't Repeat Yourself).",
        "Custom Resource Definitions": "## Extending Kubernetes (CRDs)\nOut of the box, Kubernetes understands core resources like Pods (containers), Services (networking), and Deployments. But what if you want Kubernetes to understand something completely custom, like a 'DatabaseBackup' or a 'VideoRenderJob'?\n\nYou can extend the Kubernetes API by registering a **Custom Resource Definition (CRD)**. \n\nOnce registered, you can write YAML files defining a `kind: DatabaseBackup` and send them to the Kubernetes API, and it will accept them just like native resources. This extensibility is why Kubernetes transformed from a simple container manager into a universal control plane that can manage external cloud resources, databases, and custom workflows.",
        "Reconciliation Loop": "## The Control Loop\nThe core philosophy of Kubernetes is declarative state management, driven by the **Reconciliation Loop** (or Control Loop).\n\nYou do not give Kubernetes imperative commands (e.g., *'Start a new server'*). You give it a declarative state (e.g., *'There should be 3 servers running'*). \n\nThe Reconciliation Loop constantly compares the **Desired State** (what you asked for in YAML) with the **Actual State** (what is physically running in the cluster). If you asked for 3 servers, and one crashes, the Actual State is now 2. The loop detects this drift and takes immediate action to 'reconcile' the difference by spinning up a new server. This loop runs endlessly, ensuring the system is self-healing.",
        "Traffic Shifting": "## Safe Deployments in the Mesh\nWhen deploying a new version of an API, immediately routing 100% of user traffic to the new code is incredibly risky. If there's a fatal bug, the entire system crashes for everyone.\n\nA Service Mesh (like Istio) enables advanced deployment strategies like **Canary Releases** via Traffic Shifting. \n\nBecause the Service Mesh proxy controls all network routing, you can configure it to route exactly 95% of traffic to the stable Version 1, and 5% of traffic to the new Version 2. You monitor the error rates on Version 2 for an hour. If it looks healthy, you shift the traffic to 50/50, and eventually 100%. If Version 2 throws errors, you instantly shift the routing back to Version 1 without any downtime.",
        "Mutual TLS (mTLS)": "## Zero Trust Networking\nIn traditional legacy networks, perimeter security was the norm: build a strong firewall at the edge of the data center, but assume everything inside the network is safe and can talk to each other in plain text.\n\nModern cloud-native systems use a **Zero Trust** model. Even if a hacker breaches the firewall, they shouldn't be able to read the internal traffic between your microservices. \n\nA Service Mesh achieves this by enforcing **mTLS (Mutual TLS)**. When Service A talks to Service B, the sidecar proxies intercept the traffic, automatically verify cryptographic certificates on both ends (mutual authentication), and heavily encrypt the connection. This ensures that all internal microservice communication is fully encrypted and identity-verified, all without the developers having to write a single line of security code."
    }
}


if __name__ == "__main__":
    total_patched = 0
    for filename, theory_dict in TRACKS_THEORY.items():
        filepath = os.path.join("curriculum", "tracks", filename)
        if os.path.exists(filepath):
            with open(filepath, 'r', encoding='utf-8') as f:
                data = json.load(f)

            patched = 0
            for topic, topic_data in data.items():
                for lesson in topic_data.get("lessons", []):
                    if lesson.get("title") in theory_dict:
                        lesson["theory"] = theory_dict[lesson.get("title")]
                        patched += 1
                        
            with open(filepath, 'w', encoding='utf-8') as f:
                json.dump(data, f, indent=2, ensure_ascii=False)
                
            print(f"Patched {patched} lessons in {filename}")
            total_patched += patched
            
    print(f"Total patched: {total_patched}")
