import json
import os

TRACKS_THEORY = {
    "systems_programming.json": {
        "Hello Rust": "## Safety Without Garbage Collection\nRust is a modern systems programming language created to solve the biggest problems in C and C++: memory leaks and security vulnerabilities (like buffer overflows). It provides the raw speed and low-level control of C++, but with strict guarantees about memory safety.\n\nThe most unique feature of Rust is that it achieves this safety **without a Garbage Collector** (unlike Java or Python). In Garbage Collected languages, the runtime constantly pauses the program to clean up unused memory, which causes unpredictable performance spikes—unacceptable for high-frequency trading or operating systems.\n\nRust solves this at compile time. The compiler acts as an ultra-strict editor that analyzes your code. If there's any possibility of a memory error, it simply refuses to compile, forcing you to fix it before the code ever runs.",
        "Variables & Mutability": "## Immutable by Default\nIn Python or JavaScript, when you create a variable, you can change its value at any time. In Rust, variables are **immutable by default**.\n\n```rust\nlet x = 5;\nx = 6; // ERROR: Cannot assign twice to immutable variable\n```\nIf you want a variable to be changeable, you must explicitly declare it as mutable using the `mut` keyword:\n```rust\nlet mut y = 5;\ny = 6; // This is perfectly fine!\n```\nWhy does Rust do this? Immutability makes code much safer, especially in multi-threaded programs. If a variable can't change, you never have to worry about another thread modifying it while you're trying to read it.",
        "Data Types": "## Strict and Precise\nRust is a statically typed language. Every value in Rust is of a certain data type, and the compiler must know the types of all variables at compile time. \n\nWhile Rust has powerful type inference (it can often guess the type based on the value), there are times you must annotate it. Rust has very precise types for numbers to give you control over memory usage:\n- `i8`, `i16`, `i32`, `i64`: Signed integers (can be negative)\n- `u8`, `u16`, `u32`, `u64`: Unsigned integers (only positive)\n- `f32`, `f64`: Floating-point numbers\n\n```rust\nlet guess: u32 = \"42\".parse().expect(\"Not a number!\");\nlet temperature: f64 = -12.5;\n```\nThis low-level control is why systems programmers use Rust. If you only need to store numbers from 0 to 100, you use a `u8` (which takes exactly 1 byte of memory), ensuring the system is highly optimized.",
        "Functions in Rust": "## Expressions and Statements\nFunctions are pervasive in Rust code. You declare a function using the `fn` keyword. Rust requires you to specify the types of all parameters and the return type.\n\n```rust\nfn add_two_numbers(x: i32, y: i32) -> i32 {\n    let sum = x + y; // Statement (doesn't return a value)\n    sum              // Expression (returns the value - NO SEMICOLON)\n}\n```\nA crucial concept in Rust is the difference between statements and expressions. Statements perform an action but do not return a value (they end in a semicolon). Expressions evaluate to a resulting value (no semicolon). \n\nIn the function above, returning `sum` without a semicolon is an expression. If you added a semicolon (`sum;`), it would become a statement, evaluate to the empty tuple `()`, and cause a compiler error because the function promised to return an `i32`.",
        "Control Flow": "## If, Loop, and Match\nRust handles control flow mostly like other languages, but with strict boolean requirements and powerful pattern matching.\n\nUnlike Python or JavaScript, the condition in an `if` statement *must* be a strict boolean. `if 1 { ... }` will not compile; you must write `if x == 1 { ... }`.\n\nRust has standard `while` and `for` loops, but it also has a `loop` keyword for infinite loops, which you explicitly `break` out of.\n\nThe most powerful control flow tool in Rust is `match`. It is like a `switch` statement on steroids. It forces you to handle *every single possible case*. If you match on an enum representing network states, and forget to handle the `Disconnected` state, the program will refuse to compile, saving you from runtime crashes.",
        "The Ownership Rules": "## The Core of Rust\n**Ownership** is Rust's most unique feature and the reason it guarantees memory safety without a garbage collector. The rules are simple but strict:\n\n1. Each value in Rust has a variable that's called its **owner**.\n2. There can only be **one owner at a time**.\n3. When the owner goes out of scope, the value will be **dropped** (memory is freed).\n\n```rust\nlet s1 = String::from(\"hello\");\nlet s2 = s1; // Ownership MOVES to s2.\n\n// println!(\"{}\", s1); // ERROR! s1 is no longer valid.\n```\nWhen we assign `s1` to `s2`, we don't copy the string data. Instead, Rust considers `s1` invalid and moves ownership to `s2`. This prevents the infamous 'double free' error in C++ where two pointers try to free the same block of memory.",
        "Borrowing (References)": "## Letting Others Peek\nIf ownership strictly moves every time you pass a variable to a function, programming in Rust would be incredibly tedious. To solve this, Rust allows **Borrowing**.\n\nInstead of taking ownership, a function can temporarily 'borrow' a value by taking a reference to it, denoted by the ampersand `&`.\n\n```rust\nfn calculate_length(s: &String) -> usize {\n    s.len()\n}\n\nlet s1 = String::from(\"hello\");\nlet len = calculate_length(&s1); // We pass a reference\n// s1 is still valid here!\n```\nBecause `calculate_length` only takes a reference (`&String`), it borrows the value without taking ownership. When the function ends, the reference is dropped, but the actual string `s1` lives on safely in the main function.",
        "Mutable References": "## One Writer, Many Readers\nSometimes you need to borrow a value and change it. You can do this using a **Mutable Reference** (`&mut`). \n\nHowever, Rust has a very strict rule to prevent Data Races (where two threads modify the same memory at the same time causing corruption): **You can have either exactly one mutable reference, OR any number of immutable references, but not both at the same time.**\n\n```rust\nlet mut s = String::from(\"hello\");\nlet r1 = &mut s;\n// let r2 = &mut s; // ERROR: Cannot borrow `s` as mutable more than once at a time.\n```\nThis rule forces you to structure your code safely. The compiler guarantees that if you have a mutable reference to data, absolutely nobody else in the program is currently looking at or changing that data.",
        "Lifetimes": "## Preventing Dangling Pointers\nIn C++, it's incredibly easy to create a 'dangling pointer': a reference to memory that has already been freed. If you try to use that pointer, the program crashes or gets hacked.\n\nRust prevents this entirely using **Lifetimes**. A lifetime is a tag the compiler uses to ensure that a reference does not live longer than the data it points to.\n\n```rust\n// ERROR: Returns a reference to a variable that is destroyed when the function ends\n// fn dangling() -> &String {\n//     let s = String::from(\"hello\");\n//     &s\n// }\n```\nUsually, the compiler infers lifetimes automatically. But when a function takes two references and returns one, you have to explicitly annotate them (e.g., `<'a>`) to tell the compiler exactly how long the returned reference should live relative to the inputs.",
        "Threads in Rust": "## Fearless Concurrency\nConcurrency in C++ or Java is terrifying because of Data Races—silent, random bugs caused by multiple threads accessing memory simultaneously.\n\nRust coined the term **Fearless Concurrency**. The exact same Ownership and Borrowing rules that prevent memory leaks also prevent data races. If you try to share a mutable variable between two threads without using a Mutex (a lock), the Rust compiler will catch it and refuse to compile.\n\n```rust\nuse std::thread;\n\nlet handle = thread::spawn(|| {\n    println!(\"Hello from a new thread!\");\n});\n\nhandle.join().unwrap(); // Wait for the thread to finish\n```\nBecause the compiler acts as a ruthless safety inspector, if your multi-threaded Rust code compiles successfully, you can be extremely confident it will run without crashing.",
        "Reading and Writing": "## Interacting with the File System\nSystems programming heavily involves reading configs, writing logs, and processing raw files. The `std::fs` and `std::io` modules handle this.\n\n```rust\nuse std::fs::File;\nuse std::io::prelude::*;\n\n// Write to a file\nlet mut file = File::create(\"log.txt\").expect(\"Failed to create file\");\nfile.write_all(b\"System booted successfully\").expect(\"Failed to write\");\n\n// Read from a file\nlet mut file = File::open(\"log.txt\").expect(\"Failed to open\");\nlet mut contents = String::new();\nfile.read_to_string(&mut contents).expect(\"Failed to read\");\n```\nNotice the heavy use of `.expect()`. In Rust, file operations don't throw invisible exceptions. They return a `Result` enum (`Ok` or `Err`). You must explicitly handle the potential error (crashing with `expect`, or gracefully recovering), forcing you to build robust systems.",
        "Code that writes Code": "## Rust Macros\nSometimes you need to write repetitive code, or you want a function that takes a variable number of arguments. In Rust, you use **Macros** (denoted by the `!` at the end, like `println!`).\n\nUnlike C macros (which are just dumb text substitution and very dangerous), Rust macros are hygienic and work at the Abstract Syntax Tree (AST) level. They are essentially 'code that writes code' during the compilation process.\n\nFor example, `vec![1, 2, 3]` is a macro that expands into the necessary boilerplate code to create a new vector and push three elements into it. Macros allow libraries like `Serde` to automatically generate hundreds of lines of JSON parsing code for your structs just by adding a `#[derive(Serialize)]` annotation above them.",
        "The Unsafe Keyword": "## Taking Off the Training Wheels\nRust's strict safety rules are amazing, but sometimes you need to do things the compiler can't prove are safe. For example, talking directly to the operating system, writing a hardware driver, or interacting with a C library.\n\nFor this, Rust provides the `unsafe` keyword. \n\n```rust\nunsafe {\n    // Dereference a raw memory pointer\n    // Call an external C function\n}\n```\n`unsafe` doesn't turn off the compiler; it just allows you to perform four specific dangerous operations (like dereferencing raw pointers). The beauty of this design is isolation. If a memory bug happens in a 100,000-line Rust codebase, you don't have to check the whole codebase—you only have to audit the few small blocks wrapped in `unsafe`.",
        "Foreign Function Interface": "## Talking to C (FFI)\nRust doesn't exist in a vacuum. The world runs on C. Operating systems, database engines (SQLite), and encryption libraries (OpenSSL) expose C APIs. \n\nA **Foreign Function Interface (FFI)** allows Rust to call C code, and C to call Rust code, with zero performance overhead.\n\n```rust\nextern \"C\" {\n    // Tell Rust this C function exists in an external library\n    fn abs(input: i32) -> i32;\n}\n\nfn main() {\n    unsafe {\n        // Calling C code is inherently unsafe!\n        println!(\"Absolute value of -3 according to C is: {}\", abs(-3));\n    }\n}\n```\nThis allows companies to slowly rewrite massive, buggy C++ codebases by replacing them one function at a time with safe Rust code, compiling it down to a standard C-compatible binary.",
        "Sockets": "## Network Programming at the Lowest Level\nWhen a web browser connects to a web server, it uses **Sockets**. A socket is a software endpoint for sending and receiving data across the network.\n\nIn systems programming, you don't always use high-level HTTP libraries. Sometimes you build custom protocols using raw TCP or UDP sockets. \n\n```rust\nuse std::net::TcpListener;\n\nlet listener = TcpListener::bind(\"127.0.0.1:8080\").unwrap();\n\nfor stream in listener.incoming() {\n    let stream = stream.unwrap();\n    println!(\"Connection established!\");\n    // Read raw bytes from the stream...\n}\n```\nThis is how databases, game servers, and high-frequency trading platforms communicate. They bypass the overhead of HTTP and send tightly packed binary data directly over TCP sockets for maximum speed.",
        "Pointers and References": "## The Arrow to the Data\nA pointer is simply a variable that stores the memory address of another variable. \n\nIn C and C++, you use **Raw Pointers** (`int* ptr`). They are extremely fast but incredibly dangerous. You can accidentally point to memory that has been deleted, or overwrite data belonging to another program.\n\nIn Rust, you mostly use **References** (`&T`). A reference is a type of pointer, but it is guaranteed by the compiler to always point to a valid, existing piece of data. If you absolutely need raw, unchecked memory access (e.g., writing a memory allocator), Rust forces you to use raw pointers (`*const T`) and wrap the access in an `unsafe` block.",
        "RAII Paradigm": "## Resource Acquisition Is Initialization\n**RAII** is a fundamental programming concept invented in C++ and heavily adopted by Rust. \n\nThe core idea is simple: the lifespan of a resource (like an open file, a network socket, or allocated memory) is tied directly to the lifespan of an object.\n\nWhen a `File` object is created, it automatically opens the file on the hard drive (Acquisition). When that object goes out of scope at the end of the function, its `drop` method is automatically called, and the file is safely closed. \n\nYou never have to write `file.close()` or `memory.free()`. The compiler inserts the cleanup code automatically the moment the variable goes out of scope, completely eliminating resource leaks.",
        "Spawning Threads": "## OS-Level Concurrency\nUnlike Go (which uses lightweight virtual goroutines), Rust's `std::thread::spawn` maps directly 1-to-1 to actual Operating System threads.\n\nOS threads are heavier to create, but they offer maximum performance and control. Because they map directly to hardware threads on your CPU core, they are ideal for CPU-bound tasks like heavy mathematical computations, video encoding, or game engines.\n\n```rust\nuse std::thread;\n\n// Spawn a new OS thread\nlet handle = thread::spawn(|| {\n    // Heavy computation here\n});\n```\nWhen you spawn a thread, the OS scheduler decides when it gets CPU time. Because threads share the same physical memory space, coordinating them is the hardest part of systems programming.",
        "Data Races and Mutexes": "## Protecting Shared Memory\nA **Data Race** occurs when Thread A is trying to read a variable while Thread B is simultaneously modifying it. The result is garbage data and catastrophic crashes.\n\nTo prevent this, systems programmers use a **Mutex** (Mutual Exclusion lock). \n\n```rust\nuse std::sync::Mutex;\n\nlet m = Mutex::new(5);\n\n{\n    // Lock the mutex. If another thread has it, we freeze and wait.\n    let mut num = m.lock().unwrap();\n    *num = 6; \n} // The lock is automatically released here (RAII!)\n```\nIn C++, if you forget to lock the mutex before reading the data, the code compiles but crashes in production. In Rust, the data is stored *inside* the Mutex. The compiler literally makes it impossible to read the data without calling `.lock()` first.",
        "The open() Syscall": "## Talking to the Kernel\nYour application code runs in 'User Space'. It doesn't actually have the power to touch the hard drive, read the keyboard, or send network packets. \n\nWhen you want to open a file, your code must make a **System Call (Syscall)** to the Operating System Kernel (which runs in privileged 'Kernel Space'). \n\nIn C or Rust, calling `File::open()` eventually triggers the OS-level `open()` syscall. The CPU pauses your program, switches into high-privilege kernel mode, checks if you have file permissions, instructs the hard drive hardware to find the file, and hands a 'File Descriptor' back to your program. Understanding syscalls is the bridge between writing software and understanding how hardware actually works.",
        "Forking Processes": "## How Programs Clone Themselves\nIn Unix/Linux systems, how do you start a new program? You use the `fork()` syscall.\n\nWhen a program calls `fork()`, the Operating System creates an exact, identical clone of the running process. It copies the memory, the variables, and the open files. You now have a Parent process and a Child process running simultaneously.\n\nImmediately after forking, the Child process usually calls the `exec()` syscall, which replaces the cloned memory with a brand new program (like `ls` or `python`). This `fork/exec` pattern is exactly how your terminal shell launches every single command you type.",
        "Bitwise Operations": "## Manipulating 1s and 0s\nAt the very bottom of the stack, everything is binary. Systems programmers frequently need to read or flip individual bits within a byte, especially when writing hardware drivers or network protocols.\n\nBitwise operators manipulate data at the bit level:\n- **AND (`&`):** Used to check if a specific bit is a 1 (Masking).\n- **OR (`|`):** Used to flip a specific bit to 1 (Setting).\n- **XOR (`^`):** Flips a bit to its opposite.\n- **Shift (`<<`, `>>`):** Moves all bits left or right (a fast way to multiply or divide by 2).\n\n```rust\nlet flags: u8 = 0b0000_1010; // Binary literal\nlet mask: u8  = 0b0000_0010;\n\n// Check if the 2nd bit is set\nif flags & mask != 0 {\n    println!(\"Bit is set!\");\n}\n```",
        "Volatile Keyword": "## Don't Optimize This!\nCompilers are incredibly smart. If they see you write `x = 5; x = 10;`, the compiler will aggressively optimize the code by completely deleting `x = 5;` because it seems useless.\n\nHowever, in embedded systems programming (writing code for microcontrollers), memory addresses map directly to hardware pins. Writing `x = 5` might turn on a motor, and `x = 10` might turn it off. If the compiler deletes the first command, the motor never spins!\n\nIn C (and via `read_volatile` / `write_volatile` in Rust), you use the **Volatile** concept. It tells the compiler: *\"Do exactly what I wrote. Do not optimize this memory access, because something outside the CPU (hardware) is watching this exact memory address.\"*",
        "Module Initialization": "## Structuring Systems Code\nLarge systems (like OS kernels or big Rust apps) require complex startup sequences. You can't just throw everything in `main()`. \n\nYou have to initialize the memory allocator, then the interrupt handlers, then the hardware drivers, in a very specific order.\n\nRust handles large projects using **Modules** (`mod`). Modules allow you to group related functions, structs, and traits into separate files and directories. A `lib.rs` or `main.rs` file acts as the root, declaring which modules are pulled into the project. This encapsulation ensures that the complex low-level hardware initialization code is completely hidden from the high-level application logic.",
        "Printing to Kernel Log": "## Debugging Without a Screen\nWhen you are writing an Operating System kernel or a low-level driver, you cannot use `printf()` or `println!()`. Those high-level functions require a working Operating System and a terminal to display text—but *you are* the operating system!\n\nInstead, kernel developers write directly to a hardware serial port or a specific VGA memory buffer. In Linux, drivers use the `printk()` function, which writes directly to the kernel ring buffer. You read this buffer later using the `dmesg` command.\n\nIn custom Rust kernels, you have to write your own macro (e.g., `serial_println!`) that talks directly to the CPU's I/O ports to squirt text out of a physical serial cable to another computer just to see your debug messages."
    },
    "mobile_development.json": {
        "What is React Native?": "## Learn Once, Write Anywhere\nHistorically, if a company wanted a mobile app, they had to hire two entirely separate teams: Swift/Objective-C developers for iOS, and Java/Kotlin developers for Android. This was incredibly expensive and slow.\n\n**React Native**, created by Facebook, changed the industry. It allows developers to write an app using JavaScript and the React framework, and deploy it to *both* iOS and Android from a single codebase.\n\nUnlike older tools (like Cordova) that just wrapped a web page in a mobile frame, React Native actually compiles your JavaScript UI components into native iOS and Android UI elements. A `<View>` in React Native becomes a real `UIView` on iOS and a `ViewGroup` on Android, providing the true speed, feel, and performance of a native app.",
        "View and Text": "## The Building Blocks\nIf you come from web development, you are used to using HTML tags like `<div>`, `<span>`, and `<h1>`.\n\nIn React Native, there is no HTML or DOM. You cannot use a `<div>`. Instead, React Native provides primitive mobile components:\n- `<View>` is the fundamental container (the equivalent of a `div`). It supports layout using Flexbox.\n- `<Text>` is the only component that can contain text (like a `p` or `span`). If you try to put raw text inside a `<View>`, the app will crash.\n- `<Image>` displays graphics.\n\n```jsx\n<View style={{ flex: 1, justifyContent: 'center' }}>\n  <Text style={{ fontSize: 24 }}>Hello Mobile World!</Text>\n</View>\n```\nAll styling is done using JavaScript objects that look almost identical to CSS, making the transition for web developers extremely fast.",
        "React Navigation": "## Moving Between Screens\nOn a website, navigating to a new page involves the browser requesting a new URL. Mobile apps don't have URLs in the same way. They use **Stacks** and **Tabs**.\n\n**React Navigation** is the industry-standard library for handling this in React Native.\n- **Stack Navigator:** Imagine a stack of playing cards. When you tap a profile, a new screen slides in *on top* of the current screen. When you hit the physical 'Back' button, the top screen is popped off the stack, revealing the previous screen underneath.\n- **Tab Navigator:** The persistent buttons at the bottom of the screen (e.g., Home, Search, Profile) that allow you to switch instantly between parallel stacks.\n\nManaging the navigation state properly is crucial, otherwise users get trapped in endless stacks of screens.",
        "Web APIs": "## Fetching Data\nMobile apps are rarely standalone; they almost always need to talk to a backend server to get data (like fetching a feed of posts).\n\nFortunately, React Native provides the exact same **Fetch API** that standard web browsers use. You don't need to learn a complex mobile networking library.\n\n```javascript\nfetch('https://api.example.com/users')\n  .then(response => response.json())\n  .then(data => console.log(data))\n  .catch(error => console.error(error));\n```\nYou trigger these network calls exactly as you would in React web: usually inside a `useEffect` hook when a component first mounts, saving the resulting data into state variables to trigger a UI re-render.",
        "AsyncStorage": "## Local Persistence\nWhen a user closes an app and reopens it, they shouldn't have to log in again. You need to save their session token directly onto the phone's hard drive.\n\nIn a web browser, you use `localStorage`. In React Native, you use **AsyncStorage**. \n\nAsyncStorage is a simple, unencrypted, asynchronous, persistent, key-value storage system. Because reading from the phone's flash memory takes time, all AsyncStorage methods return Promises, meaning you must use `await` when reading or writing data.\n\n*Note:* Because it is unencrypted, you should never store passwords or credit card numbers in AsyncStorage. For highly sensitive data, you must use native iOS Keychain or Android Keystore libraries.",
        "Animated API": "## Bringing UIs to Life\nA mobile app without animations feels rigid and broken. When a user taps a button, it should visually respond. When a panel opens, it should slide smoothly, not instantly snap.\n\nReact Native provides the powerful **Animated API**. It allows you to define animated values and bind them directly to the styling properties of components (like opacity, scale, or X/Y position).\n\n```javascript\nconst fadeAnim = useRef(new Animated.Value(0)).current;\n\n// Trigger the animation\nAnimated.timing(fadeAnim, {\n  toValue: 1,\n  duration: 1000,\n  useNativeDriver: true // CRITICAL for performance\n}).start();\n```\nThe `useNativeDriver` flag is the most important concept here. It sends the animation mathematical curve completely out of JavaScript and into the native iOS/Android layer. This means even if the JavaScript thread is totally frozen calculating heavy data, your animations will still run at a silky smooth 60 frames per second.",
        "Expo vs CLI": "## The Great React Native Debate\nWhen you start a React Native project, you face a major architectural choice: use the bare **React Native CLI**, or use **Expo**.\n\n**Expo** is a framework built around React Native. It hides all the complex iOS and Android configuration files. You don't need to open Xcode or Android Studio. You can build an app and test it on your physical phone in 2 minutes. However, historically, if you needed a custom Bluetooth library that Expo didn't support, you were stuck.\n\n**Bare CLI** gives you full control. You have the raw iOS and Android project folders and can inject custom Swift or Kotlin code whenever you want. However, upgrading versions is notoriously painful and requires deep native knowledge.\n\nToday, Expo is so advanced (with features like Custom Dev Clients) that the official React Native documentation explicitly recommends using Expo for almost all new projects.",
        "Bridging to Swift/Kotlin": "## Touching the Metal\nReact Native covers 95% of what a mobile app needs. But sometimes you hit an edge case. Maybe you need to interface with a proprietary credit card swiper hardware that only provides a Swift and Kotlin SDK.\n\nIn this scenario, you write a **Native Module** (a Bridge).\n\nYou write the low-level Swift code to talk to the hardware on iOS. You then expose specific functions (like `swipeCard()`) to JavaScript via a bridging header. On the JavaScript side, you simply call `NativeModules.CardSwiper.swipeCard()`. This gives React Native the ultimate escape hatch: you get the speed of writing UI in JS, with the raw power of accessing any native device feature when necessary.",
        "The JS Bridge": "## How It Actually Works\nHow does JavaScript code written on a laptop tell an iPhone to render a physical button?\n\nReact Native runs two main threads concurrently: the **Main Thread** (which handles the native UI rendering and user touches) and the **JS Thread** (which runs your React logic).\n\nThey communicate across **The Bridge**. The JS Thread figures out that a button needs to be rendered, serializes that instruction into a JSON message, and shoots it across the Bridge to the Native thread. The Native thread reads the JSON and physically draws the button on the screen.\n\nThis architecture is why passing massive amounts of data back and forth across the bridge (like a 60fps video stream) causes lag. (Note: Modern React Native is currently rolling out the JSI architecture to replace the bridge, allowing direct synchronous memory access!).",
        "Widgets are Everything": "## The Flutter Philosophy\nWhile React Native uses React components, Google's **Flutter** takes a completely different approach: *Everything is a Widget*.\n\nIn Flutter, the app itself is a widget. The layout is a widget. The buttons are widgets. Even the padding and alignment are separate widgets. You build UIs by snapping together complex, deeply nested trees of widgets.\n\nUnlike React Native (which uses native iOS/Android UI elements), Flutter has its own ultra-fast 2D rendering engine (Skia). Flutter draws every single pixel on the screen itself. This guarantees that an app looks 100% identical on an iPhone 15 and a 5-year-old Android phone, but it means it bypasses the native OS UI components entirely.",
        "Stateful vs Stateless": "## Managing Component Memory\nIn mobile development (whether React Native or Flutter), components fall into two categories: Stateful and Stateless.\n\n- **Stateless Components** are dumb. You pass them data (Props), and they render it. If the data doesn't change, they don't change. A static Header or a custom Button is usually stateless.\n- **Stateful Components** have memory. They hold variables (State) that change over time, like the text in a search input, or a boolean tracking if a modal is open or closed.\n\nWhenever the 'State' of a component changes, the framework automatically re-renders that component (and its children) to reflect the new data. Managing exactly *when* and *why* state changes is the hardest part of mobile architecture.",
        "Zustand Setup": "## Modern State Management\nIn a large app, you have data that many screens need to access (like the User's Profile or their Shopping Cart). Passing this data manually from screen to screen via props is a nightmare known as 'Prop Drilling'.\n\nYou need Global State Management. While Redux is famous, **Zustand** has become the modern favorite for React Native because it is incredibly lightweight and simple.\n\n```javascript\nimport create from 'zustand'\n\n// Create a global store\nconst useStore = create((set) => ({\n  bears: 0,\n  increasePopulation: () => set((state) => ({ bears: state.bears + 1 })),\n}))\n\n// Use it anywhere in your app\nconst bears = useStore((state) => state.bears)\n```\nWith Zustand, any component can reach into the global store, grab the data it needs, and automatically re-render when that specific data updates.",
        "Redux Toolkit": "## The Heavyweight Champion\nFor massive enterprise applications, **Redux Toolkit (RTK)** remains the industry standard for global state management.\n\nRedux enforces a very strict, predictable architectural pattern:\n1. **State:** A single, massive JSON object holding all app data.\n2. **Actions:** If a component wants to change data, it cannot modify it directly. It must 'dispatch' an Action (a description of what happened, e.g., 'ADD_TO_CART').\n3. **Reducers:** Pure functions that receive the Action, calculate the new state, and return a brand new State object.\n\nWhile traditional Redux required hundreds of lines of boilerplate code, Redux Toolkit streamlines this massively, automatically configuring the store and providing tools for efficient API caching (RTK Query).",
        "Requesting Permissions": "## Respecting User Privacy\nMobile operating systems heavily restrict what an app can do. If your app needs the camera, location, or microphone, it will crash if it tries to access them without permission.\n\nIn React Native, you must explicitly ask the user for permission using the OS prompts.\n\nFor iOS, you must add specific keys to your `Info.plist` file (e.g., `NSCameraUsageDescription`), explaining exactly *why* you need the camera. If you don't provide a good reason, Apple will reject your app during the App Store review. In the code, you use libraries like `expo-location` or `react-native-permissions` to trigger the popup, check if the user said 'Yes', and gracefully handle the scenario where they say 'No'.",
        "Handling Foreground Messages": "## Push Notifications\nPush Notifications are critical for retaining users. They involve three parties: Your app, Your Backend Server, and APNs/FCM (Apple/Google notification services).\n\nWhen a user installs your app, it requests a unique **Push Token** from Apple/Google. Your app sends this token to your backend database.\n\nWhen your backend wants to alert the user, it sends a message (containing the token) to Apple/Google's servers, which then wake up the physical phone. \n\nHandling notifications is tricky because behavior changes based on app state. If the app is in the **Background/Closed**, the OS displays a standard banner popup. But if the app is in the **Foreground** (currently open and being used), the OS usually blocks the banner. You have to write custom code to intercept the foreground message and show a custom in-app toast notification.",
        "AsyncStorage / SQLite": "## Offline-First Architecture\nUsers expect mobile apps to open instantly and work even when they are on a subway with no cellular connection. This requires an **Offline-First** architecture.\n\nInstead of fetching data from the internet every time the app opens, the app reads data from a local database instantly. \n- For simple key-value pairs (like user settings), use **AsyncStorage**.\n- For complex relational data (like thousands of chat messages or a product catalog), you use a local **SQLite** database built directly into the phone.\n\nWhen the internet connection returns, a background sync engine silently reaches out to your API, pulls down any new data, updates the local SQLite database, and the UI automatically re-renders with the fresh data.",
        "Sync Queues": "## Making Changes Offline\nWhat happens if a user 'Likes' a post while they are offline on a subway?\n\nThe app shouldn't show an error. Instead, it uses a **Sync Queue** (optimistic UI updates). \n\n1. The app immediately updates the local UI (turning the heart red) so the user feels it worked instantly.\n2. It writes a 'Like Post ID 123' task into a local Queue table in SQLite.\n3. The app listens for the OS network status to change to 'Online'.\n4. Once online, a background worker reads the Queue and attempts to send the API request to the backend. \n5. If the server is down, the task stays in the queue and retries later using exponential backoff.",
        "Fastlane Basics": "## Automating Mobile Releases\nBuilding and releasing mobile apps is a miserable, manual process. You have to increment version numbers, generate cryptographic signing certificates, take screenshots, build the `.ipa` (iOS) and `.apk` (Android) files, and manually upload them to the Apple and Google portals.\n\n**Fastlane** is an open-source tool written in Ruby that automates this entire process. \n\nYou define a `Fastfile`. With a single command in your terminal (`fastlane deploy`), Fastlane automatically increments the build number, signs the app, builds the binaries, uploads them to TestFlight and the Google Play Console, and even posts a message in your team's Slack channel saying the new beta is ready.",
        "EAS Build (Expo)": "## Compiling in the Cloud\nIf you use Expo, you don't even need Fastlane or a powerful Mac. Expo provides **EAS (Expo Application Services)**.\n\nHistorically, to compile an iOS app, you absolutely had to own an Apple Mac computer to run Xcode. With EAS Build, you run `eas build --platform ios` in your terminal. \n\nExpo zips up your JavaScript code, uploads it to their massive server farm of Macs in the cloud, compiles the native iOS and Android binaries for you, and gives you a link to download the finished app. It handles all the nightmare-inducing Apple certificates and provisioning profiles automatically.",
        "Everything is a Widget": "## The Building Blocks of Flutter\nTo reiterate a core concept of Flutter: Everything is a widget. \n\nIn Android or iOS native development, an application, a layout, and a button are fundamentally different types of software objects. In Flutter, they all inherit from the exact same Widget class.\n\nIf you want to center text, you don't apply a CSS style. You wrap the `Text` widget inside a `Center` widget. If you want padding, you wrap it in a `Padding` widget. This compositional approach results in deeply nested code (the infamous 'Widget Tree'), but provides unparalleled flexibility because you can combine widgets in infinite ways.",
        "Dart Language Basics": "## Google's Alternative to JavaScript\nTo write Flutter apps, you must learn **Dart**. Dart is an object-oriented, strongly typed language created by Google. \n\nIf you know Java, C#, or JavaScript, Dart will feel instantly familiar. It was designed to be easy to learn and highly optimized for building user interfaces.\n\nDart has a killer feature called **Sound Null Safety**. In older languages (like Java), any variable could unexpectedly be `null`, leading to the infamous 'Null Pointer Exception' crashing the app. In Dart, variables cannot be null by default. If a variable *might* be null, you must explicitly declare it with a question mark (e.g., `String? name`). The compiler then forces you to write code handling the null case before it allows the app to compile, eliminating an entire category of crashes.",
        "Layouts in Flutter": "## Rows and Columns\nFlutter does not use CSS or Flexbox (like React Native does). Instead, layout is entirely managed by layout widgets, primarily **Rows** and **Columns**.\n\n- A **Column** arranges its children vertically.\n- A **Row** arranges its children horizontally.\n\nTo control spacing, you use properties like `MainAxisAlignment` (how children are distributed along the primary axis) and `CrossAxisAlignment`. \n\nIf the items inside a Column are too tall and go off the screen, Flutter will throw a bright yellow warning tape error on the screen. To fix this, you don't add CSS overflow properties; you simply wrap the Column in a `SingleChildScrollView` widget, instantly making it scrollable.",
        "State Management with Provider": "## Flutter's Preferred State Tool\nJust like React Native needs Zustand or Redux, Flutter needs global state management. While many exist (Bloc, Riverpod), **Provider** is the official recommendation for beginners.\n\nProvider acts as a dependency injection system. You create a class that holds your data and extends `ChangeNotifier`. \n\n```dart\nclass CartModel extends ChangeNotifier {\n  int items = 0;\n  void add() {\n    items++;\n    notifyListeners(); // Tells the UI to update\n  }\n}\n```\nYou wrap your app in a `ChangeNotifierProvider`. Deep down in the widget tree, any widget can use `context.watch<CartModel>()` to read the data. When `notifyListeners()` is called, only the specific widgets watching that model are efficiently rebuilt.",
        "Routing and Navigation": "## The Navigator 2.0\nRouting in Flutter is managed by the `Navigator` widget, which manages a stack of Route objects.\n\nFor simple apps, you can use **Imperative Routing**:\n```dart\n// Push a new screen on top of the stack\nNavigator.push(context, MaterialPageRoute(builder: (context) => DetailsScreen()));\n\n// Pop the current screen off the stack (go back)\nNavigator.pop(context);\n```\nHowever, for complex apps (especially Flutter Web apps where you need the browser back button to work perfectly), you use the more complex **Navigator 2.0 (Declarative Routing)** via packages like `go_router`. This defines routes as a strict tree of URLs, making deep-linking (opening the app directly to a specific product page from an email link) incredibly robust.",
        "API Integration": "## http and json_serializable\nTo fetch data from a REST API in Flutter, you typically use the official `http` package.\n\nBecause Dart is strongly typed, you cannot just parse JSON into a random JavaScript object. You must explicitly define a Dart class that mirrors the JSON structure.\n\n```dart\nfinal response = await http.get(Uri.parse('https://api.com/user'));\nif (response.statusCode == 200) {\n  // Decode JSON string to Map, then to strong Dart object\n  var data = jsonDecode(response.body);\n  return User.fromJson(data);\n}\n```\nWriting the `fromJson` methods by hand is tedious. Most professional Flutter developers use code generation tools like `json_serializable` or `freezed`, which automatically write all the JSON parsing code for you, ensuring type safety without the boilerplate.",
        "Animations in Flutter": "## Built-In Brilliance\nAnimations are where Flutter absolutely outshines every other framework. Because Flutter controls the 2D rendering engine directly, creating complex 60fps animations is astonishingly easy.\n\nFlutter provides **Implicit Animations**. You don't have to manage math or animation controllers. You simply swap a standard widget for an animated one. \n\nFor example, instead of a `Container`, you use an `AnimatedContainer`. If you change its width from 100 to 200 based on state, you don't just see it snap to 200. The `AnimatedContainer` automatically interpolates the values and smoothly animates the width change over a specified duration. For more complex, character-based animations, Flutter integrates flawlessly with Rive and Lottie.",
        "Publishing to App Stores": "## The Final Hurdle\nThe hardest part of mobile development is often just getting the app approved and published.\n\n**Google Play Store:** Generally lenient. You pay a one-time $25 fee. The review process takes a few days. The biggest hurdle for new accounts is Google's recent rule requiring you to find 20 real people to test your app for 14 continuous days before they allow you to publish it to production.\n\n**Apple App Store:** Extremely strict. You must pay $99 every single year. The app is reviewed by human testers who will ruthlessly reject it if it crashes, uses private APIs, has a poor user interface, or tries to bypass Apple's 30% payment cut. You must provide test accounts and detailed explanations of every permission you use."
    }
}


if __name__ == "__main__":
    total_patched = 0
    for filename, theory_dict in TRACKS_THEORY.items():
        filepath = os.path.join("curriculum", "tracks", filename)
        if os.path.exists(filepath):
            with open(filepath, 'r', encoding='utf-8') as f:
                data = json.load(f)

            patched = 0
            for topic, topic_data in data.items():
                for lesson in topic_data.get("lessons", []):
                    if lesson.get("title") in theory_dict:
                        lesson["theory"] = theory_dict[lesson.get("title")]
                        patched += 1
                        
            with open(filepath, 'w', encoding='utf-8') as f:
                json.dump(data, f, indent=2, ensure_ascii=False)
                
            print(f"Patched {patched} lessons in {filename}")
            total_patched += patched
            
    print(f"Total patched: {total_patched}")
