import json
import os

TRACK = "curriculum/tracks/system_design_architecture.json"

THEORY = {
    "The Core of the Web": "## Client-Server Model\nThe internet operates primarily on the **Client-Server model**. Think of a restaurant: the customer (client) looks at the menu and places an order, while the kitchen (server) receives the order, prepares the food, and serves it back. \n\nIn web terms, your browser or mobile app is the **client**. When you type a URL or click a button, the client sends an **HTTP Request** over the internet. The **server** is a powerful computer living in a data center somewhere that receives this request, processes any business logic, fetches data from a database, and sends back an **HTTP Response** (usually HTML or JSON data). \n\nUnderstanding this request-response cycle is the absolute foundation of System Design. Every complex architecture you build is ultimately just a web of clients and servers talking to each other.",
    "Directing Traffic": "## Load Balancing\nWhen a single server receives too many requests, it gets overwhelmed and crashes. To fix this, we introduce a **Load Balancer**. \n\nImagine a busy supermarket with only one checkout lane (a single server). The line gets too long, and customers get angry. The solution is to open multiple checkout lanes and have a manager at the front directing each new customer to the shortest line. \n\nIn system design, a **Load Balancer** sits in front of multiple servers. When a client sends a request, it hits the load balancer first. The load balancer then forwards the request to one of the available servers based on a specific algorithm (like Round Robin or Least Connections). This ensures no single server is overwhelmed, providing **high availability** and allowing you to scale horizontally by just adding more servers.",
    "Why Cache?": "## The Need for Speed\nFetching data from a hard drive or running complex database queries takes time. **Caching** is the strategy of storing copies of frequently accessed data in ultra-fast, temporary storage (usually RAM).\n\nThink of a library. The database is the main archive in the basement—it holds every book, but it takes 10 minutes to go down and find one. A cache is like a small display shelf right next to the librarian's desk. When a popular new book is requested, the librarian fetches it from the basement once, but keeps it on the display shelf. The next 100 people who ask for it get it instantly.\n\nIn systems, we use tools like **Redis** or **Memcached**. When a user requests data, the server checks the cache first (a *Cache Hit*). If it's not there (a *Cache Miss*), it queries the database, returns the data, and saves a copy in the cache for next time. Caching is the single most effective way to improve system performance.",
    "Splitting Data": "## Sharding and Partitioning\nAs a database grows to terabytes of data, a single machine can no longer hold it all or query it efficiently. The solution is **Database Sharding** (or partitioning) — splitting a massive database into smaller, manageable chunks across multiple machines.\n\nImagine a phonebook for the entire world. Finding one name would take forever. Instead, you split the phonebook into volumes: Volume A-H, Volume I-P, and Volume Q-Z. If you need to look up 'Smith', you instantly know to grab the third volume, completely ignoring the others.\n\nIn a database, you might shard users by their `user_id`. Users 1 to 1 Million go to Database A, 1M to 2M go to Database B, etc. This is called a **Shard Key**. While sharding provides massive scalability, it introduces complexity: joining data across different shards is extremely difficult, and if your shard key is poorly chosen, one database might end up doing all the work (a *Hot Shard*).",
    "Decoupling Systems": "## Message Queues\nIn a monolithic system, when Component A needs Component B to do something, it calls it directly and waits for the response. If Component B is slow or crashes, Component A is stuck waiting. To solve this, we use **Message Queues** to *decouple* the system.\n\nThink of a restaurant drive-thru. If the cashier taking your order had to personally cook your burger before taking the next car's order, the line would not move. Instead, the cashier takes your order, writes it on a ticket, and puts it on an order rail (the queue). The cooks (consumers) pull tickets from the rail as fast as they can cook them. The cashier doesn't wait; they immediately take the next order.\n\nIn system design, a web server (Producer) sends a 'job' to a Message Queue (like RabbitMQ or Kafka). A background worker (Consumer) reads the job and processes it. This ensures that a sudden spike in traffic doesn't crash the system; the queue just gets temporarily longer while the workers catch up.",
    "CAP Theorem": "## Consistency, Availability, Partition Tolerance\nThe **CAP Theorem** is a fundamental principle of distributed systems. It states that a distributed data store can only guarantee **two out of the following three** properties at the same time: \n\n1. **Consistency (C):** Every read receives the most recent write or an error. (All nodes see the exact same data at the same time).\n2. **Availability (A):** Every request receives a non-error response, without the guarantee that it contains the most recent write. (The system is always on).\n3. **Partition Tolerance (P):** The system continues to operate despite an arbitrary number of messages being dropped or delayed by the network between nodes. (The system survives network failures).\n\nBecause network partitions (P) are a reality of the physical internet (cables break, switches fail), a distributed system *must* be Partition Tolerant. Therefore, when a network failure occurs, the architect must make a difficult choice: Do we sacrifice Consistency or Availability?",
    "Pick Two": "## CP vs AP Systems\nWhen a network partition happens (e.g., Data Center A loses connection to Data Center B), you are forced to choose between **Consistency (CP)** and **Availability (AP)**.\n\nIf you choose **CP (Consistency + Partition Tolerance)**, you prioritize making sure data is accurate. If a user tries to read data from a node that cannot be updated because of the partition, the node will return an error or timeout rather than returning stale data. This is crucial for banking or financial systems where an incorrect balance is disastrous.\n\nIf you choose **AP (Availability + Partition Tolerance)**, you prioritize keeping the system up. The disconnected node will continue to accept reads and writes, even though it can't sync with the rest of the network. This means users might see slightly outdated information, but the app keeps working. This is acceptable for social media feeds or 'Likes' on a post, where temporary staleness is better than an error screen.",
    "Who is the Leader?": "## Leader Election and Consensus\nIn a distributed database cluster, multiple servers (nodes) hold copies of the same data. If two users try to update the same record on two different nodes at the same time, whose update wins? To resolve this, systems often elect a **Leader**.\n\nThink of a group project. If everyone tries to edit the final essay at the same time without talking, it becomes a mess. Instead, the group elects one person to be the 'Leader'. All changes must be handed to the leader, who applies them in order and then shares the updated essay with the 'Followers'. \n\nIn systems like Kafka or MongoDB, one node is designated the Leader. All **Write** requests must go to the Leader. The Leader writes the data and then streams the changes to the Follower nodes. If the Leader crashes, the Followers use an algorithm (like Paxos or Raft) to vote and immediately elect a new Leader, ensuring the system stays online.",
    "Real-time Location": "## Geospacial Indexing\nApps like Uber, Tinder, and Yelp need to answer a very specific query instantly: *\"Find all users/restaurants within a 5-mile radius of my current GPS coordinates.\"* Doing a mathematical distance calculation against every row in a database would be impossibly slow.\n\nTo solve this, we use **Geospatial Indexing**, such as **Geohashes** or **Quadtrees**. A Geohash takes a 2D coordinate (latitude and longitude) and maps it into a short string of letters and numbers (e.g., `9q8yy`). The brilliant part of a Geohash is that locations that are physically close together share the same prefix. \n\nFor example, if you are at `9q8yy`, you can easily find nearby drivers by querying the database for all drivers whose Geohash also starts with `9q8y`. This turns a complex, slow mathematical operation into a lightning-fast string prefix match in the database.",
    "Matching Algorithm": "## Ride Matching in Uber\nHow does Uber instantly match you with a driver? It requires combining geospatial data, real-time state, and distributed messaging.\n\nWhen a driver goes online, their app sends their GPS location to a server every few seconds. This data is ingested and placed into an in-memory geospatial cache (like Redis with Geo commands) and updated constantly. \n\nWhen you request a ride, the system queries this cache to find the 10 closest drivers. It then calculates the exact ETA for each driver using a routing engine. The system sends a notification to the closest driver. If they decline or don't answer within 10 seconds, the system seamlessly routes the request to the second-closest driver. This is all coordinated using fast, in-memory databases and Pub/Sub messaging systems to ensure low latency.",
    "Video Streaming": "## How Netflix Streams Video\nStreaming high-definition video to millions of users simultaneously is incredibly bandwidth-intensive. The secret is **CDNs (Content Delivery Networks)** and **Adaptive Bitrate Streaming**.\n\nA CDN is a network of servers placed globally, as close to users as possible. Netflix doesn't stream video from a central server in California; they copy the video files to CDN servers placed directly inside your local internet service provider (ISP). When you hit play, you are streaming the video from a server just a few miles away.\n\nFurthermore, the video is chopped into small 5-second chunks. Each chunk is encoded at different quality levels (1080p, 720p, 480p). Your client constantly measures your internet speed. If your wifi suddenly drops, the client automatically requests the next 5-second chunk in 480p instead of buffering, creating a seamless viewing experience.",
    "Horizontal Scaling": "## Scaling Out vs Scaling Up\nWhen a server hits its limit, you have two choices: Scale Up (Vertical) or Scale Out (Horizontal).\n\n**Scaling Up** means buying a bigger, more expensive server. You upgrade from 16GB of RAM to 128GB of RAM. It's easy because you don't have to change your code, but it has a hard limit—eventually, you can't buy a bigger computer. Furthermore, it represents a single point of failure.\n\n**Scaling Out** means buying more servers of the same size. Instead of one massive server, you use 10 small, cheap servers and put a Load Balancer in front of them. This is how modern web scale is achieved. It provides infinite scalability and high availability (if one server dies, the other 9 keep working). However, it requires your application to be **Stateless** so that any server can handle any request.",
    "Round Robin": "## Load Balancing Algorithms\n**Round Robin** is the simplest algorithm a Load Balancer can use to distribute traffic among servers.\n\nImagine dealing cards to players at a poker table. You give one card to Player 1, the next to Player 2, the next to Player 3, and then loop back to Player 1. \n\nRound Robin does exactly this with HTTP requests. Request 1 goes to Server A, Request 2 to Server B, Request 3 to Server C, and Request 4 goes back to Server A. It's perfectly fair if all servers are identical and all requests take the same amount of time. However, if one request is a massive video upload and the next is a tiny text query, Server A might get bogged down. In those cases, algorithms like **Least Connections** (sending the request to the server with the fewest active tasks) are used instead.",
    "The Single Entry Point": "## API Gateways\nIn a microservices architecture, you might have 50 different backend services (Auth Service, Payment Service, User Service). If a mobile app had to memorize the IP address and port of all 50 services, it would be a nightmare to maintain.\n\nAn **API Gateway** solves this by acting as the single entry point for all client requests. The client only knows one URL (e.g., `api.myapp.com`). \n\nThe client sends a request to the Gateway, and the Gateway looks at the URL path and routes it to the correct internal microservice. It acts like a receptionist at a large office building who checks your ID and points you to the correct elevator. It simplifies the client code and hides the internal architecture of your system.",
    "Cross-Cutting Concerns": "## Beyond Just Routing\nAn API Gateway does much more than just route traffic; it handles **Cross-Cutting Concerns**—tasks that every single microservice would otherwise have to do themselves.\n\nInstead of writing authentication code, rate-limiting code, and logging code into all 50 of your microservices, you put that logic in the API Gateway. \n\nWhen a request arrives, the Gateway verifies the JWT token, checks if the user has exceeded their rate limit (e.g., max 100 requests per minute), and logs the request for analytics. Only if everything passes does it forward the request to the microservice. This keeps your microservices lightweight, focused solely on business logic, and ensures security policies are applied consistently across the entire system.",
    "The CAP Theorem": "## Understanding the Trilemma\nReiterating the CAP Theorem for system design interviews: **Consistency, Availability, and Partition Tolerance**. \n\nYou will often be asked to design a system and defend your choice between CP and AP. Remember that 'P' is not optional. Networks will fail. Switches will die. \n\nIf the interviewer asks you to design a stock trading platform, you must choose **CP**. If a network partition occurs, you must halt trading for that user rather than risk a double-spend or executing a trade at a stale price. \n\nIf you are asked to design Twitter, you choose **AP**. If a data center goes offline, it is perfectly fine if a user's timeline doesn't show the absolute latest tweet for a few seconds, as long as they can still scroll and interact with the app.",
    "Consensus Algorithms": "## Reaching Agreement in a Cluster\nIn distributed systems, how do 5 separate servers agree on the 'truth' when network delays mean they might receive data in different orders? They use a **Consensus Algorithm** like **Raft** or **Paxos**.\n\nRaft works by electing a Leader. The Leader receives a write request and sends a 'propose' message to all follower nodes. The followers write it to a temporary log and reply 'OK'. Once the Leader receives 'OK' from a *majority* of the nodes (e.g., 3 out of 5), the Leader 'commits' the data and tells everyone else to commit it. \n\nBecause it requires a majority (a quorum), the system can survive the failure of a minority of nodes. If 2 nodes out of 5 crash, the remaining 3 can still form a majority and keep the system running safely.",
    "Token Bucket": "## Rate Limiting: The Token Bucket Algorithm\nHow do companies like Stripe or Twitter ensure you don't spam their API with 10,000 requests a second? They use **Rate Limiting**, commonly implemented via the **Token Bucket** algorithm.\n\nImagine a physical bucket that holds a maximum of 100 tokens. A machine drops 1 new token into the bucket every second. Every time a user makes an API request, they must take a token out of the bucket. If the bucket is empty, the request is rejected (HTTP 429 Too Many Requests).\n\nThis algorithm is brilliant because it allows for short bursts of traffic (a user can spend all 100 tokens instantly) but enforces a strict long-term rate (only 1 request per second on average after the burst). It's incredibly fast to compute and requires very little memory to store per user.",
    "Leaky Bucket": "## Rate Limiting: The Leaky Bucket Algorithm\nAn alternative to the Token Bucket is the **Leaky Bucket** algorithm, which focuses on smoothing out traffic into a steady stream.\n\nImagine a bucket with a small hole in the bottom. Water (API requests) pours in from the top at an irregular, bursty rate. However, water drips out of the bottom hole at a perfectly constant rate. If water pours in faster than it drips out, the bucket fills up. If the bucket overflows, the excess water (new requests) is spilled and rejected.\n\nWhile the Token Bucket allows a sudden burst of requests to hit your servers all at once, the Leaky Bucket forces the requests to be processed at a strict, constant rate. This is useful when your backend servers absolutely cannot handle bursts and require a predictable, steady flow of traffic (e.g., a background job processor)."
}

if __name__ == "__main__":
    with open(TRACK, 'r', encoding='utf-8') as f:
        data = json.load(f)

    patched = 0
    for topic, topic_data in data.items():
        for lesson in topic_data.get("lessons", []):
            if lesson.get("title") in THEORY:
                lesson["theory"] = THEORY[lesson.get("title")]
                patched += 1
                
    with open(TRACK, 'w', encoding='utf-8') as f:
        json.dump(data, f, indent=2, ensure_ascii=False)
        
    print(f"Patched {patched} lessons in system_design_architecture.json")
