import os
# pyrefly: ignore [missing-import]
import google_auth_oauthlib.flow
import googleapiclient.discovery
import googleapiclient.errors
from googleapiclient.http import MediaFileUpload

# Scopes required for uploading to YouTube
scopes = ["https://www.googleapis.com/auth/youtube.upload"]

def upload_to_youtube(video_file, title, description, category_id="22", keywords=None, privacy="public", thumbnail_file=None):
    """
    Uploads a video to YouTube as a Short and sets its thumbnail.
    Requires a 'client_secret.json' file downloaded from the Google Cloud Console.
    """
    print("Preparing to upload to YouTube...")
    
    # Disable OAuthlib's HTTPS verification when running locally.
    # *DO NOT* leave this option enabled in production.
    os.environ["OAUTHLIB_INSECURE_TRANSPORT"] = "1"
    
    client_secrets_file = "client_secret.json"
    
    if not os.path.exists(client_secrets_file):
        print("Error: client_secret.json not found.")
        print("To upload to YouTube, you must create a project in Google Cloud Console,")
        print("enable the YouTube Data API v3, create an OAuth 2.0 Client ID, and download")
        print("the JSON file as 'client_secret.json' in this folder.")
        return False
        
    try:
        # Get credentials and create an API client
        flow = google_auth_oauthlib.flow.InstalledAppFlow.from_client_secrets_file(
            client_secrets_file, scopes)
        credentials = flow.run_local_server(port=0)
        
        youtube = googleapiclient.discovery.build(
            "youtube", "v3", credentials=credentials)
            
        # Video is now 3 minutes long and 16:9, so it is a standard YouTube video.
        # Removed #shorts tag to prevent algorithm confusion.
        
        request_body = {
            "snippet": {
                "title": title,
                "description": description,
                "tags": keywords or ["shorts", "facts", "ai", "viral"],
                "categoryId": category_id
            },
            "status": {
                "privacyStatus": privacy,
                "selfDeclaredMadeForKids": False
            }
        }
        
        media_file = MediaFileUpload(video_file, chunksize=-1, resumable=True)
        
        request = youtube.videos().insert(
            part="snippet,status",
            body=request_body,
            media_body=media_file
        )
        
        print("Uploading... This might take a few minutes.")
        response = request.execute()
        video_id = response['id']
        
        print(f"Video uploaded to YouTube successfully! Video ID: {video_id}")
        
        # Upload thumbnail if provided
        if thumbnail_file and os.path.exists(thumbnail_file):
            print(f"Uploading thumbnail {thumbnail_file}...")
            try:
                youtube.thumbnails().set(
                    videoId=video_id,
                    media_body=MediaFileUpload(thumbnail_file)
                ).execute()
                print("Thumbnail uploaded successfully!")
            except googleapiclient.errors.HttpError as e:
                # Custom thumbnails require a verified YouTube channel.
                if e.resp.status == 403 and b"customThumbnailsNotEnabled" in e.content:
                    print("[!] Could not upload thumbnail: Your YouTube channel is not verified for custom thumbnails.")
                else:
                    print(f"[!] Could not upload thumbnail: {e}")
            except Exception as e:
                print(f"[!] Could not upload thumbnail: {e}")
                
        return True
        
    except Exception as e:
        print(f"An error occurred during YouTube upload: {e}")
        return False

if __name__ == "__main__":
    # Test block
    upload_to_youtube("final_output.mp4", "Test AI Video", "A test video generated by AI.")
